### ISSUE TITLE
Is it possible to use library in extensions?

### ISSUE THREAD

**Issue by lolgear** [BranchMetrics/ios-branch-deep-linking#274]
Is it possible to use library in App extensions?

**Comment by aaustin** [comment]
@lolgear Unfortunately, there will be a number of build errors if so. However, if it's possible to modify the core library for extension use, we'd welcome the contribution. Realistically, we won't be able to dive in for a month or two on that project.

**Comment by aaustin** [comment]
We're happy to make ourselves available for questions if you want to tackle it!

**Comment by aaustin** [comment]
Just a note that the library is now fully compatible with extensions! Here's some docs on how to add it to iMessage https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios_imessage/
