### ISSUE TITLE
Wrong data received on cold start of app

### ISSUE THREAD

**Issue by vriznychok** [BranchMetrics/ios-branch-deep-linking#343]
I have a few controller registered for key in didFinishLaunchingWithOptions method
But when I do following steps - I receive wrong data, and controllers aren't presented.

1. Kill app
2. Click link, example: https://bnc.lt/qyyn/rI5hHFBMXs , app should present FirstController from this link
3. Application opens, but controller doesn't presented.
4. Kill app
5. Click link to another controller, https://bnc.lt/qyyn/MMPRufAMXs , app should present SecondController from this link
6. App opens. and presenting FirstController

So, app takes data from previous link
There can be empty or previous data, but not actual

When app is in background state (not killed) - everything works properly

**Comment by ahmednawar** [comment]
@vriznychok do you pass `launchOptions` to `initSessionWithLaunchOptions` in your `AppDelegate`?

**Comment by vriznychok** [comment]
Of course

I've set up everything like in testbed app

**Comment by ahmednawar** [comment]
@vriznychok so can you send us the logs after calling `setDebug` before `initSession`? If you prefer, you can email them to support@branch.io and reference the issue #

**Comment by vriznychok** [comment]
@ahmednawar
Ok , i'll send you

**Comment by dskatz22** [comment]
are there any updates on this issue, im seeing something very similar

**Comment by ahmednawar** [comment]
@dskatz22 we've moved the discussion over to support@branch.io
Are you using Facebook's SDK and return in the AppDelegate using their methods?

**Comment by dskatz22** [comment]
yes i am, can you send me the link to the discussion?

**Comment by ahmednawar** [comment]
@dskatz22 It is an internal email thread and Facebook actually hasn't come up yet..To fix your issue please take a look at https://dev.branch.io/getting-started/universal-app-links/support/ios/#using-facebooks-sdk

**Comment by ahmednawar** [comment]
@dskatz22 did this resolve your issue? (https://dev.branch.io/getting-started/universal-app-links/support/ios/#using-facebooks-sdk)

**Comment by ahmednawar** [comment]
This issue was resolved via email and the culprit was using AppsFlyer shared tracker. The solution was removing these 2 lines:

`[AppsFlyerTracker sharedTracker].appsFlyerDevKey = @"mykey";`
`[AppsFlyerTracker sharedTracker].appleAppID = @"myid";`

**Comment by ahmednawar** [comment]
@dskatz22 I'm closing this, feel free to reopen if you are still encountering any issues.
