### ISSUE TITLE
Crash in initSessionWithLaunchOptions closure

### ISSUE THREAD

**Issue by mattmcneeney** [BranchMetrics/ios-branch-deep-linking#354]
This is happening intermittently across a range of iOS devices using SDK version 0.11.18. Please see attached screenshots. Is this a known issue?

Our initialisation code looks as follows:

```swift
        if let branch = Branch.getInstance() {
            branch.initSessionWithLaunchOptions(launchOptions) { (params, error) in
                if params == nil {
                    return
                }
                // Do something with params...
        }
```

Thanks,
Matt

--

<img width="834" alt="screen shot 2016-05-23 at 10 31 19" src="https://cloud.githubusercontent.com/assets/7263436/15466639/82b1bc2a-20d2-11e6-9052-57cb0f762825.png">

Further debugging:

<img width="1117" alt="screen shot 2016-05-23 at 10 39 39" src="https://cloud.githubusercontent.com/assets/7263436/15466706/cfc9deac-20d2-11e6-855d-88f7771f7320.png">

<img width="1118" alt="screen shot 2016-05-23 at 10 39 48" src="https://cloud.githubusercontent.com/assets/7263436/15466707/d061ffd4-20d2-11e6-844f-eef7962c610e.png">

<img width="1116" alt="screen shot 2016-05-23 at 10 39 58" src="https://cloud.githubusercontent.com/assets/7263436/15466713/d35a7fcc-20d2-11e6-8e93-c1d48aee5330.png">

**Comment by aaustin** [comment]
Hey @mattmcneeney - We've never seen this one before. That code snippet in the screenshots should be executing if there's poor network connection but we've tested that extensively and don't see anything like that in the wild.

Do you happen to have a crashlytics report you could link to? What is the actual exception that's being thrown?

**Comment by aaustin** [comment]
Also, if you don't want to share on the public github repo, please send the additional crash details to support@branch.io

**Comment by mattmcneeney** [comment]
I'll try to pull up a crash report and send it over to your support email.
Thanks Alex.

**Comment by aaustin** [comment]
Sounds good @mattmcneeney - mention you're from Github and we'll make sure to update this thread after resolution.

**Comment by Liampronan** [comment]
ran into this similar crash -- seemed to be due to a bug in my code which caused some bad reference somewhere due to a mishandled DispatchGroup. If you get this error, try looking for any bad references or dispatch groups that you have related to handling branch info

**Comment by E-B-Smith** [comment]
Good catch. Blocks can be tricky with references. 

Do you have a specific example to share?
