### ISSUE TITLE
Deeplink open after applicationDidBecomeActive

### ISSUE THREAD

**Issue by PabloLerma** [BranchMetrics/ios-branch-deep-linking#362]
Hi!

After performing a deeplink from a deepview from Facebook all works as expected and we take the user to the correct content. But after that if we send the app to background or close the app the next time that we open it Branch send as the same deeplink date so we take the user to the content again.
We also open a ticket at Branch.io but we could not find the ticket number.

Thanks!

**Comment by aaustin** [comment]
Hey @PabloLerma - did you guys get taken care of in support? I'll close this if so.

**Comment by PabloLerma** [comment]
@aaustin yes, we've been attended in support, thanks!

**Comment by glennposadas** [comment]
Hi guys, I'm currently looking for a solution to this. Care to help? `didFinishLaunchingWithOptions` doesn't get invoke when returning to the app quickly from any platform such as NOTES app, rather the `applicationDidBecomeActive` is the one which gets called. So therefore I can't get the deeplinked data.

**Comment by E-B-Smith** [comment]
Did you add these lines to your app?

This is the obj-c version, but our documentation shows the Swift version too:

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    BOOL handledByBranch = [[Branch getInstance] continueUserActivity:userActivity];

    return handledByBranch;
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    [[Branch getInstance] handlePushNotification:userInfo];
}
```

**Comment by glennposadas** [comment]
Thank you, @E-B-Smith . I have implemented the `continueUserActivty`. Didn't know about that. HOWEVER, I'm still not sure if it really helps. Because when I was testing, there was one time that it didn't work. But meh. Don't have much enough time and who does what I do like testing out the deeplinking capability of an app back and forth lol.

Glenn

**Comment by E-B-Smith** [comment]
Implementing `continueUserActivty` will do the trick.  Testing deep linking is tedious because lots of things can go wrong.  That's why people use Branch, I think: we do lots of tedious testing so you don't have to.

If you have other problems, open an issue so it gets proper visibility.
