### ISSUE TITLE
SDK unreliable under bad network conditions

### ISSUE THREAD

**Issue by fluidsonic** [BranchMetrics/ios-branch-deep-linking#369]
The SDK is unreliable when launching the app (or opening a deep link) under bad network conditions.

## Actual Behavior

After launching the app the SDK tries to load deep link information by contacting the Branch server. Should the server be unavailable due to a network-related issue then the SDK immediately gives up completely until the user moves the app to the background and back to the foreground.

In such cases the deep link information is not available during that session even if the network issue was just temporary.

## Expected Behavior

I expect that the SDK keeps trying to load deep link information (esp. the installation referral) until it succeeded doing so. That way the info can still be used for example after the user completed the sign-up process, even though that info wasn't available immediately after app launch.

## Steps to Reproduce

1. App is not installed.
2. Tap on a Branch deep link.
3. Safari will open.
4. App Store will open since the app is not installed.
5. Install the app.
6. Disable network connections (e.g. by turning on Airplane Mode)
7. Open the app.
8. After a few seconds, re-enable network connections.
9. Try to access the referral parameters.
10. Referral parameters & other deep link information are not available even minutes after the network is working again.

**Comment by aaustin** [comment]
Hey @fluidsonic - Thanks so much for the clearly documented issue. I understand the frustration in this case. We decided that we'd only retry a fixed number of times before giving up. Any further Branch calls or reopening the app will trigger a new set of retries but it's limited in number.

For your use case, can you play around with our retry customization endpoints to see if you can set this to a level that is acceptable for your use case. I'd point you to this method: `setMaxRetries` which defaults to 1. https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Branch.h#L407 You can set it to whatever number you want. Also, you can control the interval between retries with the method above, `setRetryInterval`.

Let me know if this resolves your issue!

**Comment by fluidsonic** [comment]
@aaustin for networking issues there is no retry. 

As a temporary workaround we started calling `initSession...` again, slightly delayed after the deep link callback was called with an error.

**Comment by aaustin** [comment]
Ah - you're talking about actual network failure. My mistake. Yes.. currently we presume that the app will be offline for a while and it wouldn't be prudent to continue retrying. That assumption is based on our hypothesis that this would happen mostly during airplane mode. Have you guys seen otherwise?

Just FYI in case you want to modify the source, here's where we make the call whether or not to retry. https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCServerInterface.m#L90 Effectively, if it's a 500 error from the server is the only time we will retry. I just tested and if in airplane mode, this code is -1009. It'd be quick to add an exception for your release if you're concerned about it.

**Comment by fluidsonic** [comment]
Well, we're talking about mobile apps here. Your phone can easily have slow or unstable network connections when you are in a location with spotty network coverage. One network connection may fail while the next one succeeds.

I really expect 3rd-party libraries for mobile apps to handle such situations properly and not give up upon error. Should the user sign up while having spotty network coverage (which is not uncommon, esp. not for our app) then we'll likely fail to properly attribute that sign-up and may also fail to properly attribute credits later on should the user not relaunch/reactivate the app at some point.

Even now, in the iPhone Simulator on my Mac using a WiFi connection(!), I got a random network issue! Everything worked fine except that the Branch SDK call failed for whatever reason. Things like that can happen.

```
2016-06-14 16:55:20.222 App[35391:181898] [BNCServerInterface.m:123] An error prevented request to https://api.branch.io/v1/open from completing: The request timed out.
2016-06-14 16:55:20.222 App[35391:181041] Branch failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://api.branch.io/v1/open, _kCFStreamErrorCodeKey=-2102, NSErrorFailingURLKey=https://api.branch.io/v1/open, NSLocalizedDescription=The request timed out., _kCFStreamErrorDomainKey=4, NSUnderlyingError=0x7f6ad220 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102}}}
```

Like I said earlier, we'll use our workaround for now. But this is still an issue of the SDK itself.

**Comment by aaustin** [comment]
Thanks @fluidsonic. Appreciate the feedback. Let me scope this out and think about incorporating it into the next release.

**Comment by fluidsonic** [comment]
Thank you for taking care of this @aaustin.
Please let me know if you need more feedback or when there is something to test.

**Comment by ahmednawar** [comment]
@fluidsonic We've issued a release yesterday with a patch for this issue. Will close the issue but feel free to reopen if you encounter any problems. Cheers!
