### ISSUE TITLE
BranchLinkProperties.h has no campaign property

### ISSUE THREAD

**Issue by SebC99** [BranchMetrics/ios-branch-deep-linking#380]
We can't set the campaign property of the universal links, as it is not available in branchlinkproperties.h

**Comment by aaustin** [comment]
Hey @SebC99 - We left it out as we felt that it didn't make sense from a product perspective. How were you planning on using the field?

**Comment by SebC99** [comment]
Not sure, but it's in the docs and in the dashboard... so we wanted to try with app version number to compare links results between app version

**Comment by aaustin** [comment]
I'd recommend using the Tags array field for that!

**Comment by SebC99** [comment]
that's what we've done :)

**Comment by aaustin** [comment]
Closing this then. Happy linking!
