### ISSUE TITLE
add @subject to showShareSheetWith* methods

### ISSUE THREAD

**Issue by athibaud** [BranchMetrics/ios-branch-deep-linking#383]
As far as I can tell, `subject` is used only for the email sharing option as the email subject..

There are two ways to implement this:
- the ["correct" way](http://stackoverflow.com/a/28072306) via the [activityViewController:subjectForActivityType: protocol](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIActivityItemSource_protocol/index.html#//apple_ref/occ/intfm/UIActivityItemSource/activityViewController:subjectForActivityType:)
- the ["easy but undocumented" way](http://stackoverflow.com/a/28070555), by simply setting a `@subject` key to the `activityController`

I could create a PR for the second because its very straight forward but I have no iOS/objective-C experience at all so I would struggle a little more to implement le the first method.
What API would you want for this? `showShareSheetWithSubjectText:` `showShareSheetWith*: andSubjectText:` etc?

My use case is to ensure that the [`messageHeader` key of the `shareOptions` param of the `react-native-branch` module is taken into account on iOS too](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/ae270b18229b0e3d28ffdb794298c40d6b1d2a67/README.md#shareoptions)

**Comment by aaustin** [comment]
Thanks for the suggestion @athibaud. It does seem quite easy. We'll get this bundled into iOS for the next release.

**Comment by aaustin** [comment]
@athibaud On closer inspection, we do actually expose it but it's a bit hidden. I added it to the react native SDK in this PR: https://github.com/BranchMetrics/react-native-branch-deep-linking/pull/26

**Comment by aaustin** [comment]
Please follow that PR. Closing this issue.

**Comment by athibaud** [comment]
perfect. thanks!
