### ISSUE TITLE
Building the Carthage project fails since the last commit

### ISSUE THREAD

**Issue by lvandal** [BranchMetrics/ios-branch-deep-linking#392]
Building the Carthage project fails since the last commit:

> error: unable to read module map contents from '/Users/ahmed/Documents/git_repos/iOS-Deferred-Deep-Linking-SDK/carthage-files/module.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “module.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmed/Documents/git_repos/iOS-Deferred-Deep-Linking-SDK/carthage-files/module.modulemap, NSUnderlyingError=0x7fca15e0d820 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
error: unable to read module map contents from '/Users/ahmed/Documents/git_repos/iOS-Deferred-Deep-Linking-SDK/carthage-files/module.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “module.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmed/Documents/git_repos/iOS-Deferred-Deep-Linking-SDK/carthage-files/module.modulemap, NSUnderlyingError=0x7fca15de7cd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
A shell task (/usr/bin/xcrun xcodebuild -project /Users/lucvandal/Repositories/Screens 4/screens-4-ios/Vendor/Carthage/Checkouts/iOS-Deferred-Deep-Linking-SDK/carthage-files/BranchSDK.xcodeproj -scheme Branch iOS SDK Carthage -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

**Comment by ahmednawar** [comment]
@lvandal Thanks for reporting! Will push a fix today

**Comment by ahmednawar** [comment]
@lvandal I've updated the Carthage project. Could you please test and let me know how it goes? Cheers!

**Comment by siemensikkema** [comment]
@ahmednawar checking out the latest release (0.12.4) still triggers this problem. I'll try using a later commit but could you please push a new release?

**Comment by siemensikkema** [comment]
The problem persisted so I created a PR, see: #395.

**Comment by ahmednawar** [comment]
@lvandal @siemensikkema We've pushed a new update that should fix the module map problem. Could you please test and let us know if you still encounter any issue?

**Comment by siemensikkema** [comment]
@ahmednawar it works if I force Carthage to check out "master". It does not automatically check out 0.12.5.

**Comment by ahmednawar** [comment]
@siemensikkema can you please try again? I've uploaded the archived framework to the public release.

**Comment by siemensikkema** [comment]
@ahmednawar Ok, this is a little embarrassing ... It totally works now but it probably was working before because I totally overlooked that I was still referring to **my own fork** in my `Cartfile`. 😳

**Comment by ahmednawar** [comment]
this what makes it fun :) Let me know if you encounter any issues with Carthage. Cheers!
