### ISSUE TITLE
Outdated pod?

### ISSUE THREAD

**Issue by rafaellage** [BranchMetrics/ios-branch-deep-linking#400]
Hi,

I noticed that the version of the sdk in cocoapods is outdated, for example, i could not find the method "applyPromoCode".

**Comment by ahmednawar** [comment]
@rafaellage The pod is up to date, however as of 0.12.4, we removed some deprecated methods from the SDK including `applyPromoCode`.

Here are the relevant parts from the ChangeLog:

>setDebug must be called on getInstance. It's no longer a static method.
referral code and promo code methods are no longer available
action count methods are no longer available
getReferralUrl removed - please migrate to BUO
getContentUrl removed - please migrate to BUO
BUO showShareSheet andCallback method deprecated - migrate to showShareSheet callback.

Let me know if you have any questions.

**Comment by rafaellage** [comment]
Ok, so what method i have to use to apply a promo code inside the app?

**Comment by aaustin** [comment]
Hey @rafaellage  - Unfortunately, to continue using promo codes, you'll need to lock to version 0.12.4. We no longer plan to maintain this part of the platform. Sincere apologies for the inconvenience.
