### ISSUE TITLE
Swift - does not conform to protocol 'BranchDeepLinkingController'

### ISSUE THREAD

**Issue by macpraveen** [BranchMetrics/ios-branch-deep-linking#407]
I am getting the following error. I'm using Xcode 7.2.1 Swift 2
![screen shot 2016-08-17 at 12 15 23 am](https://cloud.githubusercontent.com/assets/4463109/17711843/0958a2a8-6411-11e6-9e11-c27caf3176c2.png)

I have implemented the method 

    func configureControlWithData(data: [NSObject : AnyObject]!) {
    }

**Comment by aaustin** [comment]
Hey @macpraveen - Apologies here but `BranchDeepLinkingController` will only work with classes that subclass `UIViewController`. `UINavigationController` doesn't fall in this category. Please use it in that capacity.
