### ISSUE TITLE
Archive with BitCode check fails

### ISSUE THREAD

**Issue by damien-nd** [BranchMetrics/ios-branch-deep-linking#408]
I do have all my frameworks compatible with bitcode.
It was working fine on 0.12.4 I guess but now it fails on both with 0.12.5.

When I archive I get this errors:
[https://s3.postimg.org/fpw9yvwjn/Branch_Errors.png](https://s3.postimg.org/fpw9yvwjn/Branch_Errors.png)

Anyone getting the same problem?

**Comment by damien-nd** [comment]
Update: Look lite without bitcode it's not working.
Maybe it is a carthage error?

I do 'clean' and 'clean build folder', then use 'carthage update --platform ios' and use latest version of Branch.

When I archive to make a testflight version I always get the errors, whatever I check or not the bitcode enable.

**Comment by ahmednawar** [comment]
@damien-nd sorry to hear that you are having trouble. The image URL you posted gives 404. Could you please update the link so that I can see the error you are getting.

**Comment by damien-nd** [comment]
Sorry, the link is wrong but the text is good.
The good link is https://s3.postimg.org/fpw9yvwjn/Branch_Errors.png <https://s3.postimg.org/fpw9yvwjn/Branch_Errors.png>

 <http://www.octopepper.com/> <http://www.octopepper.com/>
Damien NOEL DUBUISSON
iOS / Android developer	 <http://octopepper.com/contact.php>
damien@octopepper.com <mailto:mathieu@octopepper.com> | +33(0)9 50 27 90 74

**Comment by damien-nd** [comment]
I'm really sorry for the issue.
I end by deleting all Carthage folders, clean builds folder and clean app.
Then I restart all carthage configuration in build phases.

Now everything is working fine. So maybe in long use Carthage mixed up some files, but nothing on your side.
Again sorry for that and will enjoy to continue with branch.

**Comment by ahmednawar** [comment]
Glad you figured it out. Happy Deep linking!
