### ISSUE TITLE
UniversalObject doesn't contain proper type

### ISSUE THREAD

**Issue by gbitaudeau** [BranchMetrics/ios-branch-deep-linking#419]
Hi,

In callback of `public func initSessionWithLaunchOptions(options: [NSObject : AnyObject]!, andRegisterDeepLinkHandler callback: callbackWithParams!)` universalObject retrieved doesn't contain any type attribute whereas it's present in callback params (`$content_type`).

Basically, I think it's just a forgetting in = `BranchUniversalObject.getBranchUniversalObjectFromDictionary`

**Comment by ahmednawar** [comment]
@gbitaudeau Thanks for reporting! I've submitted a PR #421 and it will go out with our next release next week. Let me know if this doesn't solve your issue.

Cheers!

**Comment by ahmednawar** [comment]
@gbitaudeau we've cut a release yesterday which contained the fix for this. Closing here and feel free to re-open if this is still an issue. Cheers!

**Comment by gbitaudeau** [comment]
@ahmednawar your correction works ! 
Thank you.

**Comment by ahmednawar** [comment]
@gbitaudeau Awesome. Happy Deep linking!
