### ISSUE TITLE
Share sheet helper (and possibly other shortURL methods) intermittently returns large, non-short URLs

### ISSUE THREAD

**Issue by mwkas** [BranchMetrics/ios-branch-deep-linking#422]
I have successfully integrated the Branch iOS SDK and I'm using the share sheet helper to create and share links. The problem I am facing is that I am occasionally getting very long share URLs (large number of query parameters) when I should be receiving the short URL. If I restart my app and try sharing again it usually works and I get given a correct short URL. Is this a known issue?

**Comment by aaustin** [comment]
Hey @mwkas - How frequently are you seeing this? This should occur on a very rare occurrence. We fallback to generating a long URL with all relevant parameters when there are connectivity issues. Are you testing on a solid connection?

One option is to up the retryCount https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Branch.h#L407 or networkTimeout https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Branch.h#L414.

Please share your thoughts.

**Comment by mwkas** [comment]
Yeah I assumed it was a safe fallback if the shortening request fails. During the couple of days of integration and testing I'd seen it about 4ish times. All on a very good connection.

**Comment by aaustin** [comment]
Where are you based if you don't mind me asking? Also, try bumping up those counts I linked to above and let me know if you still observe it.

**Comment by mwkas** [comment]
We're based in London. I'll up the counts and see if I still experience the issue. Thanks!

**Comment by aaustin** [comment]
Going to close for the time being.

**Comment by JPROFFICIAL** [comment]
@aaustin This exact problem is still occuring with me. Before initializing in the App Delegate, I am setting `branch.networkTimeout` to 50.0 and `branch.setMaxRetries` to 50. I am also on a very good connection. The weird thing is, This bug is only happening in one spot in our application where we are setting 30+ Metadata keys in our BranchUniversalObject.

**Comment by aaustin** [comment]
Hey @JPROFFICIAL - Thanks so much for the note. I have a hypothesis that it's related to one of your keys. Is it possible that you call 1. setDebug before initializing to turn on logging, 2. attempt to create this link and 3. send us the logs (you can start a new ticket at integrations@branch.io).

One hypothesis I have is that our request to one of your URLs could be timing out. Our link creation process will attempt to scrape your $desktop_url, $fallback_url or $canonical_url to pre-fill some open graph tags. If this URL times out when we crawl it, it will significantly delay (and maybe time out) the link creation process. We can check if this is it once you send us an example link POST body.
