### ISSUE TITLE
loadRewardsWithCallback: method never calls callback

### ISSUE THREAD

**Issue by alexruperez** [BranchMetrics/ios-branch-deep-linking#424]

**Comment by alexruperez** [comment]
I get "[Branch Error] User session has not been initialized!" but the queue is never freed.
I think issue #227 should be reopened.

**Comment by aaustin** [comment]
Hey @alexruperez - Just gave `loadRewardsWithCallback` a try on our testbed app and it works just fine. https://github.com/BranchMetrics/ios-branch-deep-linking/tree/master/Branch-TestBed

Is this happening 100% of the time for you? Can you confirm you've gone through the onboarding steps (added key, setup plist, added app delegate methods, etc)? https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/

**Comment by alexruperez** [comment]
Everything is properly configured and has worked for months, it could be a bug in the new Facebook Ads integration?

`[[Branch getInstance] registerFacebookDeepLinkingClass:[FBSDKAppLinkUtility class]];`

**Comment by aaustin** [comment]
Hmm - I wonder if it's a Facebook SDK change. Perhaps you updated us both at the same time. Have you confirmed when you remove that line it works fine?

**Comment by alexruperez** [comment]
@aaustin confirmed, the problem is that line.

**Comment by aaustin** [comment]
I'll investigate today and try to get it in the next release. We have one going out today, but it'll be in the next one if there's a bug.

In the meantime, to unblock you, could you use the server side Facebook integration we have? It's actually faster anyways. https://dev.branch.io/features/facebook-ads/guide/ios/#option-1-connect-without-using-facebook-sdk

**Comment by alexruperez** [comment]
Done, thanks!

**Comment by aaustin** [comment]
@alexruperez I'm having some trouble reproducing on my side. I just loaded up the new Facebook SDK, and called the following:

```
[[Branch getInstance] registerFacebookDeepLinkingClass:[FBSDKAppLinkUtility class]];
[[Branch getInstance] setDebug];
// Initalize Branch and register the deep link handler
// The deep link handler is called on every install/open to tell you if the user had just clicked a deep link
[[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandlerUsingBranchUniversalObject:^(BranchUniversalObject *BUO, BranchLinkProperties *linkProperties, NSError *error) {
    NSLog(@"init session returned!");
}];
[[Branch getInstance] loadRewardsWithCallback:^(BOOL changed, NSError * _Nullable error) {
    NSLog(@"loaded rewards");
}];
```

In this case, `loaded rewards` is printed before `init session returned!` but it's returned nonetheless. I need to issue a patch to correct the order, and I've got that in a branch now. However, I want to patch the issue you were seeing. Can you share the code you used?

**Comment by alexruperez** [comment]
@aaustin try this code (on a fresh install, it only happens the first time, and later the queue remains frozen).

```objective-c
[Fabric with:@[Crashlytics.class, Twitter.class, Branch.class]];

Branch *branch = [Branch getInstance];

[branch setDebug];

[branch registerDeepLinkController:MyBranchDeepLinkingController.new forKey:BRANCH_INIT_KEY_X];

[branch registerFacebookDeepLinkingClass:[FBSDKAppLinkUtility class]];

[branch initSessionWithLaunchOptions:launchOptions automaticallyDisplayDeepLinkController:YES];

[branch setIdentity:@"MyUserID"];

[branch registerViewWithParams:@{} andCallback:nil];

[branch userCompletedAction:@"MyAction" withState:@{}];

[branch loadRewardsWithCallback:^(BOOL changed, NSError * _Nullable error) {
    NSLog(@"loaded rewards: %d", branch.getCredits);
}];
```

Hope it helps. 👍

**Comment by aaustin** [comment]
I still quite reproduce, but I'm 90% sure this will resolve it. https://github.com/BranchMetrics/ios-branch-deep-linking/pull/428

**Comment by alexruperez** [comment]
Yeah, #428 fix the issue, thanks @aaustin! 😃
