### ISSUE TITLE
Logs of nullability warnings in BranchUniversalObject with swift project

### ISSUE THREAD

**Issue by briankracoff** [BranchMetrics/ios-branch-deep-linking#427]
As of the Xcode8 GM, building with `v0.12.7` is giving us a ton of nullability warnings. Doesn't seem to break things though. We're running Cocoapods `1.1.0.beta.1` in a swift project with `use_frameworks`.

![screen shot 2016-09-08 at 9 54 12 am](https://cloud.githubusercontent.com/assets/1471922/18351991/7a41b4fa-75aa-11e6-8593-3f6815209299.png)

**Comment by aaustin** [comment]
Thanks so much for the issue @briankracoff. We've got this patched in a PR https://github.com/BranchMetrics/ios-branch-deep-linking/pull/426 and plan to merge it in after a bit more testing. Expect the new release early next week.

**Comment by briankracoff** [comment]
Awesome thanks! Feel free to close this
