### ISSUE TITLE
branch_key not found when nested in Fabric dictionary of Info.plist as live/test dictionary

### ISSUE THREAD

**Issue by benjaminjackson** [BranchMetrics/ios-branch-deep-linking#429]
Looks like the SDK doesn't detect the key when it's nested inside the Fabric dictionary as a "live/test" dictionary rather than a single key.

When the key is top-level in the plist, the SDK checks for both a string and a dictionary:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCPreferenceHelper.m#L172-L177

However, when it's nested, the code only checks for the string variant:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCPreferenceHelper.m#L185-L187

Copying the checks from the former case into the latter should resolve the issue. For now, we've kept the keys in the top level of the plist and it's working as expected.

**Comment by aaustin** [comment]
Ack! Good find. Thanks so much for letting us know. We'll get this patched right away.

**Comment by benjaminjackson** [comment]
🔥 👍

**Comment by aaustin** [comment]
Merged to prod!
