### ISSUE TITLE
Crash on startup with branch SDK 0.12.7 on iOS 7

### ISSUE THREAD

**Issue by pymaurice** [BranchMetrics/ios-branch-deep-linking#432]
Hi,

The SDK v0.12.7 is crashing on iOS 7 due to a call to NSString `- (BOOL)containsString:(NSString *)str` in BNCServerInterface` - (NSDictionary *)prepareParamDict:(NSDictionary *)params key:(NSString *)key retryNumber:(NSInteger)retryNumber` (line 235)

It's working fine with 0.12.6.

**Comment by ahmednawar** [comment]
@pymaurice thanks for reporting! We are currently investigating and will get back to you.

**Comment by ahmednawar** [comment]
@pymaurice I've submitted a PR #433 to address this issue. Could you please test and let us know how it goes.

**Comment by aaustin** [comment]
This has been deployed to prod. Apologies for the crash there!
