### ISSUE TITLE
showShareSheetWithLinkProperties doesn't distinguish between canceled and failed

### ISSUE THREAD

**Issue by kballard** [BranchMetrics/ios-branch-deep-linking#436]
`showShareSheetWithLinkProperties` doesn't pass the `activityError` to the completion block, so the calling code can't distinguish between the user canceling the share, and the share failing.

**Comment by kballard** [comment]
Hmm, it used to pass the `activityType` string as a nullable string, which makes sense because UIKit defines it as a nullable string, and it seems likely that UIKit returns `nil` if the user cancels. But at some point Branch updated its header to mark that parameter as nonnull, even though it never actually checks if the `activityType` is `nil`, meaning if UIKit does pass `nil`, Branch will claim it's not nil, and Swift code will crash (and obj-c code will get an unexpected `nil`, which may or may not crash depending on what it does with it).

**Comment by aaustin** [comment]
Hey @kballard - Looking into this now and will update here.

**Comment by aaustin** [comment]
Hey man - I added a new callback that will support error passthrough. Enjoy!

**Comment by kballard** [comment]
Thanks!

**Comment by Atoyebs** [comment]
Hi, i've been looking for a solution to the above problem not being able to distinguish between cancel and anything else. When the user posts successfully completed = true. When the user presses the cancel button and doesn't go through with the post completed = true.

As a result It seems impossible to tell if the user has cancelled the action or successfully posted.

I might be missing something from this thread or might have misunderstood. Apologies if I have, but does this PR solve the problem I've just described? I realise that if there is an error posting to social media we can now access it by the block NSError variable, but the `activityType` returns the same string whether or not the user cancels or posts.

clarity on this would be greatly appreciated.

Thank You

**Comment by aaustin** [comment]
Hey @Atoyebs - Thanks for the note. Here's the example method call that will allow you to try to retrieve the NSError. I added this new block callback type in 0.12.9.
```
[self.branchUniversalObject showShareSheetWithLinkProperties:linkProperties andShareText:shareText fromViewController:self completionWithError:^(NSString * _Nullable activityType, BOOL completed, NSError * _Nullable activityError) {
        
}];
```
In the case of a use not completing, completed will be NO. Then, you can check the activity error to gather evidence of any issues with the share.

Hope this helps!

**Comment by Atoyebs** [comment]
Thanks @aaustin, upon further testing i've just realised that the issue is unique to The "reminders" and "WhatsApp" app. It works correctly for Facebook and Twitter.
If you have any workarounds or solutions please feel free to share, but your response was helpful.
