### ISSUE TITLE
BranchUniversalObject's initializers should not be nullable

### ISSUE THREAD

**Issue by kballard** [BranchMetrics/ios-branch-deep-linking#448]
`BranchUniversalObject`'s initializers are now marked as returning a `nullable` object. This is incorrect and makes creating these objects annoying in Swift. `BranchUniversalObject`'s initializers all return a nonnull object if `[super init]` does, and `-[NSObject init]` returns a nonnull object, so `BranchUniversalObject`'s initializers will never return `nil`. I don't think `<objc/NSObject.h>` has nullability annotations, but `-[NSObject init]` definitely returns nonnull (specifically, it's implemented as `return self`), and the Swift overlay module explicitly makes it nonnull.

**Comment by aaustin** [comment]
Thanks for the feedback Kevin - We'll get this patched for the release next week!

**Comment by aaustin** [comment]
Merged in here for next release https://github.com/BranchMetrics/ios-branch-deep-linking/pull/451

**Comment by aaustin** [comment]
This has been resolved in v0.12.10. Thanks so much for your contributioN!
