### ISSUE TITLE
Init callback not being called in latests versions.

### ISSUE THREAD

**Issue by fceldeiro** [BranchMetrics/ios-branch-deep-linking#454]
I'm having the following issue with the latest versions.
I'm force killing the app, tapping on the link and the init callback is never being called.
I rolled back to version 0.12.5 and it started working again.

I debugged your code a little bit and found out that the property `shouldWaitForInit` may be the issue.
```
- (void)processNextQueueItem {
    dispatch_semaphore_wait(self.processing_sema, DISPATCH_TIME_FOREVER);
    
    if (self.networkCount == 0 && self.requestQueue.size > 0 && !self.preferenceHelper.shouldWaitForInit) {
        self.networkCount = 1;
        dispatch_semaphore_signal(self.processing_sema);
        
        BNCServerRequest *req = [self.requestQueue peek];
      
```

This is in the Branch.m class.
The network count is -, the queue.size is > 0 but the shouldWaitForInit is true at this point.

In your previous version the `0.12.5.` you don't have that property to validate.
```
- (void)processNextQueueItem {
    dispatch_semaphore_wait(self.processing_sema, DISPATCH_TIME_FOREVER);
    
    if (self.networkCount == 0 && self.requestQueue.size > 0) {
        self.networkCount = 1;
        dispatch_semaphore_signal(self.processing_sema);
        
        BNCServerRequest *req = [self.requestQueue peek];
        
        if (req) {
            BNCServerCallback callback = ^(BNCServerResponse *response, NSError *error) {
           
```
And everything is working correctly in the scenario i'm having.

**Comment by aaustin** [comment]
Hey @fceldeiro - Thanks so much for the note here. We simultaneously got a bug report of the same thing earlier this afternoon and have issued an emergency patch here: https://github.com/BranchMetrics/ios-branch-deep-linking/pull/453

We're doing final QA on the fix and hope to deploy tomorrow morning. We're not sure how this case slipped through our QA but we've added additional checks for this scenario so that it can't happen again.

Apologies for the inconvenience, but all should be well by midday tomorrow.

**Comment by aaustin** [comment]
Hey @fceldeiro: According to our internal tests and QA, we've resolved this in v0.12.10. Can you confirm? We want to make sure there isn't another issue that we haven't been able to reproduce yet.

**Comment by fceldeiro** [comment]
Hey @aaustin : Having troubles with the link (It's saying There was a minor issue on the server . The team has been notified and are looking into it) So I can't confirm yet if it was fixed.

**Comment by aaustin** [comment]
Hey @fceldeiro - We had a brief blip on the service due to a bad database restart. Sincere apologies. It was all hands on deck here for a few minutes.

Can you try again?

**Comment by fceldeiro** [comment]
@aaustin Confirmed, it works now for both cases, fresh install and with the app already installed!
Thanks for the fast fix!
