### ISSUE TITLE
Cannot convert value of type '(String?, NSError?) 

### ISSUE THREAD

**Issue by oddpanda** [BranchMetrics/ios-branch-deep-linking#457]
I get this error with the following code after updating to Swift 3

`Cannot convert value of type '(String?, NSError?) -> Void' to expected argument type 'callbackWithUrl' (aka '(String, Optional<Error>) -> ()')`

        branchUniversalObject.getShortUrlWithLinkProperties(linkProperties,  andCallback: { (url: String?, error: NSError?) -> Void in
            if error == nil {
                self.socialLink = url
                print("got my Branch link to share: %@", url)
            }
        })

I checked the latest documentation and couldn't see the issue

**Comment by aaustin** [comment]
Hey @oddpanda - Thanks for the note here. Investigating it now!

**Comment by aaustin** [comment]
Hey @oddpanda - Yikes. The docs weren't updated when we changed the nullability state of the Branch Universal Object. I've just fixed them now. Can you try to replace your current line with the following:

```
branchUniversalObject.getShortUrl(with: linkProperties,  andCallback: { (url: String, error: Error?) in
    if error == nil {
        self.socialLink = url
        print("got my Branch link to share: %@", url)
    }
})```

**Comment by oddpanda** [comment]
Perfect!
