### ISSUE TITLE
continueUserActivity is returning true for non-branch links

### ISSUE THREAD

**Issue by MikeSilvis** [BranchMetrics/ios-branch-deep-linking#464]
Calling `[[Branch instance] continueUserActivity:userActivity]` from a spotlight search, returns true for the activity 

Using the latest release: `0.12.11`

**Comment by aaustin** [comment]
Hey @MikeSilvis - Thanks for the heads up. If you're using Branch to track/deep link from Spotlight,  it should correctly return YES, indicating that we've handled it https://dev.branch.io/features/spotlight-indexing/guide/

You can review how the code handles YES/NO logic here: 
https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Branch.m#L443 and https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m#L41. You see that it will only return YES if the Branch key is found in the userInfo dictionary.

**Comment by aaustin** [comment]
Please let me know if I'm misinterpreting.

**Comment by MikeSilvis** [comment]
@aaustin i think the issue is this line https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m#L49 where you aren't actually enforcing that the branch key is present but simply that it is a spotlight search OR it is a branch spotlight search

**Comment by MikeSilvis** [comment]
@AustinHay any update on this ?

**Comment by ahmednawar** [comment]
@MikeSilvis Hi Mike, thanks for the suggestion. We have a PR #470 here that should fix this. Could you please test and let us know if it fixes the issue. If so, we will include it in our upcoming release.

**Comment by MikeSilvis** [comment]
Great, thanks!

**Comment by E-B-Smith** [comment]
@MikeSilvis:  We made a slight change to the fix so that older code doesn't break.  The fix should still work for you.

**Comment by MikeSilvis** [comment]
@E-B-Smith @AustinHay hey, when do you guys expect to have your next release?

I am noticing an issue now where because i had to re-arrange the logic with the branch check in my `continueUserActivity` that i am short circuiting before getting to you causing an error. Furthermore when I receive a universal link `Branch.instance().initSessionWithLaunchOptions` seems to drop the `$deeplink_path` from the completion block. 

Because of this, I am currently losing all universal branch deeplinks

**Comment by E-B-Smith** [comment]
@MikeSilvis 

We released version v0.12.12 last week which should fix your problem.  Have you updated the SDK in your app and tested it yet?
