### ISSUE TITLE
Tell branch that I well handle a deep link to avoid duplicate handle

### ISSUE THREAD

**Issue by gbitaudeau** [BranchMetrics/ios-branch-deep-linking#466]
I use :
```
branch.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { params, error in
//do awesome stuff
})
```

The fact is that I also implements notifications in my application (without deep link inside but a custom sauce)

Here my use case :

1. I use a branch deep link to open my application on a special screen (using handler define in initSession)
2. Later application go background
3. A notification is received and I use it to open my application again (it goes foreground)
4. The handler is call again whereas I don't want ...

Perhaps the problem come from the fact that I don't call :
```
- (void)handlePushNotification:(NSDictionary *)userInfo;
```

 Can we have a method on branch to indicate when a link is fully managed and we no more need to handle it ?
Perhaps the handler can call a block when job is done ...

**Comment by ahmednawar** [comment]
@gbitaudeau just to clarify, did you get the *same* link data in the `deepLinkHandler` twice?

The handler gets called every time the app become active but you should get the link data, the first time only.

**Comment by gbitaudeau** [comment]
Yes, I get twice the same universal object using `branch.getLatestReferringBranchUniversalObject()`

**Comment by ahmednawar** [comment]
@gbitaudeau Where do you call `getLatestReferringBranchUniversalObject`?  If you just log the value of the `params` dictionary passed to the `deepLinkHandler`, do you get the same result as well?

**Comment by gbitaudeau** [comment]
I can't reproduce anymore ... 
Either I update something, either the case to reproduce is more complex .... 
Please close this, I will re-open it if I have more elements !
