### ISSUE TITLE
Handle branch link (incoming) in iMessage extension

### ISSUE THREAD

**Issue by SebC99** [BranchMetrics/ios-branch-deep-linking#469]
It's easy to generate a branch link to associate to a iMessage to send, but then for the receiver, I can't find any way to handle the message link.
When a user click on a received iMessage, it opens the message extension but doesn't fire the branch callback, and there's no available method to tell branch to handle the received message URL.
How could we do that? 
The `handleDeepLink` method doesn't fire Branch server request as Branch considers itself as already initialized.
Thanks

**Comment by aaustin** [comment]
Hey @SebC99 - Thanks for the question! Let me understand the flow so I'm 100% certain:

0. You're testing with an iMessage app that has integrated Branch according to my guide here:  https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios_imessage/
1. A link is sent to one of your users with your iMessage extension installed
2. You receive the MessageViewController delegate call with the message and the Branch link
3. You'd like to parse out the Branch link, give it to Brancb and then deep link route the to extension based on the data with that link

If that flow is correct, then we currently don't have a tailored solution for it. Can you share your product use case? I want to make sure I wrap my head around the solution.

Here's the hack you can use in the interim: call [[Branch getInstance] handlePushNotification:{@"branch": <link here>}]; It will correctly close the session and open a new one referred by the link you pass in. Give it a try and let me know your thoughts!

**Comment by SebC99** [comment]
Yes that's it!

1. A link is sent to a user with my iMessage extension installed
2. the MessageViewController is opened with the conversation.selectedMessage containing the branch link as selectedMessage.URL
3. I'd like to parse out the Branch link with a BNCServerRequest to route the user to the right viewController of my extension

For now, I have to send a longURL with the iMessage and parse the base64encoded query string to obtain the data, but it's a huge link and it's very ugly for people without iOS10 (fallback)
The shortURL would be a perfect fallback

I'll try the interim!

**Comment by SebC99** [comment]
Well unfortunately, it doesn't work as
```[[UIApplicationClass sharedApplication] applicationState] == UIApplicationStateActive```
is false in the extension (the `[UIApplication sharedApplication]` is in background....

**Comment by SebC99** [comment]
I tried to bypass the `UIApplicationStateActive` test creating my own function as a (dirty) category... It passes and parses the link well, but then each time the same user open the iMessage extension, the link is considered as clicked and passed to the deepLinkHandler!

```objective-c
@implementation Branch (force)
- (void)handleLink:(NSURL *)URL {
    [self performSelector:@selector(callClose)];
    if (URL) {
        [BNCPreferenceHelper preferenceHelper].universalLinkUrl = URL.absoluteString;
    }
    [self performSelector:@selector(applicationDidBecomeActive)];
}
@end
```

**Comment by aaustin** [comment]
Ahh - I was unaware the application was in the background when you received the link. I understand better now. You receive the link in `didReceiveMessage` but Branch is initialized in `didBecomeActiveWithConversation`.

 Is `didReceiveMessage` being called before `didBecomeActiveWithConversation` in your use case? Assuming so, can you try the following:
1. In `didReceiveMessage`, create a NSUserActivity with `activityType` set to `NSUserActivityTypeBrowsingWeb` and set the `webpageURL` to the Branch link in `NSUrl` form.
2. Call `[[Branch getInstance] continueUserActivity:userActivity];` with this userActivity.

This will tell Branch that the app was opened via a URL, and will initialize the session using that URL. The only risk is if `didBecomeActiveWithConversation` is called *before* `didReceiveMessage`, in which case `initSession` will fire off the initialization request before you get a chance to receive and pass in the URL. If this is the case, we'll think of a new route.

**Comment by SebC99** [comment]
No no, we receive the link in `didBecomeActiveWithConversation` as the link is included in the `selectedMessage` property of the `conversation` passed as parameter of `didBecomeActiveWithConversation`
And I guess that in iMessage when you test for the `UIApplication` being active, it doesn't test if the iMessage extension is, but if the linked application is. And of course, when you're in the iMessage extension, you're not in the main Application which is in the background.

**Comment by aaustin** [comment]
Ah - got it. Can you try this:
```
if (conversation && conversation.selectedMessage) {
    NSUserActivity *userActivity = [[NSUserActivity alloc] initWithActivityType:NSUserActivityTypeBrowsingWeb];
    userActivity.webpageURL = conversation.selectedMessage.URL;
    [[Branch getInstance] continueUserActivity:userActivity];
}
[[Branch getInstance] initSessionWit ....
```

**Comment by SebC99** [comment]
Already tried ;)
But when executing:
```objective-c
- (BOOL)continueUserActivity:(NSUserActivity *)userActivity {
    //check to see if a browser activity needs to be handled
    if ([userActivity.activityType isEqualToString:NSUserActivityTypeBrowsingWeb]) {
        self.preferenceHelper.universalLinkUrl = [userActivity.webpageURL absoluteString];
        self.preferenceHelper.shouldWaitForInit = NO;
        [self initUserSessionAndCallCallback:YES];

...
}
```
The call to `[self initUserSessionAndCallCallback:YES]` goes to `self.sessionInitWithParamsCallback([self getLatestReferringParams], nil);` and then the deeplink handler is called with the last referring params (which are empty) and not with the useractivity link.

**Comment by aaustin** [comment]
Hmm - that shouldn't be happening at all. I see the issue! Our session isn't closing out from the last time you ran it. Can you try adding: `[[Branch getInstance] resetUserSession];` to `willResignActiveWithConversation`? This will close the session and allow you to trigger a new link.

**Comment by SebC99** [comment]
Almost there...
Except something weird is happening with iMessage Extension: 

- When you use the extension to send a message, it builds the iMessage layout and put it the message placeholder, and then resign active. 
- But when you then click on 'send', it reload the extension for a few seconds, launching the `didBecomeActive` and just after the `willResignActive` ... 

There's a concurrency issue, as the `[[Branch getInstance] resetUserSession];` is called before the `handleInitSuccess` callback of the `initializeSession` method (called by `continueUserActivity`)! 

So the session is not correctly closed, and at next start, the `continueUserActivity` will not initialize the session, and will not open the link...

**Comment by aaustin** [comment]
Oh gees. What a mess! The worst part of it all is that I bet this will all change in a minor version or two...

One last thought: Is there any aspect of the MSConversation object that indicates you can ignore the call to Branch init/reset during that `send` mini-session? Like some sort of state or type variable?

If not, we're going to have to make some library changes to support this type of session management. I can see there will be a lot of edge cases to manage.

**Comment by SebC99** [comment]
Nothing available...

**Comment by SebC99** [comment]
Ok, so I've added a `state` property to my `MessageViewController`, which is set to `active` in `willBecomeActiveWithConversation` and to `inactive` in `willResignActiveWithConversation`, and then I force a `resetUserSession` in the deepLinkHandler if the state has been changed to inactive:
```objective-c
[[Branch getInstance] initSessionWithLaunchOptions:@{} andRegisterDeepLinkHandler:^(NSDictionary * _Nonnull params, NSError * _Nullable error) {
  if (self.state == MessageViewControllerStateInactive) {
    [[Branch getInstance] resetUserSession];
    return;
  }
  if (!error) {
    NSLog(@"found params %@", [params description]);
  }
}];
```

and it seems to work!! :)

**Comment by aaustin** [comment]
Oof - that's not pretty. Thanks for all the help. Deep linking in iMessage extensions is a pretty small use case for us, so I'll make this an upcoming weekend project for me.

**Comment by E-B-Smith** [comment]
There's not a lot of interest in this so I'm closing it out.

If there is interest I'm happy to re-open it.
