### ISSUE TITLE
Value of type 'Branch' has no member 'initSession' aka outdated readme

### ISSUE THREAD

**Issue by tirrorex** [BranchMetrics/ios-branch-deep-linking#481]
Hi guys, currently implementing branch in my app (last release of swift before swift 3).
I tried to follow your integration guide but it fails during the init.
This line in particular
"branch.initSession(launchOptions: launchOptions, deepLinkHandler: { params, error in"

Browsing with autocompleted i can find some methods but none that seems to be the same.
What is your advice here?
Thanks

**Comment by snakingfire** [comment]
Hi tirrorex! Our documentation currently uses Swift 3 syntax for code snippets. The correct initSession syntax for Swift 2.x is:

branch.initSessionWithLaunchOptions(launchOptions, automaticallyDisplayDeepLinkController: true, deepLinkHandler: { params, error in
            if error == nil {
                print("params: %@", params.description)
            }
        
        })

If you need more reference, I would recommend you look at our legacy Swift test-bed here:
https://github.com/BranchMetrics/ios-branch-deep-linking/tree/146b9b9e37baf59e16e948403ceccd8bd53a1785

**Comment by tirrorex** [comment]
Thanks for the link mate
