### ISSUE TITLE
Order of calling functions on Branch instance

### ISSUE THREAD

**Issue by stefanprutianu** [BranchMetrics/ios-branch-deep-linking#483]
Hello,

This is rather a question than an issue.

I've observed that there seems to matter the order in which methods are called on the Branch instance.

For example if -[Branch continueUserActivity:] gets somehow called before 
- [Branch initSessionWithLaunchOptions: andRegisterDeepLinkHandler:],
the completion handler on the later will never be called.

I know that the integration guide states that - [Branch initSessionWithLaunchOptions: andRegisterDeepLinkHandler:] should be called in -[UIApplicationDelegate application: didFinishLaunchingWithOptions:] which will guarantee it being called before  -[Branch continueUserActivity:] but I did not found it explicitly stated that this should be the order.

Please let me know if this is the expected behaviour or an issue?

Thanks,
Stefan

**Comment by aaustin** [comment]
Hey @stefanprutianu - Thanks for the question. 

It does matter very much. It's important that Branch gets initialized with the correct referring link information (potentially coming from continueUserActivity or openUrl) and we do quite a bit of fancy footwork to ensure that's the case. All of our fancy footwork is designed around the assumption that our `initSession`, `continueUserActivity` and `handleDeepLink` are called in their respective App Delegate life cycle calls when those calls are made. If not, it's untested territory.

Hope this helps!
