### ISSUE TITLE
branch.initSessionWithLaunchOptions causes UITextField to removeFirstResponder on clean install

### ISSUE THREAD

**Issue by eeallen1** [BranchMetrics/ios-branch-deep-linking#484]
This issue only happens on the first install of my app - never after. 

In my initial view controller, my `viewDidLoad()` looks like this:

`override func viewDidLoad(){`
    `super.viewDidLoad()`
    `self.textField.becomeFirstResponder()`
`}`

The problem is that on a clean install of the app, the keyboard shows up, then goes back down, and then ~1 second later, it comes back up. Since this is the first screen users see in my app, I don't want to have an initial bad experience. 

I've tried rearranging where the textField becomes first responder, but the only way I've been able to fix the problem is to comment out `branch.initSessionWithLaunchOptions`. 

This may to be related to the issue addressed in v0.12.10 : "Fix for issue causing initsession hang on cold start from universal link", but I'm using v0.12.11, so it must be something different. 

I'd love some clarity on why this is happening and what I can do to fix it.

**Comment by eeallen1** [comment]
I've been able to fix the problem by keeping a copy of`launchOptions` from `applicationDidFinishLaunchingWithOptions` AppDelegate and calling `initSessionWithLaunchOptions` later. If I'm not doing any link handling before this, is there any potential downside to not initializing branch on app launch?

**Comment by E-B-Smith** [comment]
I understand.  The first app impression is pretty important.  I'm glad you were able to find a work around.

The only downside to not initializing Branch at startup is that app links that are used to launch you app may not be handled.

Are you using the useCookieBasedMatching? That may cause the keyboard to momentarily lose focus.

**Comment by eeallen1** [comment]
@E-B-Smith 

I'm not explicitly using useCookieBasedMatching, but I also haven't disabled it, so if it's a default setting then that could be it. 

I'll test it soon, but I've been able to get all of my app launches via links working by initializing branch on launch unless it's the app's first launch, so it isn't a big issue for me now, but it was very frustrating trying to figure out why it was happening.

**Comment by E-B-Smith** [comment]
Yes, I'm sure it was frustrating!  Sorry about that.  I'm going to investigate this to prevent problems in the future.  Thanks for the heads up.

The useCookieBasedMatching defaults to 'on', so you were using that.

**Comment by aaustin** [comment]
Hey @eeallen1 Quick clarification: the method name is actually `disableCookieBasedMatching`. This will prevent our SafariViewController code from executing. However, this would only execute if you've got SafariServices.framework included. Did you give this a try?

We'd like to help you solve this issue!

**Comment by E-B-Smith** [comment]
Fixed in SDK release 0.12.18.
