### ISSUE TITLE
accountForFacebookSDKPreventingAppLaunch documentation is partial

### ISSUE THREAD

**Issue by lordzsolt** [BranchMetrics/ios-branch-deep-linking#487]
The documentation for `accountForFacebookSDKPreventingAppLaunch` says `application:didFinishLaunchingWithOptions:` has to always return `YES`, but it doesn't mention that `application:willFinishLaunchingWithOptions:` **also** has to return `YES`.

PS: I've spent half a day pulling my hair out before I noticed another developer on the project was returning NO from that method, for unknown reasons.

**Comment by E-B-Smith** [comment]
We don't know why that other developer was returning ```NO``` from the ```application:willFinishLaunchingWithOptions:```  method either.

However we will update the documentation to make it clear that the ```application:willFinishLaunchingWithOptions:``` also needs to return ```YES``` for URL links to work.

Thank you for the suggestion.
