### ISSUE TITLE
DeepLink handler callback is not always called

### ISSUE THREAD

**Issue by stefanprutianu** [BranchMetrics/ios-branch-deep-linking#491]
Hi,

While we were verifying the integration with your service via the iOS Branch SDK (0.12.12) we've stumbled upon a situation where the deeplink handler we register via -[Branch initSessionWithLaunchOptions: andRegisterDeepLinkHandler:] does not get called when the app is opened via a Branch link.

The scenario is like this:
1) App becomes active
2) Branch SKD launches a call to the servers
3) App resigns active state
4) Branch session timer fires but the handler -[Branch callClose] does nothing because session is not yet initialized
5) Branch response received, session is initialized
6) App resumed via URL, -[Branch handleDeepLink:] is called, -[Branch initUserSessionAndCallCallback:] is called with callCallback set to NO (!isInitialized) and it ends there.

It seems that the truth value for isInitialized (YES from step 5) will prevent the callback to be called either via -[Branch  initUserSessionAndCallCallback:] or via -[Branch applicationDidBecomeActive].

Please note that the scenario above is not that easy to reproduce (probably 20%-25% of attempts) but is still represents a problem for us.

I'm attaching the app logs where you can observe the app state transitions and logs from within the Branch SDK (both your debug logs and also some I've added).

branch-log-issue represents the portion of the logs that showcases the scenario above.
branch-log-app_session represents the full app session logs

Looking forward to your response.

Thanks,
Stefan
[logs.zip](https://github.com/BranchMetrics/ios-branch-deep-linking/files/544340/logs.zip)

**Comment by E-B-Smith** [comment]
Thanks for the detailed explanation.   Let me dig into this and see what's up.

**Comment by stefanprutianu** [comment]
Hi! Any news on this topic? Thanks!

**Comment by E-B-Smith** [comment]
Thanks again for your great write up.  I have a fix for this that we are testing and it should be in the codebase this week.

I'll send you a ping when I merge the fix.

**Comment by stefanprutianu** [comment]
Hi again,

Have you managed to test the fix? Should we expect a new release soon? I'm asking because we too are planning to make a release and considering the relatively low visibility of this issue we can do it without this fix if it is going to take longer to validate the solution from your side.

Thanks,
Stefan

**Comment by E-B-Smith** [comment]
@stefanprutianu  I've made and tested a fix for this and I'm going to merge this into the staging branch today.  I'll ping you when it's done.

You can pull from that branch if you want the fix today, otherwise we'll make an official release Monday and you can wait for that.

The reason we are moving slower than usual is that we are trying to put in place a whole Enhance-Fix-Test-QA-Release pipeline so that we assure quality releases.  It's a new process and we're still adapting.  Thanks for your patience.

**Comment by aaustin** [comment]
Hey @stefanprutianu Sorry about the delay here. We've been going slowly through the fix to ensure it covers all edge cases. This affects a pretty complex part of the SDK codebase and we want to make sure we get it right. This is the PR with resolution https://github.com/BranchMetrics/ios-branch-deep-linking/pull/506 if you want to give it a whirl on your local env.

In the meantime, you should release as there's no timeline.

**Comment by E-B-Smith** [comment]
Fixed in SDK release 0.12.18.
