### ISSUE TITLE
0.12.13 cannot be built with iOS 9.3 SDK

### ISSUE THREAD

**Issue by mikemonaco** [BranchMetrics/ios-branch-deep-linking#493]
0.12.13 has a compiler error in Xcode 7.3.1 (iOS 9.3 SDK) because the code is trying to access new iOS 10+ properties of NSLocale (countryCode & languageCode)

BNCDeviceInfo.m:77:49: Property 'countryCode' not found on object of type 'NSLocale *'
BNCDeviceInfo.m:78:50: Property 'languageCode' not found on object of type 'NSLocale *'

possible solution would be to use respondsToSelector/performSelector.

**Comment by icarasiaofficial** [comment]
+1 to that.

**Comment by aaustin** [comment]
Hey team - Thanks so much for letting us know right away. We're working on a patch now and will do an out of band deploy shortly. Will keep you updated.

**Comment by aaustin** [comment]
Ah I saw we handle the runtime case already in the code https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCDeviceInfo.m#L68. We're going to hold off on the deploy until tomorrow morning. Sorry for the delay.. Any reason you guys are still running Xcode 7?

**Comment by StewartGillen** [comment]
@aaustin [This code](https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCDeviceInfo.m#L77-L78) is [iOS 10 API and above](https://developer.apple.com/reference/foundation/nslocale/1643060-countrycode). 

It causes these build errors:

> /Users/builder/Jenkins/workspace/HomeAwayOwner-iOS-Production-Monolithic/Pods/Branch/Branch-SDK/Branch-SDK/BNCDeviceInfo.m:77:49: error: property 'countryCode' not found on object of type 'NSLocale *'
        self.country = [NSLocale currentLocale].countryCode;
                                                ^
/Users/builder/Jenkins/workspace/HomeAwayOwner-iOS-Production-Monolithic/Pods/Branch/Branch-SDK/Branch-SDK/BNCDeviceInfo.m:78:50: error: property 'languageCode' not found on object of type 'NSLocale *'
        self.language = [NSLocale currentLocale].languageCode;
                                                 ^
2 errors generated.

**Comment by E-B-Smith** [comment]
I added a new branch called 'Xcode-7-Support' that fixes this issue.

You can compile with that branch now to get going.  I expect to merge the branch into master shortly after some testing.

**Comment by E-B-Smith** [comment]
This is fixed in the new release,  v0.12.14, which is now on master.
