### ISSUE TITLE
App Crash when registerDeepLinkController as visible ViewController.

### ISSUE THREAD

**Issue by LadyRanger1992** [BranchMetrics/ios-branch-deep-linking#504]
Branch.m/line 1399
build newest release.

I try to handle my VC as first VC. and can not present the VC if it already visible.

Try to check it visible or not.

**Comment by E-B-Smith** [comment]
If you want to conditionally handle app deep linking (like for instance, don't do anything if the view controller is already visible), make sure `automaticallyDisplayDeepLinkController = NO` and handle the deep linking yourself in the deepLinkHandler block.

So initialize Branch like this:

```objc
[[Branch getInstance] initSessionWithLaunchOptions:launchOptions 
    automaticallyDisplayDeepLinkController:NO 
    deepLinkHandler:^(NSDictionary *params, NSError *error) {

    //  Your logic goes here.  Something like:

    if (! myViewController.isVisible) {
        UIViewController *presentingVC = 
            [[[UIApplication sharedApplication] keyWindow] rootViewController];
        [presentingVC presentViewController:myViewController 
            animated:YES 
            completion:NULL];
    }
}];
```

Does this help?

**Comment by LadyRanger1992** [comment]
Yeah, thank for your support @E-B-Smith . This really helpful.
