### ISSUE TITLE
crash in BNCPreferenceHelper

### ISSUE THREAD

**Issue by charliebartel** [BranchMetrics/ios-branch-deep-linking#514]
Branch version in podfile.lock is 0.12.16
BNCPreferenceHelper.m line 642
365 crashes in the last 7 days.
Occurring for iOS 9 and 10 devices, iPads and iPhones

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1940ee1c0 __exceptionPreprocess
1  libobjc.A.dylib                0x192b2855c objc_exception_throw
2  CoreFoundation                 0x1940ee108 -[NSException initWithCoder:]
3  Foundation                     0x194b389e0 -[NSData(NSData) writeToURL:options:error:]
4  Branch                         0x100a0d40c __41-[BNCPreferenceHelper persistPrefsToDisk]_block_invoke (BNCPreferenceHelper.m:642)
5  Foundation                     0x194bb2754 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
6  Foundation                     0x194af72c8 -[NSBlockOperation main]
7  Foundation                     0x194ae78c4 -[__NSOperationInternal _start:]
8  Foundation                     0x194bb4b00 __NSOQSchedule_f
9  libdispatch.dylib              0x192f791c0 _dispatch_client_callout
10 libdispatch.dylib              0x192f87444 _dispatch_queue_serial_drain
11 libdispatch.dylib              0x192f7c9a8 _dispatch_queue_invoke
12 libdispatch.dylib              0x192f8938c _dispatch_root_queue_drain
13 libdispatch.dylib              0x192f890ec _dispatch_worker_thread3
14 libsystem_pthread.dylib        0x1931822b8 _pthread_wqthread
15 libsystem_pthread.dylib        0x193181da4 start_wqthread

**Comment by E-B-Smith** [comment]
Sorry about your crashes - The latest version of the SDK,  0.12.17,  fixes this.
