### ISSUE TITLE
Crash in 0.12.18

### ISSUE THREAD

**Issue by jweihs** [BranchMetrics/ios-branch-deep-linking#515]
Starting with v. 0.12.18 my app crashes after initializing the Branch Instance in `didFinishLaunchingWithOptions` (using `- (void)initSessionWithLaunchOptions:(NSDictionary *)options andRegisterDeepLinkHandler:(callbackWithParams)callback`)
Until then i'm using the 0.12.16.

Tested on the simulator only.

Jonathan

Detailed log:

> *** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<BNCMatchViewController_Safari: 0x7fce3401f690> should have parent view controller:(null) but actual parent is:<SFMainContainerViewController: 0x7fce34007110>'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x000000011176f34b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x0000000110cb921e objc_exception_throw + 48
> 	2   CoreFoundation                      0x00000001117d8265 +[NSException raise:format:] + 197
> 	3   UIKit                               0x000000010e217bf5 -[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:] + 289
> 	4   UIKit                               0x000000010e217fe0 -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] + 252
> 	5   UIKit                               0x000000010e228cf0 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 451
> 	6   Branch                              0x000000010cd9ac86 -[BNCStrongMatchHelper willLoadViewControllerWithURL:] + 931
> 	7   Branch                              0x000000010cd9a749 __55-[BNCStrongMatchHelper createStrongMatchWithBranchKey:]_block_invoke + 35
> 	8   libdispatch.dylib                   0x0000000112f38980 _dispatch_call_block_and_release + 12
> 	9   libdispatch.dylib                   0x0000000112f620cd _dispatch_client_callout + 8
> 	10  libdispatch.dylib                   0x0000000112f428d6 _dispatch_main_queue_callback_4CF + 406
> 	11  CoreFoundation                      0x00000001117334f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
> 	12  CoreFoundation                      0x00000001116f8f8d __CFRunLoopRun + 2205
> 	13  CoreFoundation                      0x00000001116f8494 CFRunLoopRunSpecific + 420
> 	14  GraphicsServices                    0x00000001142a9a6f GSEventRunModal + 161
> 	15  UIKit                               0x000000010e168964 UIApplicationMain + 159
> 	16  GameFeed                            0x000000010b0bc7af main + 111
> 	17  libdyld.dylib                       0x0000000112fae68d start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by E-B-Smith** [comment]
Thanks for reporting this!

I've tested in the simulator on iOS 9 and 10 with the Branch-TestBed and app and a couple other test apps and didn't see any problems.  

I wonder if it is the order that things are initialized in your AppDelegate?  I initialize Branch first, then do some app initialization.  Also, are you using storyboards?

In the mean time, use version 0.12.17 if you're going to release production code.  It fixes a known crash bug.

**Comment by E-B-Smith** [comment]
Also, What simulator version / Xcode / iOS version crashed for you? I'd love to be able to reproduce this.

**Comment by E-B-Smith** [comment]
This was fixed by regression in 0.12.19.  Momentarily having a  key window appear is still an issue.  I should be able to fix that this week.
