### ISSUE TITLE
BNCDeviceInfo Significantly Impacting App Launch Time by Getting User Agent

### ISSUE THREAD

**Issue by brynbodayle** [BranchMetrics/ios-branch-deep-linking#520]
On app launch, BNCDeviceInfo gets the user's user agent by using a UIWebView here https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCDeviceInfo.m#L87

This is problematic because using a UIWebView like this takes a significant amount of time in the context of app launch times. Apple recommends 400ms as a good target for total app launch time here:
http://devstreaming.apple.com/videos/wwdc/2016/406i3zbazbegkeh0udt/406/406_optimizing_app_startup_time.pdf

Here is a time profiler stack trace on an iPad Air 2 with iOS 10.0.2
![screen shot 2016-12-13 at 1 10 13 pm](https://cloud.githubusercontent.com/assets/1455522/21193893/c1c3352c-c1e2-11e6-9882-054cd30ca736.png)

As you can see getting the user agent takes 133ms and that's on a pretty fast device (iPad Air 2).

I think it's not ideal that this one call is taking over 1/4 of the recommend app launch time. Could this be deferred until after applicationDidFinishLaunching or could there be a more optimal way of getting the user agent?

Thanks for a great library and let me know if I can help in any way.

**Comment by E-B-Smith** [comment]
Thanks for your feedback.  Let me look at some ways to make have less of an impact.

**Comment by E-B-Smith** [comment]
I am testing a fix for this.  I expect this to be included in the 0.12.21 release.

**Comment by E-B-Smith** [comment]
This issue has been fixed in SDK version 0.12.21.

This version has been QA tested and is available as a beta release.

Information about the Branch beta program can be found [here, on Github.](https://branch.app.link/Beta-Info)

**Comment by brynbodayle** [comment]
Looks great! Thanks for doing this.
