### ISSUE TITLE
0.12.20 - Build error when using in app extension (iMessage)

### ISSUE THREAD

**Issue by hudsonnj** [BranchMetrics/ios-branch-deep-linking#521]
Updated to 0.12.20 and I'm now getting build error(s) when using Branch in an iMessage app extension.

The error is related to referencing [UIApplication sharedApplication] in the BNCStrongMatchHelper.m class.

BNCStrongMatchHelper.m, line 277:
self.primaryWindow = [[UIApplication sharedApplication] keyWindow];

Error:
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

Note that if I revert to 0.12.19, the error goes away, so I will be using that version in the meantime.

**Comment by E-B-Smith** [comment]
Sorry about that - I'll have a fix for this in our next build.

**Comment by hudsonnj** [comment]
No worries, thanks for getting back to me!

**Comment by E-B-Smith** [comment]
Fixed in version 0.12.21.

**Comment by E-B-Smith** [comment]
This issue has been fixed in SDK version 0.12.21.

This version has been QA tested and is available as a beta release.

Information about the Branch beta program can be found [here, on Github.](https://branch.app.link/Beta-Info)
