### ISSUE TITLE
Please rename SDK_VERSION const in BNCConfig

### ISSUE THREAD

**Issue by ancloid** [BranchMetrics/ios-branch-deep-linking#523]
It conflicts with other Frameworks (for example with HeyzapAds)
I guess BNC_SDK_VERSION it is more appropriate name for this const

**Comment by E-B-Smith** [comment]
Good catch!  I'll update this in the next release.

**Comment by E-B-Smith** [comment]
Fixed in version 0.12.21.

**Comment by E-B-Smith** [comment]
This issue has been fixed in SDK version 0.12.21.

This version has been QA tested and is available as a beta release.

Information about the Branch beta program can be found [here, on Github.](https://branch.app.link/Beta-Info)
