### ISSUE TITLE
0.12.20: -[BNCMatchViewController_Safari viewControllers]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by jlagomar** [BranchMetrics/ios-branch-deep-linking#527]
When I delete the app on my device then install it from Xcode getting this crash:
`-[BNCMatchViewController_Safari viewControllers]: unrecognized selector sent to instance`

After the first launch/crash everything seems to work okay on subsequent launches. Went to `0.12.19` and the error doesn't seem to occur.

**Comment by E-B-Smith** [comment]
Thank you for reporting this. Can you crash call stack too?

**Comment by jlagomar** [comment]
Apologies, looks like the call is from our code.  Have some code where this controller slipped in that looks something like this:

```objc
    UITabBarController *tabbarController = (UITabBarController *)self.window.rootViewController;
    for (UINavigationController *navController in tabbarController.viewControllers) {
        for (UIViewController *viewControllers in navController.viewControllers) { // crash
```

Not sure exactly what's going on but it looks like we can fix it on our end.

**Comment by E-B-Smith** [comment]
Ah!

Let me know how you fix it.
Thanks!
