### ISSUE TITLE
Recently I integrated to my project, but while run time, i am getting BAD EXCESS error in swift

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [BranchMetrics/ios-branch-deep-linking#533]
I am using swift latest version, but, my app getting issue as BAD EXCESS in the following line.

        let branch: Branch = Branch.getInstance()
its happening didfinishapplaunching delegate method.
How to fix this?

**Comment by E-B-Smith** [comment]
Did you set your Branch key or have your Branch key in your Info.plist?

You can see a Swift example here, in our TestBed-Swift app:  [TestBed-Swift on Github](https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift#L15)
