### ISSUE TITLE
initSession this method never going inside in app delegate, didfinishlaunchwithoptions

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [BranchMetrics/ios-branch-deep-linking#534]
let branch: Branch = Branch.getInstance()
branch?.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: {params, error in
    if error == nil {
        // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
        // params will be empty if no data found
        // ... insert custom logic here ...
        print("params: %@", params.description)
    }
})

===

I am calling above method in didfinishlaunchingwithoptions, in app delegate class, but initSession, never going inside.
How to fix this issue?

**Comment by E-B-Smith** [comment]
Are you setting up your deep link correctly?   Also, try setting `automaticallyDisplayDeepLinkController` to false and see what happens.

Here's an example in Swift: [TestBed-Swift](https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift#L15)
