### ISSUE TITLE
Carthage Framework does not build (0.12.22)

### ISSUE THREAD

**Issue by n8tr** [BranchMetrics/ios-branch-deep-linking#540]
Repro:
- update to version iOS SDK 0.12.22 via carthage
- try to build app
- Branch.h fails to build with #import "BNCCommerceEvent.h" not found

<img width="600" alt="screen shot 2017-01-05 at 10 51 33 pm" src="https://cloud.githubusercontent.com/assets/1009324/21707018/8aa7288c-d399-11e6-923e-457008216629.png">

<img width="400" alt="screen shot 2017-01-05 at 10 52 19 pm" src="https://cloud.githubusercontent.com/assets/1009324/21707033/a8f207da-d399-11e6-9a7e-2b8632c8077d.png">

**Comment by andris-zalitis** [comment]
I have the same issue. Currently resolved just by pointing `Cartfile` to the previous release:
`github "BranchMetrics/ios-branch-deep-linking" "0.12.20"`

**Comment by E-B-Smith** [comment]
I made that header public in the new release, version 0.12.23.
