### ISSUE TITLE
"'BNCCommerceEvent.h' file not found" when installing via Fabric

### ISSUE THREAD

**Issue by rablador** [BranchMetrics/ios-branch-deep-linking#542]
I get an error saying "'BNCCommerceEvent.h' file not found" in Branch_SDK.h when trying to install via Fabric.

Latest version of Branch.
Latest version of Fabric.
Latest version of Xcode.
Latest version of Swift.

**Comment by E-B-Smith** [comment]
Thanks for the heads up!   The new release, version 0.12.24, fixes this.
