### ISSUE TITLE
Is there a way to force shortURL to use https?

### ISSUE THREAD

**Issue by SebC99** [BranchMetrics/ios-branch-deep-linking#546]
Hello,
We use https everywhere but the Branch generated links (short or long) are always using http. We could replace the string to force https, but is there a better way to force Branch to generate https links?
Thanks!
S.

**Comment by E-B-Smith** [comment]
There's got to be a better way, right?

I think that https should be the default, or at least an option.  I'm talking with the backend team about the ramifications about changing this.  There could be some weird edge cases that I don't know about before changing this.

**Comment by SebC99** [comment]
any news about this?

**Comment by ahmednawar** [comment]
@SebC99 We've been working on this transition for a while but it's a big change so it's taking a while. Note that we already generate links on https if they are branch domains (bnc.lt and app.link). We only generate http links on custom domains and then redirect to https version on a branch domain. Hopefully we will roll this out soon. Hang tight, more to come!

**Comment by ahmednawar** [comment]
This is actually not an SDK issue but more of a backend one. We will add it to our product update email once it's live. Closing here.
