### ISSUE TITLE
Crash at BNCServerInterface.m line 246 -[BNCServerInterface prepareParamDict:key:retryNumber

### ISSUE THREAD

**Issue by itchingpixels** [BranchMetrics/ios-branch-deep-linking#551]
http://crashes.to/s/19c9d4afe0c
<img width="1280" alt="branch_crash_1" src="https://cloud.githubusercontent.com/assets/5416288/21991220/92cd35d8-dc09-11e6-9067-01825dcdcd4d.png">

**Comment by itchingpixels** [comment]
Latest SDK version. Was getting a crash also when launching the simulator. Can be also reproduced in production, see link above the screenshot.

**Comment by E-B-Smith** [comment]
See comment for [issue #548](https://github.com/BranchMetrics/ios-branch-deep-linking/issues/548#issuecomment-274059520) .

**Comment by mohitongit** [comment]
Received this same crash on v0.12.25 beta on iPhone 7 simulator:
`[metadata addEntriesFromDictionary:self.preferenceHelper.requestMetadataDictionary];`
