### ISSUE TITLE
Crash at BNCServerInterface.m line 296 -[BNCServerInterface updateDeviceInfoToMutableDiction...

### ISSUE THREAD

**Issue by itchingpixels** [BranchMetrics/ios-branch-deep-linking#552]
http://crashes.to/s/2d57bf7dab3

<img width="1280" alt="branch_crash_2" src="https://cloud.githubusercontent.com/assets/5416288/21991299/e654cc52-dc09-11e6-83cb-6ed86c0b5a28.png">

Latest SDK version (v0.12.24). Was getting a crash also when launching the simulator. Can be also reproduced in production, see link above the screenshot.

**Comment by E-B-Smith** [comment]
See comment for [issue #548](https://github.com/BranchMetrics/ios-branch-deep-linking/issues/548#issuecomment-274059520) .

**Comment by mohitongit** [comment]
Hi, I updated to 0.12.27 (from 0.12.25 beta) and am experiencing 
`[BNCServerInterface updateDeviceInfoToMutableDictionary:] at /Pods/Branch/Branch-SDK/Branch-SDK/BNCServerInterface.m:318`
crash on both simulator and real device randomly on launch.

**Comment by E-B-Smith** [comment]
@mohitongit 
What are your linker settings? Do you include 

```
OTHER_LDFLAGS = -ObjC
```

**Comment by mohitongit** [comment]
Yes, I do. It looks like this:
`$(inherited) -ObjC -l"GoogleAnalytics" -l"c++" -l"icucore" -l"sqlite3" -l"stdc++" -l"xml2" -l"z" -framework "AVFoundation" -framework "AddressBook" -framework "AssetsLibrary" -framework "AudioToolbox" -framework "Bolts" -framework "Branch" -framework "CFNetwork" -framework "CoreData" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreImage" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreText" -framework "CoreVideo" -framework "Crashlytics" -framework "FBAudienceNetwork" -framework "FBSDKCoreKit" -framework "FBSDKShareKit" -framework "Fabric" -framework "FirebaseAnalytics" -framework "FirebaseAuth" -framework "FirebaseCore" -framework "FirebaseCrash" -framework "FirebaseDatabase" -framework "FirebaseInstanceID" -framework "FirebaseMessaging" -framework "FirebaseRemoteConfig" -framework "Foundation" -framework "GGLAnalytics" -framework "GGLCore" -framework "GLKit" -framework "GTMOAuth2" -framework "GTMSessionFetcher" -framework "GoogleAppUtilities" -framework "GoogleInterchangeUtilities" -framework "GoogleMobileAds" -framework "GoogleSignIn" -framework "GoogleSymbolUtilities" -framework "GoogleToolboxForMac" -framework "MediaPlayer" -framework "MessageUI" -framework "MobileCoreServices" -framework "OneSignal" -framework "OpenGLES" -framework "SDWebImage" -framework "SafariServices" -framework "Security" -framework "StoreKit" -framework "SwiftyJSON" -framework "SystemConfiguration" -framework "UIKit" -framework "libwebp" -weak_framework "AdSupport" -weak_framework "CoreMotion" -weak_framework "JavaScriptCore" -weak_framework "SafariServices" -weak_framework "WebKit"`

**Comment by mohitongit** [comment]
Just now experienced the same crash even on 0.12.25 beta on iPhone 7 simulator:
`dict[BRANCH_REQUEST_KEY_HARDWARE_ID_TYPE] = deviceInfo.hardwareIdType;`

**Comment by mohitongit** [comment]
This time, (0.12.25, iPhone 7 simulator) crash on this line:
`[self safeSetValue:deviceInfo.vendorId forKey:BRANCH_REQUEST_KEY_IOS_VENDOR_ID onDict:dict];`

**Comment by E-B-Smith** [comment]
Thanks for the heads up.  I'm looking into this now.

**Comment by E-B-Smith** [comment]
The latest version of beta is 0.12.29.

Do a `pod update` to get the latest version.

**Comment by mohitongit** [comment]
Ok, but this was fixed in 0.12.25 beta - isn't it? Is it fixed now in 0.12.29?

**Comment by E-B-Smith** [comment]
Yes.
