### ISSUE TITLE
params doesn't contain url when is_first_session = 1

### ISSUE THREAD

**Issue by eliasbagley** [BranchMetrics/ios-branch-deep-linking#553]
I have a case where if the app is installed for the very first time, and then a branch link is clicked, the Branch SDK params has "is_first_session" = "1", and doesn't include any information about the url that was clicked. If I click the link again, "is_first_session" = "0", and then the url information is present in the params. Is there a reason why the url isn't being included with the params for the first session?

I'm using the iOS SDK version 0.12.24

**Comment by ahmednawar** [comment]
@eliasbagley could you please share how you are testing? Are you testing on a Wi-Fi network with lots of other people clicking at the same time?

Can you also send your branch_key to integrations@branch.io?

**Comment by E-B-Smith** [comment]
@eliasbagley  Do you have anymore insight into your problem?  

When I click a Branch link for a first-time install, I get "is_first_session" = "1" and the URL information  in the session params.  Maybe there is something special in your set up?
