### ISSUE TITLE
Created Test App but Domain Link Is not working

### ISSUE THREAD

**Issue by Miteshimmply** [BranchMetrics/ios-branch-deep-linking#563]
I have created Test Application after Registration @ Website. I created Test application with Live And i also Use Branch-Key and put in Plist File with LinkDomain, I also add URI Schema but when i try to open app via Branch Domain Link named "tryone.app.link" it convert to http://tryone.app.link , it says File not found.

Setting in Plist File :
<key>branch_app_domain</key>
	<string>tryone.app.link</string>
	<key>branch_key</key>
	<dict>
		<key>live</key>
		<string>key_live_flAb3U7ukPd2CkVR8KEwaocltzl6rSv0</string>
	</dict>
<key>CFBundleURLName</key>
			<string>com.test.customer</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>DeepLinkingTest</string>
			</array>

In App Delegate file :
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // Override point for customization after application launch.
    
    Branch *branch = [Branch getInstance];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        if (!error && params) {
            // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
            // params will be empty if no data found
            // ... insert custom logic here ...
            NSLog(@"params: %@", params.description);
        }
    }];
    
    return YES;
}
// Respond to URI scheme links
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    // pass the url to the handle deep link call
    [[Branch getInstance] handleDeepLink:url];
    
    // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    return YES;
}

// Respond to Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    BOOL handledByBranch = [[Branch getInstance] continueUserActivity:userActivity];
    
    return handledByBranch;
}
So can you help me to integrate so i am looking forward to your SDK

**Comment by E-B-Smith** [comment]
So you get a '404 - File Not Found' when you click the link?

Did you set your entitlements file up?  Make sure you've set up your associated domains:

```
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:tryone.app.link</string>
	</array>
```

**Comment by Miteshimmply** [comment]
But i am not using enable universal link.

**Comment by E-B-Smith** [comment]
This is an app integration issue.  I can see that you're working with our app integration team on this. I'll leave you in their very capable hands.
