### ISSUE TITLE
BNCEncodingUtils.m line 199

### ISSUE THREAD

**Issue by sheshans** [BranchMetrics/ios-branch-deep-linking#564]
We are getting lot of crashes from branch sdk mostly on iPhone 7 plus devices.

http://crashes.to/s/ca911aacdcd

**Comment by E-B-Smith** [comment]
Thanks for the heads up. I'll look into this ASAP.

**Comment by E-B-Smith** [comment]
Do you have any more insight into this crash?

I can't reproduce this with an iPhone 6 Plus on 10.2.1 or an iPhone 7 Plus Simulator using 10.2.
I'm calling -[Branch userCompletedAction:withState:] and this looks good, even when stress testing.

**Comment by sheshans** [comment]
Currently we are also trying to figure this out. But, we have not been able to reproduce the bug. 50 - 60% of crashes in our App are caused by this issue.

**Comment by E-B-Smith** [comment]
Are you able to test on an actual iPhone 7 Plus on 10.2.0?   It looks like most of the crashes are from that.  It would be weird if it were that OS / model specific, but it's possible.

**Comment by E-B-Smith** [comment]
I tested a bunch with an actual iPhone 7 Plus on 10.2.0 and got no insight into this.

**Comment by sheshans** [comment]
We do not have access to iPhone7 Plus. We tried testing on different simulators but, we are not able to reproduce this issue. But our users are still facing this issue. Any help in debugging this issue will be of great help. Just for your info our code base is swift2.3

**Comment by E-B-Smith** [comment]
I can't reproduce this either, even on an iPhone 7 Plus.  But I'm looking into it.  It's frustrating.

Do you compile the Branch SDK or use Carthage?  Are you using Xcode 7 or Xcode 8?

**Comment by sheshans** [comment]
We use Cocoa pods to add Branch SDK to our project and use Xcode7.3

**Comment by E-B-Smith** [comment]
Let me test with Xcode 7.3...

**Comment by E-B-Smith** [comment]
@sheshans Xcode 7.3 or 7.3.1?

**Comment by sheshans** [comment]
Sorry, my bad its 7.3.1

**Comment by E-B-Smith** [comment]
Okay. I'm testing on 7.3.1.

**Comment by E-B-Smith** [comment]
I have been testing on an iPhone 7 Plus and can't see any crashes.

I suggest pulling the latest version of the SDK and seeing if that helps.

Also, see if you can use Xcode 8 to compile your code.  It could easily be a compiler problem in that older version.
