### ISSUE TITLE
Adding Branch as a depedency on another Cocoapod, static library error

### ISSUE THREAD

**Issue by tspent** [BranchMetrics/ios-branch-deep-linking#583]
Hi,

when trying to add Branch framework as a dependency on another pod, the pod install commands complains: target has transitive dependencies that include static binaries

Are there any plans to convert the Branch framework to a dynamic library?

**Comment by tspent** [comment]
Hey, 

it's not a warning. It's an error, preventing from building an internal framework.
We have an internal framework/pod that we use (link) as a base for our apps, that is linked against Branch.

When adding Branch as a dependency in the .podspec file of our internal framework, Cocoapods spits out an error that Branch's framework is build as a static library and not dynamically.

The error:
`target has transitive dependencies that include static binaries (path/to/branch)`

**Comment by E-B-Smith** [comment]
I am looking in to this -- It's something I'd like to do in the near future, but since this library is used by so many people I want to get a feeling for the impact before simply changing it.

**Comment by ric2z** [comment]
bump — I'm having the same issue.

`framework not found Branch for architecture x86_64`

**Comment by E-B-Smith** [comment]
You can add Branch directly to your project as a dynamic library by adding the BranchSDK.xcodeproj file to your project. 

Here's a step-by-step guide:
https://github.com/BranchMetrics/ios-branch-deep-linking#adding-the-raw-files-branch-sdk-to-your-project
