### ISSUE TITLE
loadRewardsWithCallback and redeemRewards:forBucket:callback are not called on the main thread

### ISSUE THREAD

**Issue by warpling** [BranchMetrics/ios-branch-deep-linking#596]
Based on crashes I'm receiving it seems somewhere after `0.12.20` that `loadRewardsWithCallback:` or  `redeemRewards:forBucket:callback:` might have started running its callback on a thread other than main? I'm trying to absolutely confirm that this was not a change with my code but if anyone familiar with the code base knows I'd be much apprecaited!!

**Comment by warpling** [comment]
Seemed to be fixed in `0.12.50`! Can close but would love to confirm with someone that I wasn't crazy for seeing this in `0.12.30`…

**Comment by E-B-Smith** [comment]
I made sure that the call backs happen on the main thread in release 0.13.5.

**Comment by warpling** [comment]
Exactly what I noticed. Thanks for the confirmation. I'll work on using reward history to remedy the rewards I previously crashed delivering to my users.

**Comment by E-B-Smith** [comment]
Oh man, sorry about that.

**Comment by warpling** [comment]
Hopefully it's something a test gets added for in the future on both ends eh? ;)
It'd definitely a bit of a headache but luckily since the creditHistory does exist I should be able to roughly fix it using date ranges. There isn't a way to check the SDK version the rewarded was redeemed by is there?

**Comment by E-B-Smith** [comment]
Not easily.  How many do you think there are?

**Comment by warpling** [comment]
~13k credits for ~11k users. If it requires anything crazy don't worry about it, I think the date range thing—although potentially messy—should be sufficient.

**Comment by E-B-Smith** [comment]
I'm not sure I could improve the search much beyond a date range.

**Comment by warpling** [comment]
No worries! I'll see what I can do.
