### ISSUE TITLE
How do I access metadata when branch link was clicked and opened my app...?

### ISSUE THREAD

**Issue by kunass2** [BranchMetrics/ios-branch-deep-linking#602]
This is how I prepare and share branch link to the users:

            let branch = BranchUniversalObject(canonicalIdentifier: UUID().uuidString)
            branch.title = self.territory.name
            branch.metadata = self.territory.dictionary
            
            let properties = BranchLinkProperties()
            properties.controlParams = self.territory.dictionary
             
            branch.getShortUrl(with: properties) { string, error in
             
                if let string = string, let url = URL(string: string) {
                    
                    let controller = UIActivityViewController.controller(activityItem: url, from: sender, traitCollection: self.traitCollection)
                    
                    alert.dismiss(animated: true)
                    self.present(controller, animated: true)
                }
            }

Then I would like to access parameters I passed to that link, but I do not know how... Any help?

I mean: What do I do within `application:continueUserActivity`?

**Comment by E-B-Smith** [comment]
You can check the link parameters, including any metadata, in the deep link handler you set when you initialize Branch with `initSession` in your application's `application:didFinishLaunchingWithOptions:` method.

Also, make sure your app delegate `continueUserActivity` method passes the user activity to Branch:

```
    // Respond to Universal Links
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
        // pass the url to the handle deep link call
        Branch.getInstance().continue(userActivity);
        return true
    }
```

**Comment by kunass2** [comment]
Don't understand... what if my app is in the background mode? And then I tap the link from iMessage (for example)... didFinishLaunching is not called then. I need to do sth in my app, when my app is opened from a branch link. What do I do is determined by metadata... but how can I access it? Could you show me an simplest example?

**Comment by E-B-Smith** [comment]
Yes -- Look at the examples included in this repo, either Branch-TestBed or Branch-TestBed-Swift.

There's also the Branchster project you can look at here: [Branchster.](https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-iOS)

**Comment by kunass2** [comment]
thank you...

**Comment by kunass2** [comment]
Works perfect:) One more question... 

I get a warning: `[Answers] Event attribute values must be of type NSString or NSNumber.`. What does it mean?

**Comment by E-B-Smith** [comment]
NSString and NSNumber are obj-c types that are bridged to Swift. The Swift equivalents are regular strings and numbers.

Here's what Apple says:  https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/BuildingCocoaApps/WorkingWithCocoaDataTypes.html

Maybe you're assigning a dictionary or array to the Answers event attribute value?

**Comment by kunass2** [comment]
Yes, here:

    branch.metadata = self.territory.dictionary

I assign to metadata dictionary with values as: strings, ints, arrays

**Comment by jdee** [comment]
Hi @kunass2. Metadata keys and values must be strings. Unfortunately, the SDK doesn't always limit these properly. Assigning anything other than a `[String: String]` in Swift ought to be a compilation error, but isn't. There is also a BUO method `addMetaDataValue(_: String, key: String)` that properly enforces this. We can probably improve this in future releases, but for now, please limit metadata to strings.

Regarding your Answers error message: Are you using Fabric Answers directly, or is that coming from the Branch SDK? If it's coming from the Branch SDK, it's probably related to the metadata issue. If you're using Answers yourself, please be aware that custom parameters with Answers must be numbers or strings, and this influences how Answers reports them. See [their documentation](https://docs.fabric.io/apple/answers/answers-events.html#id12) for more information.

**Comment by kunass2** [comment]
ok... but what is the other way to pass array to branch link?

**Comment by jdee** [comment]
@kunass2 You probably just have to serialize and deserialize it yourself. You could use an extension like this:

```Swift
extension Array {
    init?(stringRepresentation: String) {
        do {
            guard let data = stringRepresentation.data(using: .utf8) else { return nil }
            guard let object = try JSONSerialization.jsonObject(with: data, options: []) as? Array else { return nil }
            self.init(object)
        }
        catch {
            return nil
        }
    }

    var stringRepresentation: String? {
        get {
            do {
                let data = try JSONSerialization.data(withJSONObject: self, options: [])
                return String(data: data, encoding: .utf8)
            }
            catch {
                return nil
            }
        }
    }
}

func testArrayExtension() {
    let array = [ 1, 2, 3 ]
    guard let stringRepresentation = array.stringRepresentation else {
        print("could not serialize array")
        return
    }
    
    guard let newArray = [Int](stringRepresentation: stringRepresentation) else {
        print("could not deserialize array")
        return
    }

    print("new array from deserialization: \(newArray)")
}
```
