### ISSUE TITLE
Universal link with branch.io doesnt work with iPhone when it works with iPad

### ISSUE THREAD

**Issue by kunass2** [BranchMetrics/ios-branch-deep-linking#604]
My App is in production now, and within my app I create a Universal link using **branch.io** and share it to other users using for example iMessage. Example link below I got from my friend is below:

- [![enter image description here][1]][1]

I have the app from App Store installed on both devices: iPad and iPhone. Now the above link I tap on iPad and everything is fine. My App is opened I can catch the link:)

But when I tap it on iPhone the result is following:

[![enter image description here][2]][2]

Why? Shouldnt it works the same way on both: iPad and iPhone? I do not know what is wrong here... Any questions? I can change and add additional info here to help the solve the problem.

This is how I defined it in dashboard:

<img width="978" alt="screen shot 2017-03-28 at 18 38 30" src="https://cloud.githubusercontent.com/assets/9480650/24416668/dfdbbfa2-13e5-11e7-9d6b-dc6ed3872ebf.png">

  [1]: https://i.stack.imgur.com/A9LIsm.png
  [2]: https://i.stack.imgur.com/Cf6csl.png

**Comment by jdee** [comment]
Hi @kunass2. Can you provide a sample link that is failing? That might be the fastest way to find the problem.

Another quick thing you can test: Mail yourself the link and then open the mail message in the iOS Mail app on the device. Long-press the link in the mail message. That should show you a menu. There should be two options: _Open in "Field Service" App_ and _Open in Safari_. If you select _Open in "Field Service" App_, does that open your app? After that, if you go back to Messages and tap the link, does the link behave differently now?

**Comment by kunass2** [comment]
sample link: https://fieldserviceios.app.link/nmiuHCLYSB, now i will do your test.

**Comment by kunass2** [comment]
OK, I did what you say.
- share the link with myself via MAIL APP
- do long press, present context menu and choose _open in field service app_ (the link was opened in my app)
- then I get back to messages App and tap the link: (it also opens my app...)

Why there is a difference?

**Comment by jdee** [comment]
Your test results mean that it's an instance of a known problem. Apple discontinued support for custom URI redirects in iOS 9.2. Once a user chooses to direct your domain to Safari, Branch cannot force a link back to the app if the app is installed. I wrote up [an explanation](https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/110#issuecomment-282893587) in another GitHub issue (under **Here's what's going on**). Using Branch [Deepviews](https://dev.branch.io/features/deepviews/overview/) can help with this issue. This is just a setting you activate in the Dashboard. You can easily try it out in the test environment.

**Comment by wassimseif** [comment]
I'm having an issue, the opening the app from safari works, however none of the functions in the appdelegate are getting called
