### ISSUE TITLE
 the links expires no matter what exp_date or expiration_date is sent for the text me the app feature please help

### ISSUE THREAD

**Issue by markmark1** [BranchMetrics/ios-branch-deep-linking#607]
If there is a bug or error in this repo, please file the issue here. 
https://dev.branch.io/features/text-me-the-app/guide/ the links expires no matter what exp_date or expiration_date is sent for the text me the app feature please help
If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.
https://dev.branch.io/features/text-me-the-app/guide/

**Comment by markmark1** [comment]
https://bnc.lt/clOk/d/Sgn1TPNdHx https://bnc.lt/zpOk/d/bmwTi3CTLx https://bnc.lt/clOk/d/YM7OZMBrVx example expired links from sms

**Comment by E-B-Smith** [comment]
What was the solution?

**Comment by markmark1** [comment]
No solution yet 😳






On Thu, Mar 30, 2017 at 2:56 PM -0700, "Edward Smith" <notifications@github.com> wrote:












What was the solution?

**Comment by markmark1** [comment]
On Thu, Mar 30, 2017 at 3:00 PM -0700, "markmark1" <notifications@github.com> wrote:










No solution yet 😳













On Thu, Mar 30, 2017 at 2:56 PM -0700, "Edward Smith" <notifications@github.com> wrote:

























What was the solution?

**Comment by markmark1** [comment]
https://image.ibb.co/c0Ycka/IMG_3085.png They delete every week so how to make a link that doesn't expire

**Comment by markmark1** [comment]
How to have links that don't expire

**Comment by E-B-Smith** [comment]
I checked in the back end.  Right now the text-me-the-app links expire at 7 days.

This is something it seems we might re-visit in the future, but right now that's how it is.

Sorry about that.  Maybe send the link with a fall back message?

**Comment by markmark1** [comment]
Ed how to make it so links don't expire is there another means of generating a link 






On Thu, Mar 30, 2017 at 4:58 PM -0700, "Edward Smith" <notifications@github.com> wrote:












I checked in the back end.  Right now the text-me-the-app links expire at 7 days.


This is something it seems we might re-visit in the future, but right now that's how it is.


Sorry about that.  Maybe send the link with a fall back message?

**Comment by markmark1** [comment]
Is there a way to generate links wo text me method thanks 






On Thu, Mar 30, 2017 at 4:58 PM -0700, "Edward Smith" <notifications@github.com> wrote:












I checked in the back end.  Right now the text-me-the-app links expire at 7 days.


This is something it seems we might re-visit in the future, but right now that's how it is.


Sorry about that.  Maybe send the link with a fall back message?
