### ISSUE TITLE
[Crash] Release 0.14.9

### ISSUE THREAD

**Issue by lucianocn** [BranchMetrics/ios-branch-deep-linking#610]
XCODE Version 8.3 (8E162)
IOS 10.3

Updated from 0.13.5 to 0.14.9:

<img width="910" alt="screen shot 2017-03-31 at 03 21 29" src="https://cloud.githubusercontent.com/assets/3828136/24538704/2d6fb9ee-15c1-11e7-98c6-e53193dd3986.png">

**Comment by E-B-Smith** [comment]
I am releasing a fix for this now.  What platform are you running on?

**Comment by E-B-Smith** [comment]
This is fixed in release 0.14.10.

I still want to know what platform are you were running on and the kind of app distribution are you using.  I am curious because I didn't see this in my tests.

**Comment by lucianocn** [comment]
I tested with my iPhone 7 iOS 10.3
Running the app into debug mode and also with branch debug key.

Do you need more info?

**Comment by E-B-Smith** [comment]
Are you developing a special type of application?  Like an iMessage extension or iWatch app?

**Comment by lucianocn** [comment]
@E-B-Smith No, it's a default obj-c iOS application.

**Comment by lucianocn** [comment]
@E-B-Smith It's a default iOS application that also have an iMessage extension.
But the Branch SDK is only used in the main app.
