### ISSUE TITLE
branch.framework 0.14.10 build failed

### ISSUE THREAD

**Issue by adeb6600** [BranchMetrics/ios-branch-deep-linking#612]
If there is a bug or error in this repo, please file the issue here. 
branch.framework 0.14.10 failed to build 
BranchShareLink.h not found
If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by E-B-Smith** [comment]
How are you integrating Branch into your project?  Through direct integration, CocoaPods, or Carthage?

**Comment by Caiopia** [comment]
I'm also getting this error with 0.14.10. It seems like `BranchShareLink.h ` is not in `Branch.framework/Headers/`. Adding it there seems to fix it for me.

**Comment by E-B-Smith** [comment]
Fixed in release 0.14.11.
