### ISSUE TITLE
getShortUrl never calls callback

### ISSUE THREAD

**Issue by edenman** [BranchMetrics/ios-branch-deep-linking#620]
I recently switched to using Branch to generate the referral links when one user of my app wants to invite their friends:
```
	private static func getBranchLink(_ promoCode: String, after: Double) {
		if after > 10 {
			LogNonFatal("Retries exhausted building branch link, giving up.")
			return
		}
		Async.userInitiated {
			let userID = store.user.user!.id!
			let code = promoCode
			let branchUniversalObject = BranchUniversalObject(canonicalIdentifier: "referral-from/\(userID)")
			branchUniversalObject.canonicalUrl = "https://mydomain.com/path?promoCode=\(code)"
			branchUniversalObject.contentDescription = "Referral from user \(userID)"
			branchUniversalObject.contentIndexMode = ContentIndexMode.private
			branchUniversalObject.addMetadataKey("code", value: code)
			branchUniversalObject.addMetadataKey("userID", value: userID)
			let linkProperties = BranchLinkProperties()
			linkProperties.feature = "referral"
			linkProperties.channel = "sms"
			branchUniversalObject.getShortUrl(with: linkProperties) { (url, error) in
				if url != nil {
					DDLogDebug("Got a valid branch referral link!")
					// Do stuff with the link
				} else {
					let error = error!
					if error._code == BNCServerProblemError {
						let newDelay = after * 2
						DDLogDebug("Server issue when building a branch link, retrying again in \(newDelay)s.  Error: \(error)")
						Async.userInitiated(after: newDelay, { getBranchLink(promoCode, after: newDelay) })
					} else {
						DDLogError("Failure to build branch link \(error._code): \(error.localizedDescription)")
					}
				}
			}
		}
	}
```

sometimes I call getShortUrl and it just never calls the callback (I don't see any "Failure to build branch link" or "Got a valid branch referral link" messages in the logs).  If it matters, here's how I'm initializing the session:

```
		Branch.getInstance().initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { params, error in
			if error == nil && params != nil {
				// do stuff
			} else {
				DDLogError("Unable to register with Branch. Error: \(error.orNil)")
			}
		})
```
I don't see any "Unable to register with Branch" messages in the logs either, so I don't think this is necessarily relevant, but who knows.  I'm unable to repro this problem (the links are generated fine on my device) but it's happened to 60 users so far (and my app doesn't have that many users to begin with).  Halp!

**Comment by E-B-Smith** [comment]
Sorry you're having problems!  

So you're unable to reproduce the problem on your phone, but other users are having problems.

All users, or just some users? Also, are you testing with a Branch live key or a test key?  Are you shipping the code to users with the live or test key?

**Comment by edenman** [comment]
@E-B-Smith 
1) I'm not sure if it's all users or some users: i don't currently have any logging around the success case.  I'll add this to my next dot release.
2) I'm testing with a live key
3) I'm shipping the code to users with the same live key

**Comment by E-B-Smith** [comment]
It seems like you're using the right keys. And you're making the call to `Branch.getInstance().initSession(...)` in `application:didFinishLaunchingWithOptions` before doing any other Branch thing, right?

The callback won't get called if the `getShortUrl` call to the Branch servers to generate the link hasn't completed and the user kills the app.  The short link will still get generated but the callback won't be called.

Do you think this could be happening?

**Comment by edenman** [comment]
I don't think it's a "if the call hasn't completed and the user kills the app" situation.  There's some code in my app that polls the "get my referral code" endpoint every 30s.  If it's changed (or if the Branch link hasn't been generated yet) we generate a new Branch link.  For one of these users, I see logs where the Branch link is nil, so we try to create it every 30s, and every time we don't get a response.

That said, it's entirely possible I've got a race condition based on when I'm calling `initSession` (I was calling it at the end of `application:didFinishLaunchingWithOptions` and I had some Async blocks that were kicked off beforehand).  I'll try moving that call earlier to guarantee it runs before I interact with the Branch SDK in any other way.

**Comment by E-B-Smith** [comment]
Thirty seconds is probably too short a timeout on mobile, especially if the network conditions are poor.

Plus, the Branch SDK will retry the request automatically if there is a recoverable network failure.

Try a retry timeout of 90 seconds or more.

**Comment by E-B-Smith** [comment]
I think this will work for you and explains why it works for you (on a good network) but fails in real life.

If you continue to not see call backs let me know.
