### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by alexsanderkhitev** [BranchMetrics/ios-branch-deep-linking#623]
Hello! Thanks for the wonderful framework. I use the Branch SDK for deep links to the iOS application. The problem appears in the following cases if you send a deep link to a third-party application (for example, Slack, Facebook) quickly, then an app crash occurs. The console shows the following result `[core] SLComposeViewController dealloc <SLComposeViewController: 0x11fbf03a0>.`  How can I fix it?

My code 

    func shareCardDetail(_ cardModel: CardModel) {
            let shareText = "What do you think about this?"
            let branchUniversalObject = BranchUniversalObject(canonicalIdentifier: ("cardId/\(cardModel.id)"))
            branchUniversalObject.title = cardModel.title
            branchUniversalObject.contentDescription = ""
            branchUniversalObject.imageUrl = cardModel.photoURLsProperties.placeVenuePhoto
        
            branchUniversalObject.addMetadataKey(CardKeys.cardID.rawValue, value: cardModel.id)
            
            if let placeAvatarURLString = cardModel.photoURLsProperties.placeVenuePhoto {
                branchUniversalObject.addMetadataKey("placeAvatarURLString", value: placeAvatarURLString)
            }
            branchUniversalObject.addMetadataKey("title", value: cardModel.title)
            branchUniversalObject.addMetadataKey("isAutoGeneratedCard", value: "false")
            
            let fullLocationName = cardModel.location.fullLocationName
            branchUniversalObject.addMetadataKey("fullLocationName", value: fullLocationName)
            
            branchUniversalObject.addMetadataKey(CardKeys.ownerID.rawValue, value: cardModel.ownerID)
            branchUniversalObject.addMetadataKey(ParametersKeywords.type.rawValue, value: ModeKeywords.shareCard.rawValue)
            
            branchUniversalObject.addMetadataKey("availableSeats", value: cardModel.peopleProperties.availableSeats.description)
            
            if let coordinate = cardModel.location.coordinate {
                branchUniversalObject.addMetadataKey("latitude", value: coordinate.latitude.description)
                branchUniversalObject.addMetadataKey("longitude",value: coordinate.longitude.description)
            }
            
            
            let linkProperties = BranchLinkProperties()
            linkProperties.feature = "sharing"
            linkProperties.addControlParam("$desktop_url", withValue: "http://www.example.com")
            linkProperties.addControlParam("$ios_url", withValue: "example://")
            
            guard let topViewController = UIApplication.topViewController() else { return }
            
            branchUniversalObject.showShareSheet(with: linkProperties, andShareText: shareText, from: topViewController) { (text, success) in
                debugPrint("done showing share sheet!")
            }
        }

**Comment by E-B-Smith** [comment]
Thank you for the compliment!  Sorry to hear about your crash.

Have you tried the new `BranchShareLink` class to share Branch universal objects? It has more flexibility and may solve your crash problem.

Your app needs to hold on to a reference to the BranchUniversalObject that you just created until the sharing the object.  The new  `BranchShareLink` class automatically does this for you.

Feel free to reopen this issue if these suggestions don't fix your crash.

**Comment by alexsanderkhitev** [comment]
Hello @E-B-Smith thank you for response. 

I did as you said, but when I send a deep link on the side of the application (like Slack, Facebook), I sometimes get an app crash. Tell me please, what needs to be corrected, what would it not be.

```
  guard let branchShareLink = BranchShareLink(universalObject: branchUniversalObject, linkProperties: linkProperties) else { return }
        branchShareLink.shareText = shareText
        branchShareLink.presentActivityViewController(from: topViewController, anchor: nil)
```

Logs

```
2017-05-06 10:01:06.360789+0400 ***[650:106883] [core] SLComposeViewController completeWithResult: 1
2017-05-06 10:01:06.362675+0400 ***[650:106883] [core] SLComposeViewController skipping explicit dismiss because isBeingDismissed is already 1
2017-05-06 10:01:06.387956+0400 ***[650:106883] [core] SLComposeViewController dealloc <SLComposeViewController: 0x13dc912a0>
```

**Comment by E-B-Smith** [comment]
Here's an example:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed-Swift/TestBed-Swift/ViewController.swift#L215-L240

**Comment by alexsanderkhitev** [comment]
@E-B-Smith thanks

**Comment by jeffvstudio** [comment]
Hey @E-B-Smith, we're facing same issue, and the link is broken :( Could u pls let me know where i can  see how to implement this? I'm watching this object in this link but it's used on "Share message dynamically part", not sure if that's what i really need. Appreciate your help!

Thanks!

https://docs.branch.io/pages/apps/ios/

**Comment by E-B-Smith** [comment]
Sorry about the broken link!  Here's a link to a Swift example:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/015db1db4cf976acc1a6ac31f1e00c809b1506cd/Branch-TestBed-Swift/TestBed-Swift/HomeViewController.swift#L480-L508

If you want to share a link and change the share text or other link properties during the share action, you can add a delegate call back and change it before it's presented to the user by adding a delegate call back:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/015db1db4cf976acc1a6ac31f1e00c809b1506cd/Branch-TestBed-Swift/TestBed-Swift/HomeViewController.swift#L510-L534

Hope this helps!
@jeffvstudio
