### ISSUE TITLE
Cannot attach imageData as String

### ISSUE THREAD

**Issue by kunass2** [BranchMetrics/ios-branch-deep-linking#624]
I create it like this:

                let imageData = UIImagePNGRepresentation(image)
                var dictionary = [AnyHashable: Any]()
                dictionary["imageData"] = imageData?.base64EncodedString()

                let branch = BranchUniversalObject(title: address.title)
                branch.metadata = ["territory": dictionary]
                branch.getShortUrl(with: BranchLinkProperties()) { string, error in
                    
                    if let string = string, let url = URL(string: string) {
                        
                        let controller = UIActivityViewController(activityItems: [url], applicationActivities: nil)
                        self.present(controller, animated: true)
                    }
                }
                
It is fine, then I select iMessage app, and:

![img_0691](https://cloud.githubusercontent.com/assets/9480650/25838823/3f32de84-3495-11e7-8e19-a4edfb0245e8.PNG)

Why it doesnt work? When I put anothe different dictionary:

                branch.metadata = ["territory": ["a": 1, "b": 1]]

then it works fine... but I have to pass an image somehow.

**Comment by E-B-Smith** [comment]
Try using a `BranchShareLink` object to share your link, which handles much of the complexity of presenting a UIActivityViewController for you.  Here's an example:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed-Swift/TestBed-Swift/ViewController.swift#L242-L273

To add an image to a shareLink, assign the UIImage to `shareLink.shareObject`,  like this:

```
            branchShareLink.title = "Share your alias link!"
            branchShareLink.delegate = self
            branchShareLink.shareText = 
                "Shared from Branch's TestBed-Swift at \(self.dateFormatter().string(from: Date()))"
            branchShareLink.shareObject = image  // <= Add your image here <=
            branchShareLink.presentActivityViewController(
                from: self,
                anchor: actionButton
            )
```

I hope this helps!

**Comment by kunass2** [comment]
How does it work when I need to share an image along with dictionary? Will it work if an image will be under "image" key in this dictionary?

**Comment by E-B-Smith** [comment]
You can't share image data directly in the Branch link, but you can share a URL to an image with a Branch link, like this:

```
        shareBranchObject.imageUrl = "https://branch.io/img/press/kit/badge-black.png"
```

If you want to include an image in the UIActivityViewController you can use the example I provided above.

**Comment by kunass2** [comment]
I think it is not what I expect. I need to access that image from within an app when someone tap that link and open my app.

**Comment by E-B-Smith** [comment]
What exactly are you trying to do?

**Comment by kunass2** [comment]
Ok, simply I developed an app... and inside that app I attach objects called `Terrritories`. Every territory has some parameters: name, location, addresses, status, image (selected from Photos). Such territory can be shared to other user with Universal linking. Thanks Branch.io I can create a link and associate with them some info. So I do it like this and it works... but only simple parameters (without image). User A sends a link generated by Branch.io to user B with iMessage app. User B tap on the link, opens my app, and I catch all associated data (location, name... etc)... except image. Now I would like to attach an image there. Is it possible?

It is not about to attach an image to a link and send it next to link. The link itself should somehow cantain data about the image:)

Can I do this using Branch.io?

**Comment by E-B-Smith** [comment]
You should probably keep image data on your own servers and just send a URL to that image in the Branch link.  Otherwise the Branch link data gets too big and really slows down the network traffic and makes for a bad user experience.

Otherwise, you can include the image as one of the activityItems in the UIActivityViewController.

**Comment by kunass2** [comment]
Thanks for your help:)

**Comment by E-B-Smith** [comment]
Good luck!
