### ISSUE TITLE
Using Branch pod with 'Legacy Swift Language Version' ( Swift 2.3)

### ISSUE THREAD

**Issue by roimulia** [BranchMetrics/ios-branch-deep-linking#638]
Hey! 
Due to unfortunate circumstances our iOS app (which is mainly Objective-c based) running Swift 2.3, on xCode Version 8.2.1. Until now we were using Branch version  '0.12.13'. When I was trying to 'pod update Branch', it worked. But it complained about the Swift version we are using.
If there is no other solution, other than updating our Swift version to 'Swift 3.0', we will, but we are trying to avoid it. 
Does Branch pod requiring specific Swift version? Or it's not related to each other?

**Comment by E-B-Smith** [comment]
The Branch SDK works just fine with Swift 2.3.

Somewhere in a subproject a compiler flag for Swift 3.0 is set, somewhere in example code, and that is making the whole pod require Swift 3.0.

You can safely make the project use Swift 2.3 and in the meantime I'll figure out which project is causing the issue.

Are you including the pod as a dynamic library or are you compiling it?

Thanks for the heads up.

**Comment by roimulia** [comment]
Hey @E-B-Smith , Thank you for the fast response!
I'm not 100% sure, but I think we are using it as a dynamic library because i'm declaring 'use_frameworks!' at the start of my podfile.
 I will wait for your respond about where the flag is set, thank you Smith!
----

One question tho, I'm a bit confused.
After doing 'pod update Branch', when checking the 'Branch' pod directory inside xCode, I'm only seeing the h/m files without any subproject or Swift files.
So why would it requite my xCode to update to the newest Swift version, if there no actually demands inside xCode? ( I guess i'm missing something). Attaching photo.
Thank you Smith! 

Where core folder contains the h/m files.

<img width="308" alt="screen shot 2017-06-05 at 10 12 58 am" src="https://cloud.githubusercontent.com/assets/9759595/26774161/99ff2424-49d7-11e7-8863-47e57aa45084.png">

**Comment by E-B-Smith** [comment]
I just built a Swift 2.3 version of our testbed app and didn't have a problem with the Swift version -- Neither Xcode nor CocoaPods complained about any version problems.

This is the pod file I used:
```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '7.0'

target "TestBed-Swift" do
  pod "Branch"
end
```

I did a `pod install` and a `pod update` and I am using Xcode 7.3.1 to compile.
