### ISSUE TITLE
BNCDeviceInfo.m line 81 CRASH

### ISSUE THREAD

**Issue by hatebyte** [BranchMetrics/ios-branch-deep-linking#644]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

App is crashing on launch when it requests device info. Mostly occurs with iOS 9 and below but the issue has risen drastically in the last few days.

[branch_crash.txt](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1099833/branch_crash.txt)

<img width="899" alt="screenshot 2017-06-24 10 44 10" src="https://user-images.githubusercontent.com/1091447/27509419-77498a58-58ca-11e7-9221-5d49a4cb5e93.png">

**Comment by E-B-Smith** [comment]
Sorry to hear about your crashes!

We haven't updated that part of the SDK in a few months, and I don't have any other reports of crashing in that part of the code. I've tested it on iOS 7,8,9,10 and 11 devices.  So I'm a little perplexed about your problem.

Which version of the Branch SDK are you using? Are these crashes isolated to a particular kind of device?  Have you tried updating to the latest version of the Branch SDK?

**Comment by hatebyte** [comment]
@E-B-Smith 
We are using `Branch (0.12.16)` via  `mParticle-BranchMetrics (6.11.0)`.
Curiously, there was similar crash in Mixpanels' SDK this week, also when they we collecting device properties. They have since patched it, but it does seem odd to me that 2 SDKs would have such a tightly related problem in this close a time frame.

We will try updating to the latest. Looks like `Branch (0.15.3)` via  `mParticle-BranchMetrics (6.14.0`. We are always hesitant to upgrade when something is working well.

Here is the mixpanel stack trace if you are interested.
[mixpanel.txt](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1099999/com.stash.stash-invest_issue_545_crash_95e38cf2921e4fd7ac8fd4b8e3ca0768_184a657e572311e78d9156847afe9799_0_v2.txt)

**Comment by E-B-Smith** [comment]
The issue in that Mixpanel stack trace doesn't look related.

You can see the area of the code that is crashing here:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCDeviceInfo.m#L61-L85

We get the country and local differently depending on the iOS version.  Maybe there's something about those particular devices?  How much of an increase are you seeing?  Are you getting an uptick of installs from a new region in the world?

**Comment by heruohuan** [comment]
I also appeared in my application the same procedure Fenbu, do not know is the Branch of the bug
[branch_crash.txt](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1101451/branch_crash.txt)

**Comment by heruohuan** [comment]
I also appear in my application, the same program crashes, do not know the branch bug
[branch_crash.txt](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1101453/branch_crash.txt)

**Comment by E-B-Smith** [comment]
Thanks for the extra information.

I'm working on this now.  If you have any more information about this please send it along!

**Comment by hatebyte** [comment]
Actually @E-B-Smith, I followed up with marketing, and in fact it is as it seems. Its quite possible the campaign generated more users outside of the US than we have ever done before. So the noticeable uptick in crashes is indeed very tightly linked to the locale for sure.

thanks for acting so quick on this.

**Comment by E-B-Smith** [comment]
I have a fix for this that is being tested now.  I'll post again when the fix is available.

**Comment by E-B-Smith** [comment]
This is fixed in release 0.16.2.
