### ISSUE TITLE
Crash in BNCLog.m line 321

### ISSUE THREAD

**Issue by mignick** [BranchMetrics/ios-branch-deep-linking#661]
Hi!
We've updated to 0.16.2 and now see tens of crashes in production.
![screen shot 2017-07-27 at 11 56 10](https://user-images.githubusercontent.com/34469/28665170-1012ece0-72c3-11e7-8f5d-dbebd63fa5b6.png)

**Comment by E-B-Smith** [comment]
Thanks for reporting this issue!

Sorry you're having crashes.  I'm looking into this now.

**Comment by E-B-Smith** [comment]
Question:  Do you have file protection turned on?

**Comment by mignick** [comment]
No, it's off.

**Comment by E-B-Smith** [comment]
This issue has been fixed in release v0.17.3.

See the release notes at https://github.com/BranchMetrics/ios-branch-deep-linking/releases/tag/0.17.3
