### ISSUE TITLE
Crash in BranchOpenRequest.m line 121

### ISSUE THREAD

**Issue by bkovaly** [BranchMetrics/ios-branch-deep-linking#672]
Getting occasional crashes in the BranchOpenRequest. Currently using 0.15.3 of the app. I'm going to update to the latest, but I didn't see any changes to this file since 0.15.3 or any crash fixes in the change logs that might be related.

BranchOpenRequest.m line 121-[BranchOpenRequest processResponse:error:]
--

[__NSDictionaryM length]: unrecognized selector sent to instance 0x10bb2dc70

I do not have a repro for this, but I'm seeing quite a few crashes per day showing up in crashlytics. Let me know if I can provide any other info!

**Comment by E-B-Smith** [comment]
Thanks for reporting the issue.  I'm tracking this down now and I'll let you know when I publish a fix.

**Comment by E-B-Smith** [comment]
This crash is due to some bad data being passed back from the Branch back end server.  This isn't happening now, but there may have been some bad code in the past that did this by mistake.

I added a guard for session data. Sometimes the session data is not stringified (an error on the backend) but this guards against a crash in the SDK in the future.

**Comment by bkovaly** [comment]
Awesome! Thanks for the speedy turn around! When you say "bad code in the past", how recent do you mean? Looks like we've had 93 crashes in the last 24 hours for this. Just want to make sure there isn't an existing issue on the backend that hasn't been fixed :)

**Comment by E-B-Smith** [comment]
I'll talk to the back end guys about this again!

**Comment by E-B-Smith** [comment]
Are you running a campaign in a new country or region that may have 1) old versions of the app 2) a different string encoding?

You can email me at esmith@branch.io.

**Comment by dostrander** [comment]
Hey @E-B-Smith when are you going to cut the next release. I would like to get the commit with you adding guards to the data coming back in ASAP.

**Comment by E-B-Smith** [comment]
I'm putting the SDK through the QA regimen now and it will be out today.  I'll post here and elsewhere when it's released.

**Comment by dostrander** [comment]
Great, thank you!

**Comment by E-B-Smith** [comment]
This issue has been fixed in release v0.17.3.
See the release notes at https://github.com/BranchMetrics/ios-branch-deep-linking/releases/tag/0.17.3
