### ISSUE TITLE
Branch + Fabric crashing on startup

### ISSUE THREAD

**Issue by dostrander** [BranchMetrics/ios-branch-deep-linking#680]
Getting this as I'm upgrading from 0.11.16 to 0.17.5. Not sure how to fix since I am not using fabric

`[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.'`

**Comment by E-B-Smith** [comment]
Thanks for reporting the issue.  I think I know what this is and can get a fix for you pretty quick.

Are you using Crashlytics?

**Comment by dostrander** [comment]
Yeah I am

**Comment by E-B-Smith** [comment]
Crashlytics requires Fabric now.  Are you using an old version of Crashlytics?

**Comment by E-B-Smith** [comment]
And did you add your Fabric key?

https://fabric.io/kits/ios/crashlytics/manual-install?step=0

**Comment by dostrander** [comment]
So I have 1 (let's call it targetA) target using crashlytics and has the correct information in the info.plist. I also have another target (targetB) that has fabric within the project (because it's cocoapods) however doesn't actually use it at all. 

From what I can see, you check to see if the Fabric class is there and if it is you try to do your own fabric config internally? I'm not 100% sure.

**Comment by E-B-Smith** [comment]
We are loosely linking to both Fabric and Crashlytics.

If Fabric is linked then we track some user events in Fabric.

If Crashlytics is linked then we track the SDK version and some debugging information in Crashlytics.

Crashlytics requires Fabric as a dependency. So you should include Fabric and your Fabric key in the project that is using Crashlytics too.

**Comment by dostrander** [comment]
Ok yeah that answers my question. The problem I am running into is `TargetB` has Fabric/Crashlytics linked however, doesn't have any configuration nor doesn't use it whatsoever. Is there a way to opt-out of the fabric/crashlytics stuff even if we have it linked?

**Comment by jdee** [comment]
If you're not using Crashlytics in a target, you can also omit it in your Podfile for that target.

```ruby
# common pods
pod "LibraryA"
pod "LibraryB"

target "targetA" do
  pod "Crashlytics"
  pod "LibraryC"
end

target "targetB" do
  pod "LibraryD"
end
```

**Comment by dostrander** [comment]
that is definitely a possibility. However, trying to avoid that if possible, for not very good reasons… haha

**Comment by E-B-Smith** [comment]
Were you able to resolve this?
