### ISSUE TITLE
Address Sanitizer gives an error in Branch.

### ISSUE THREAD

**Issue by alexsanderkhitev** [BranchMetrics/ios-branch-deep-linking#684]
Hello! I ran the manage scheme with the Address Sanitizer enabled and I get an error right away when the application starts.

![bnclog m 2017-08-11 17-55-15](https://user-images.githubusercontent.com/12511909/29216974-62ff1032-7ec1-11e7-8fd9-0b92c8baeda4.png)

**Comment by E-B-Smith** [comment]
Thanks for the screen shot.  The fix is PR #685.

https://github.com/BranchMetrics/ios-branch-deep-linking/pull/685

I'll update the master repo today.

**Comment by E-B-Smith** [comment]
I've updated the master branch and made a new release.

Thanks for the report!

https://github.com/BranchMetrics/ios-branch-deep-linking/releases/tag/0.17.6
