### ISSUE TITLE
When i try to update pod then getting error in app//

### ISSUE THREAD

**Issue by developweb10** [BranchMetrics/ios-branch-deep-linking#690]
[self.universalObject userCompletedAction:BNCShareCompletedEvent];
![screen shot 2017-08-17 at 3 17 04 pm](https://user-images.githubusercontent.com/7962363/29406637-3867f1c0-835f-11e7-9455-1f19ad80b808.png)

**Comment by E-B-Smith** [comment]
That's odd.  I pulled the pod and all my projects built okay.

Are you using including the pod as a frame (use_frameworks! in your podfile)?  Any other clues for me to diagnose this?

**Comment by E-B-Smith** [comment]
Please re-open if you're still having problems!
