### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by Formerly** [BranchMetrics/ios-branch-deep-linking#694]
pod 'Branch'

  pod 'Braintree'
  pod 'Braintree/DataCollector'
  pod 'Braintree/Venmo'
  pod 'Braintree/Apple-Pay'

iOS8 Start the jammed.Have libraries conflict?

**Comment by E-B-Smith** [comment]
Are you including the Branch SDK as a static or dynamic library?

I'll try your pod configuration myself in an example project.  Can you post your whole Podfile?

**Comment by E-B-Smith** [comment]
I've publish release v0.17.10 which fixes your problem #695 .

Let me know if you have any other problems!
