### ISSUE TITLE
Symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by karthikasdas** [BranchMetrics/ios-branch-deep-linking#698]
Hi,

I have integrated Branch though cocoapods. I am getting the following error when trying to install on iPhone 6 plus and 6s and is working perfectly fine with iPhone 5. 

Kindly help!

Showing All Messages
  "_OBJC_CLASS_$_Branch", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks,
Karthika

**Comment by E-B-Smith** [comment]
Make sure you have arm64 architecture turned on in your project's build settings. Also, if you are trying to use the same binary for both iPhone 5 and 6 (and others), make sure that  and that 'Build for Active Architecture Only' is turned *off*.

Hope this helps!
