### ISSUE TITLE
LaunchArguments (AppleLanguages and AppleLocale) are ignored after update to 0.17.x

### ISSUE THREAD

**Issue by matkuznik** [BranchMetrics/ios-branch-deep-linking#707]
After updated branch framework to version 0.17.10 (from 0.14.12) our test started to fail because of wrong language/region in the Simulator. 
After back to version 0.14.12 everything works correctly. 

Language and regions are set in Scheme settings or programatically (via XCUIApplication)

We tested this multiple times on different Macs (at least 4 Macs).

**Comment by E-B-Smith** [comment]
I'll check with the old version to see what's up.

**Comment by E-B-Smith** [comment]
PR #708 fixes this.  The patch is in QA now and will be available soon. I'll update you when this is released.

Thanks for reporting this issue!

**Comment by E-B-Smith** [comment]
I fixed this in version 0.18.8.

https://github.com/BranchMetrics/ios-branch-deep-linking/releases/tag/0.18.8
