### ISSUE TITLE
clicking branch link in app and going back

### ISSUE THREAD

**Issue by littlehome-eugene** [BranchMetrics/ios-branch-deep-linking#710]
Here's the problem we face.  

In viewController1, there's a webview and a branch link (bnc.lt/...)
When a user clicks the link, we open up a viewController2 and load the url. 
When he/she clicks a back button, we check if we can go back with `webview.canGoBack` and goes back.  

With normal link it works fine, but with branch link we are facing a problem.

It is as if there's an intermediate url we visit which redirects us to the original url.  
So hitting a back button goes to the intermediate url and it redirects the user to the starting url.

www.example.com => bnc.lt/1

when clicking bnc.lt/1 user goes to `some intermediate url` then gets redirected to `www.example.com` . 
So if he tries to go back, he goes to `the intermediate url` and gets redirected to `www.example.com` again.

I'd like to know if it's indeed the reason why we are not being able to go back. 
And wonder if there's a recommended fix?

**Comment by E-B-Smith** [comment]
The Branch link uses the intermediate redirect to check if any Branch 'magic' needs to happen with the link before going to ultimate link destination.

Probably the quickest way for you to fix this to check in the delegate if the user is going back from a Branch link and simply go back twice.  This seems like kind of a hack though.

Let me think about a better solution.  What kind of web view are you using?

**Comment by E-B-Smith** [comment]
Did this solution work for you?

What did you decide to do for a work around?

**Comment by E-B-Smith** [comment]
See the WebViewExample in the 'Examples' directory to see how to do this.
