### ISSUE TITLE
iOS SDK  handleDeepLink = false when using Own Domain

### ISSUE THREAD

**Issue by ADevelopStudio** [BranchMetrics/ios-branch-deep-linking#713]
Hi there, 
Noticed that 
` let handle =  Branch.getInstance().handleDeepLink(withNewSession: url)
`
returns false after I changed link domain to my own. 
The method runs and the deeplink is handled properly, but anyway strange behaviour. 
I used logic:
```
            let handle =  Branch.getInstance().handleDeepLink(withNewSession: url)
            if !handle && UIApplication.shared.canOpenURL(url) {
                UIApplication.shared.open(url, options: [:], completionHandler: nil)
            }
```
but now I need to add another condition in order to prevent opening url in safari after handling  deeplink. All the rest is fine, thanks!

**Comment by E-B-Smith** [comment]
Thanks for the heads up.  That seems like stupid oversight on my part that I'll fix promptly.

**Comment by E-B-Smith** [comment]
Are you using a custom domain?

**Comment by ADevelopStudio** [comment]
yep

**Comment by ADevelopStudio** [comment]
And everything is working fine after I changed from generated xxxx.app-link to my own, except this **.handleDeepLink(withNewSession: url) = false**

**Comment by E-B-Smith** [comment]
You need to add your custom domain to your Info.plist file.

Add the  `branch_universal_link_domains` key and for the value add the custom domain as a string.
