### ISSUE TITLE
Incorrect key format throws exception instead of logging an error

### ISSUE THREAD

**Issue by Niv1988** [BranchMetrics/ios-branch-deep-linking#715]
#642 introduces a major change in handling incorrect key format, instead of logging an error as before it now throws an exception.
This change is documented neither in the commit nor any of the release notes.

**Comment by E-B-Smith** [comment]
The intention is to catch key problems early, while the app is being developed.  How is this impacting you?

**Comment by Niv1988** [comment]
The undocumented change from logging to throwing exception caused our code to fail when using dummy strings for testing

**Comment by E-B-Smith** [comment]
For testing you can use the test key for your app, for in the Branch dash board.  It starts with 'key_test_'.  I try to document all changes but some escape me.
