### ISSUE TITLE
Compiler warning in BNCLog.h

### ISSUE THREAD

**Issue by crontab** [BranchMetrics/ios-branch-deep-linking#719]
https://github.com/BranchMetrics/ios-branch-deep-linking/blob/ecd48a58ed5c7c276bca66e01db0f3f581d4b636/Branch-SDK/Branch-SDK/BNCLog.h#L62

Minor but annoying. Disabling this warning is not an option when the framework is used via CocoaPods.

Returning `NSString *const` doesn't make sense in Objective-C even if you return a string literal, as (unlike C strings) the caller won't be able to modify it anyway.

**Comment by E-B-Smith** [comment]
What is the warning?

This returns a constant pointer to an NSString, so the pointer is constant.

**Comment by crontab** [comment]
@E-B-Smith 

` warning: 'const' type qualifier on return type has no effect`

There is absolutely no point in imposing const on the pointer (because it's returned by value) nor the NSString itself (as it's not mutable anyway). That's what the compiler is trying to say. Anyway this wouldn't be a big issue if it was fixable locally which with cocoapods it's not unfortunately.

**Comment by E-B-Smith** [comment]
Fixed in #720 to be merged next release.
