### ISSUE TITLE
Duplicated links in copied text (iOS 11)

### ISSUE THREAD

**Issue by jfsagasti** [BranchMetrics/ios-branch-deep-linking#726]
Hi! I've noticed that, in iOS 11, the copied text when sharing an item with the iOS share sheet, contains a duplicated link. Does anyone have this issue too? I am not experimenting this in iOS 10. I also updated branch library to latest SDK but still happening.  Thanks in advance.

**Comment by E-B-Smith** [comment]
You aren't the only one.

This seems to a change in behaviour in the way iOS 11 handles URL activity items: Copied activity items that are URLs are duplicated as text. 

If somebody knows why they would change this behaviour, please chime in.  It may be security related to prevent people clicking on deceptive URLs that have targets?

None the less, I'm working on a fix now and should have it in the next release, 0.19.x, shortly.

**Comment by E-B-Smith** [comment]
Fixed in release 0.19.5.
