### ISSUE TITLE
Crash in BNCPerformBlockOnMainThread

### ISSUE THREAD

**Issue by edenman** [BranchMetrics/ios-branch-deep-linking#728]
I haven't been able to repro this issue.
It has only happened to one of our users.
The user in question had it happen 16 times.

```
Hardware Model:     iPhone9,2
Version:            2.8.1
OS Version:         iOS 11.0

NSInvalidArgumentException: -[__NSDictionaryM length]: unrecognized selector sent to instance 0x1c4e3a8a0
0  CoreFoundation        ___exceptionPreprocess
1  libobjc.A.dylib       _objc_exception_throw
2  CoreFoundation        -[NSObject(NSObject) doesNotRecognizeSelector:]
3  CoreFoundation        ____forwarding___
4  CoreFoundation        ___forwarding_prep_0___
5  Branch                BNCPerformBlockOnMainThread
6  libdispatch.dylib     __dispatch_client_callout
7  libdispatch.dylib     __dispatch_sync_thread_bound_invoke
8  libdispatch.dylib     __dispatch_client_callout
9  libdispatch.dylib     __dispatch_main_queue_callback_4CF$VARIANT$mp
10 CoreFoundation        ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
11 CoreFoundation        ___CFRunLoopRun
12 CoreFoundation        _CFRunLoopRunSpecific
13 GraphicsServices      _GSEventRunModal
14 UIKit                 _UIApplicationMain
15 recharge-consumer-ios main (APIErrorsGenerated.swift:42:7)
16 libdyld.dylib         _start
```
I can't figure out what's happening here, but maybe you guys can?

**Comment by edenman** [comment]
Yeah, that's what I was afraid of.  9 times in a row, then 25min later, another 7 times in a row, then stopped.

**Comment by E-B-Smith** [comment]
That user really wanted to do what ever it was that crashed, which means your app is compelling, which is good. It's a bummer that the app crashed. Which is bad.

I would look in your deep link call back handler to see if there's a place where you assume a parameter is a string, or a sub-element of a dictionary is a string.

The somewhat good news is that I haven't had any reports of a crash like this, and the crash sounds isolated to a single user on your end, so it doesn't seem like a devastating bug.

**Comment by edenman** [comment]
Yeah, definitely not devastating.  FWIW:

```
		Branch.getInstance().initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { params, error in
			if error == nil && params != nil {
				DeepLinkRouter.onDeepLinkParamsReceived(params!)
			} else {
				DDLogError("Unable to register with Branch. Error: \(error.orNil)")
			}
		})
```
which farms out to
```
	static func onDeepLinkParamsReceived(_ params: [AnyHashable: Any]) {
		if let promoCodeToAutoAdd = params["code"] as? String {
			// add the promo code
		} else if let targetStr = params["target"] as? String, let target = BranchLinkTarget(rawValue: targetStr) {
			// go to the target section of the app
		}
	}
```
(where BranchLinkTarget is a string-based enum I've defined).  Anyway, I'll let you know if I figure out anything more, but for now I'm going to punt.  Thanks for the quick replies!

**Comment by E-B-Smith** [comment]
Nothing in this code seems suspicious to me either.

If you figure something out, or the problem recurs, please re-open this issue with more details.
