### ISSUE TITLE
Branch link lose parameters after second click

### ISSUE THREAD

**Issue by salah-ghanim** [BranchMetrics/ios-branch-deep-linking#729]
to reproduce:
1- create a link programatically and add a parameter ("foo":"bar")
2- send link via email , slack , whatsapp ...
3- Click link and install app from app store 
4- link parameters are read and are correct
5- close app, click link again.
EXP: param is still read (since link id is correct and its visible in branch portal).
OBS: link keeps value, but loses parameters in init callback

ENV: 
iOS: 11
Iphone 6s

**Comment by E-B-Smith** [comment]
Thanks for the report.  Let me investigate this.

**Comment by E-B-Smith** [comment]
I followed your steps and I don't see this.  I see the parameter I set (literally foo:bar) both times.

Are you maybe setting some other parameter that could be interfering with this?

I'm testing on iOS 11 iPhone 6 Plus.

**Comment by salah-ghanim** [comment]
There is no other parameters interfering, but maybe its useful to know that it happens when we use deepviews. 

so
 link click -> deep view -> App Store -> App Download -> Open App -> values are read.

second attempt:
   link click -> deep view -> Open App -> values are missing

**Comment by E-B-Smith** [comment]
Interesting, we haven’t seen this issue. 

Could you contact integrations@branch.io and we can have a support engineer look into this more deeply.

It would be super helpful if you include an example of a link that is failing in your email.
