### ISSUE TITLE
Multiple compiler warnings using Xcode 9 and Cocoapods version 1.3.1.

### ISSUE THREAD

**Issue by ebessilko** [BranchMetrics/ios-branch-deep-linking#733]
After installing Branch framework via CocoaPods, we see 21 compiler warnings.
There are all about availability problems, like: ***/Pods/Branch/Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m:553:39: 'setEligibleForSearch:' is only available on iOS 9.0 or newer.

Could you silence those warnings in an upcoming release?

Best regards.

[bugReport.txt](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1366818/bugReport.txt)

**Comment by E-B-Smith** [comment]
Thanks -- Will do.

**Comment by ebessilko** [comment]
The only Pods project's option that seems to be related with the warnings is CLANG_WARN_UNGUARDED_AVAILABILITY.
After updating CocoaPods to version 1.3.1 it might automatically be set to YES_AGGRESSIVE or YES.

**Comment by E-B-Smith** [comment]
I silenced the warnings in PR #735.  This will be available in version 0.20.x

**Comment by ebessilko** [comment]
Thanks 👍.
