### ISSUE TITLE
io.branch.sdk.error Code=1004, Trouble reaching the Branch servers

### ISSUE THREAD

**Issue by Sea-Eagle** [BranchMetrics/ios-branch-deep-linking#734]
Hi Team, from lastest Branch.io sdk , I'm facing below error when opening the app

**BNCServerInterface.m(569) Error: An error prevented request to https://api.branch.io/v1/open from completing: Error Domain=io.branch.sdk.error Code=1004 "Trouble reaching the Branch servers, please try again shortly." UserInfo={NSLocalizedFailureReason=The request timed out., NSLocalizedDescription=Trouble reaching the Branch servers, please try again shortly., NSUnderlyingError=0x1c4250830 {Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x1c0444590 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.branch.io/v1/open, NSErrorFailingURLKey=https://api.branch.io/v1/open, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}}}**

OS: iOS 11;

**Comment by E-B-Smith** [comment]
Are you connected to the internet when you open the app?  This error message is returned by the SDK when an internet connection is not available or extremely slow.

**Comment by baottran** [comment]
@E-B-Smith , what happens here when there's a bad internet connection? Does the Branch sdk still try to reconnect and listen for any deep links after or should we try to reinitialize it?

**Comment by E-B-Smith** [comment]
The SDK will try again later -- you don't need to re-initialize it.

**Comment by baottran** [comment]
do you know how long it takes to try again?

**Comment by E-B-Smith** [comment]
It is won’t try again until the app comes into the foreground again or another link is checked.

**Comment by flochtililoch** [comment]
Another reason why this message could show, is if the network your device is connected to is running a "global" ad-blocker (for example pi-hole) which blocks `api.branch.io` domain. I was consistently getting this message while my internet connection was still up and fast until I realized branch domain was being filtered.

**Comment by ashtrus** [comment]
I had this error as well, and solved it by disconnecting from VPN.
