### ISSUE TITLE
ld: framework not found FileProvider for architecture...

### ISSUE THREAD

**Issue by E-B-Smith** [BranchMetrics/ios-branch-deep-linking#739]
Frameworks built with Xcode 9 but used in Xcode 8 or lower may get a link error:

    `ld: framework not found FileProvider for architecture...`

The FileProvider.framework is an iOS 11 only framework, but it looks like Apple has accidentally made it required linking.
     
To get around this in pre-Xcode 9, copy the FileProvider.framework and the IOSurface.framework from Xcode 9 and place these frameworks in your project directory. Xcode will check the linking with them and continue building your project.

The frameworks are in the Xcode 9 directory:
`/Applications/Xcode-9.0.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks`

where `Xcode-9.0.1.app` is whatever you call your version of Xcode 9.

Again, these frameworks aren't used in iOS versions less than iOS 11, and the frameworks aren't copied to your executable.  But Xcode checks the linking anyway.

**Comment by parthkalavadia** [comment]
Thier is an alternate way to overcome this issue while installing SDK manually: https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/README.md#download-the-raw-files

**Comment by E-B-Smith** [comment]
Fixed in SDK version 0.21.11.
