### ISSUE TITLE
XCode 9 warnings fix

### ISSUE THREAD

**Issue by ivulyov90** [BranchMetrics/ios-branch-deep-linking#740]
It will be nice to fix warnings in Xcode 9.0.1

 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.h:14:49: 'CSSearchableItemAttributeSet' is partial: introduced in iOS 9.0
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:11:9: In file included from  Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:11:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreSpotlight.framework/Headers/CSSearchableItemAttributeSet.h:18:12: 'CSSearchableItemAttributeSet' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.h:14:12: Annotate 'BranchCSSearchableItemAttributeSet' with an availability attribute to silence
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:54:11: 'CSSearchableIndex' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreSpotlight.framework/Headers/CSSearchableIndex.h:29:12: 'CSSearchableIndex' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:54:11: Enclose 'CSSearchableIndex' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:138:23: 'setEligibleForSearch:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:91:45: 'setEligibleForSearch:' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:138:23: Enclose 'setEligibleForSearch:' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:139:23: 'setEligibleForPublicIndexing:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:94:53: 'setEligibleForPublicIndexing:' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:139:23: Enclose 'setEligibleForPublicIndexing:' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:140:23: 'setContentAttributeSet:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreSpotlight.framework/Headers/CSSearchableItemAttributeSet.h:84:58: 'setContentAttributeSet:' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:140:23: Enclose 'setContentAttributeSet:' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:142:23: 'setRequiredUserInfoKeys:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:44:47: 'setRequiredUserInfoKeys:' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:142:23: Enclose 'setRequiredUserInfoKeys:' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:143:23: 'setKeywords:' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserActivity.h:62:37: 'setKeywords:' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:143:23: Enclose 'setKeywords:' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:147:32: 'CSSearchableItem' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreSpotlight.framework/Headers/CSSearchableItem.h:35:12: 'CSSearchableItem' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:147:5: Enclose 'CSSearchableItem' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:147:32: 'CSSearchableItem' is only available on iOS 9.0 or newer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/CoreSpotlight.framework/Headers/CSSearchableItem.h:35:12: 'CSSearchableItem' has been explicitly marked partial here
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:147:32: Enclose 'CSSearchableItem' in an @available check to silence this warning
 Pods/Branch/Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m:148:7: 'CSSearchableIndex' is only available on iOS 9.0 or newer

**Comment by E-B-Smith** [comment]
I'll silence the warnings.

Are you using the class `BranchCSSearchableItemAttributeSet` in your project?
