### ISSUE TITLE
Branch.continueUserActivity always returns false

### ISSUE THREAD

**Issue by cornr** [BranchMetrics/ios-branch-deep-linking#758]
Hello. We are using the version 0.21.11 and experience problems when calling
`- (BOOL)continueUserActivity:(NSUserActivity *)userActivity;`
It always returns `false` for in my opinion proper deep links

Our expected behavior would be: it returns `true` iff eventually the DeepLinkHandler is called.
We need to know if the DeepLinkHandler will be called eventually to either route to "beginning" of the app or wait for the DeepLinkHandler in which we directly route to the expected VC.

Maybe its got something to do with it: We are using our own link domain.

Thanks for your help.
Jonas

**Comment by E-B-Smith** [comment]
Did you set `branch_universal_link_domains` in the info.plist file for your app? Check this out:

https://docs.branch.io/pages/deep-linking/universal-links/#return-yes-to-continueuseractivity

**Comment by cornr** [comment]
Yap. this solves the problem. Thanks.
If there is a hole section in the documentation dedicated to this method, then why is it not linked within the method documentation?
