### ISSUE TITLE
Branch synchronize method is blocking the main thread?

### ISSUE THREAD

**Issue by warpling** [BranchMetrics/ios-branch-deep-linking#759]
Version 0.21.11 running a debug build on tethered device the app often becomes unresponsive – pausing shows the PC here… 

Let me know if I can somehow provide more information. Good chance I'm reading this wrong.
<img width="1680" alt="screen shot 2017-12-01 at 5 49 15 pm" src="https://user-images.githubusercontent.com/220240/33510337-16e3a18e-d6c0-11e7-9737-318c5da76445.png">

**Comment by E-B-Smith** [comment]
What was thread 0 doing?

**Comment by E-B-Smith** [comment]
Can you show me the other threads too?

Were you calling the `getLatestReferringParamsSynchronous` method?

**Comment by warpling** [comment]
Hey @E-B-Smith, I was trying to recreate this over the weekend but couldn't :( Not sure what you mean by thread 0—afaik threads start at 1?

**Comment by E-B-Smith** [comment]
Sorry, I meant main thread and all the other threads.

The only blocking call in the Branch SDK is `getLatestReferringParamsSynchronous`. Maybe some other thread dependent thing happened that blocked unexpectedly.

I wonder if you weren't on slow / no network?  Also, do you have the link that was opened?

**Comment by warpling** [comment]
I don't think I was on a slow/no connection and I don't think a deep/UL link was even used? Only thing happening was checking for bucket rewards I'm pretty sure? Maybe it was a fluke thing related to something else I just got suspicious when I saw the sync call and some recent bug fixes…

**Comment by E-B-Smith** [comment]
Thanks -- Nothing has changed there lately.  But this gives me something to look out for.  I'll make sure to pay extra attention when testing that part of the code.

**Comment by warpling** [comment]
Totally, feel free to close for now! I'll re-open if I can trigger it again.

**Comment by warpling** [comment]
Just deployed a build to an iPhone 5s running 9.3.5 and experienced this again.
App completely hung, paused debugger…
<img width="1680" alt="screen shot 2017-12-20 at 3 05 16 pm" src="https://user-images.githubusercontent.com/220240/34232900-66e47790-e597-11e7-8234-746f629110e6.png">

**Comment by E-B-Smith** [comment]
Thanks for sending this along.  This stack trace includes more clues.  

If it happens again could you expand the `io.branch.sdk.network.queue`  so I can see that trace too?

The closest device I have is a 6s running 9.1.  I'll test with that.

**Comment by E-B-Smith** [comment]
Duh.  I see a thing.  I made a fix and pushed it to the github `beta` branch for you to test.

Here's info on using the Branch GitHub beta branch with CocoaPod or Carthage.

Let me now if this works for you.

**Comment by E-B-Smith** [comment]
Try the new release, version 0.22.3.
