### ISSUE TITLE
Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}

### ISSUE THREAD

**Issue by DarrenDuXuan** [BranchMetrics/ios-branch-deep-linking#760]
Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}

**Comment by DarrenDuXuan** [comment]
[branch.io] BNCServerInterface.m(586) Error: An error prevented request to https://api.branch.io/v1/open from completing: Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}

**Comment by DarrenDuXuan** [comment]
[branch.io] BNCNetworkService.m(219) Debug: Network finish operation https://api.branch.io/v1/open 0.233s. Status 400 error (null).
{"error":{"device_fingerprint_id":"doesn't pass regex","instrumentation":{}}}

**Comment by DarrenDuXuan** [comment]
😢 what should i do

**Comment by DarrenDuXuan** [comment]
I tried some times. and initSessionWithLaunchOptions not call back error code 1003 ...  and i don't know how to fix this bug

**Comment by E-B-Smith** [comment]
Sorry for your frustration!

It's a network error because some of the data passed sent to Branch is invalid.

What kind of device are you testing with? Also, if you could send more of the log messages are can help you diagnose this quicker.

**Comment by E-B-Smith** [comment]
Any more information on this?

**Comment by DarrenDuXuan** [comment]
[branch.io] BNCServerInterface.m(711) Debug: URL: https://api.branch.io/v1/open

**Comment by DarrenDuXuan** [comment]
[branch.io] BNCServerInterface.m(711) Debug: URL: https://api.branch.io/v1/open
[branch.io] BNCServerInterface.m(715) Debug: Body: {
    "ad_tracking_enabled" = 0;
    "app_version" = "6.1.5";
    "apple_ad_attribution_checked" = 0;
    "branch_key" = "key_live_lmunGYUOO1rmGaZJTaaABolbvwb7AHp2";
    brand = Apple;
    cd =     {
        mv = "-1";
        pn = "com.quvideo.XiaoYing";
    };
    country = CN;
    debug = 1;
    "device_fingerprint_id" = b4528bf3813a8b9c477df4d7a9cca19a;
    "facebook_app_link_checked" = 0;
    "hardware_id" = "71A7A2E0-7A1A-432D-B37A-BDBDB79015D1";
    "hardware_id_type" = random;
    "identity_id" = 4198266199867562;
    "ios_bundle_id" = "com.quvideo.XiaoYing";
    "ios_vendor_id" = "9EDFE639-F8D8-4555-8BAD-0038103AA2AE";
    "is_hardware_id_real" = 0;
    language = zh;
    "local_ip" = "10.64.105.102";
    model = "iPhone8,1";
    os = iOS;
    "os_version" = "10.3.3";
    retryNumber = 0;
    "screen_height" = 1334;
    "screen_width" = 750;
    sdk = "ios0.21.13";
    update = 1;
    "uri_scheme" = "twitterkit-iCp3xDuXGZCzRLq3fzqX79vPf";
    "user_agent" = "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60";
}
JSON: {"sdk":"ios0.21.13","facebook_app_link_checked":false,"language":"zh","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60","screen_height":1334,"country":"CN","app_version":"6.1.5","update":1,"ad_tracking_enabled":false,"brand":"Apple","retryNumber":0,"uri_scheme":"twitterkit-iCp3xDuXGZCzRLq3fzqX79vPf","identity_id":"4198266199867562","os":"iOS","local_ip":"10.64.105.102","hardware_id":"71A7A2E0-7A1A-432D-B37A-BDBDB79015D1","screen_width":750,"cd":{"pn":"com.quvideo.XiaoYing","mv":"-1"},"ios_vendor_id":"9EDFE639-F8D8-4555-8BAD-0038103AA2AE","ios_bundle_id":"com.quvideo.XiaoYing","hardware_id_type":"random","debug":true,"os_version":"10.3.3","is_hardware_id_real":false,"model":"iPhone8,1","branch_key":"key_live_lmunGYUOO1rmGaZJTaaABolbvwb7AHp2","device_fingerprint_id":"b4528bf3813a8b9c477df4d7a9cca19a","apple_ad_attribution_checked":false}.
2017-12-06 20:30:31.449657+0800 XiaoYing[7628:2782483] [branch.io] BNCNetworkService.m(223) Debug: Network start operation https://api.branch.io/v1/open.
2017-12-06 20:30:31.504109+0800 XiaoYing[7628:2782329] {"hotfix":0,"gotoFeedOrDetail":1,"allowUploadAndDownloadWithoutWifi":1,"videoDownloadSwitch":1,"AutoPlaySettingType":2,"isFeedorGridHot":1,"SWITCHER_DIGIT_WMARK":1,"silentMode":0,"DefaultCommunityTab":2,"httpslock":0,"rateDialog":1}

**Comment by DarrenDuXuan** [comment]
and [branch.io] BNCNetworkService.m(219) Debug: Network finish operation https://api.branch.io/v1/open 0.948s. Status 400 error (null).
{"error":{"device_fingerprint_id":"doesn't pass regex"}}

[branch.io] BNCServerInterface.m(771) Debug: Server returned: Status: 400; Data: {
    error =     {
        "device_fingerprint_id" = "doesn't pass regex";
    };
}.

**Comment by DarrenDuXuan** [comment]
all information in debug model

**Comment by E-B-Smith** [comment]
Try removing the app from your phone and then re-running it.

It looks like some test parameters or bad parameters were saved to your phone.  Removing the app from your phone should clear them.

Let me know if this solves your problem.

**Comment by DarrenDuXuan** [comment]
I tried renoving my app and re-running ten 
no error

**Comment by DarrenDuXuan** [comment]
@E-B-Smith  I tried removing my app and re-running ten
no error

**Comment by DarrenDuXuan** [comment]
@E-B-Smith  but when i close my app and re-open it 
has error Code=1003

**Comment by E-B-Smith** [comment]
Are you switching between production / test mode between runs? By changing the Branch key or setting `[Branch.setUseTestBranchKey:YES]`?

Or changing the app version?

**Comment by DarrenDuXuan** [comment]
![image](https://user-images.githubusercontent.com/15886912/33985383-65967a88-e0f5-11e7-98c9-f68211f24250.png)
this is all branch code no setUseTestBranchKey
and i check app id is right

**Comment by E-B-Smith** [comment]
The `device_fingerprint_id` that is being sent is definitely wrong. Let's figure out how that happened.

Can your re-install the app on the device and send me the logs?

* Remove the app from the device.
* Make sure that Branch logging is turned on.
* Run the app from Xcode.
* Send me or post the Xcode log output.

I can see that in general your app is getting Branch installs and opens on our system.  It seems to be this particular device.

**Comment by DarrenDuXuan** [comment]
@E-B-Smith 
[branchLog.txt](https://github.com/BranchMetrics/ios-branch-deep-linking/files/1581245/branchLog.txt)
There are first install app all branch logs

**Comment by E-B-Smith** [comment]
LinkedMe and Branch can't be used in the same app.  They use our SDK code as part of their SDK, so it interferes with the way Branch normally runs.

**Comment by DarrenDuXuan** [comment]
@E-B-Smith okay!!!  THX!!

**Comment by jhipkisshex** [comment]
I get a similar issue with [branch.io] BNCNetworkService.m(202) Debug: Network finish operation https://api.branch.io/v1/open 0.195s. Status 200 error (null).

The API call returns the data I'm looking for but doesn't populate to the listeners.

BranchSDK version: 2.1.2
capacitor-branch-deep-links version: 5.0.0
