### ISSUE TITLE
Update docs example for contentMetadata.customMetadata

### ISSUE THREAD

**Issue by petemillermultimedia** [BranchMetrics/ios-branch-deep-linking#761]
I see a warning that BranchUniversalObject.addMetadataKey is deprecated, and it appears that the correct way to do it is with

myBranchObject.contentMetadata.customMetadata["key"] = value

but the example on the main page still shows addMetadatakey. I can validate this change in my code with trial and error, but the example could be updated.

**Comment by E-B-Smith** [comment]
Thanks for the heads up! 

I'm updating the README.md and some of the other docs now.

**Comment by E-B-Smith** [comment]
See PR #762 .

**Comment by E-B-Smith** [comment]
Merged to master.
