### ISSUE TITLE
Unable to use continueUserActivity inside a Swift extension

### ISSUE THREAD

**Issue by OhadMaor-VIA** [BranchMetrics/ios-branch-deep-linking#765]
When using Swift `extension Branch {...}` and trying to invoke `continueUserActivity` inside an extension custom method, Swift doesn't recognise `continueUserActivity` as a method but as a `continue` when using inside a loop.

![screen shot 2017-12-12 at 16 37 15](https://user-images.githubusercontent.com/34231750/33890047-be88cb56-df5a-11e7-8525-7e7d58e9e773.png)

**Comment by E-B-Smith** [comment]
Try adding `self` to `continue`, like this:

```
extension Branch {
    func myHandleDeepLink() {
        let ua = NSUserActivity.init(activityType: NSUserActivityTypeBrowsingWeb)
        ua.webpageURL = URL.init(string: "https://myapp.app.link")
        self.continue(ua)
    }
}
```

Also, if you simply want to open a Branch URL in a new session, you can use `handleDeepLinkWithNewSession`, which is a little more clear with what is happening:

```
extension Branch {
    func myHandleDeepLink2() {
        let url = URL.init(string: "https://myapp.app.link")
        handleDeepLink(withNewSession: url)
    }
}
```
