### ISSUE TITLE
The first short url trouble

### ISSUE THREAD

**Issue by alexanderkhitev** [BranchMetrics/ios-branch-deep-linking#777]
Hello! There is a problem in getting shortURL, it manifests with new users during the first short url reception or after updating the application in the App Store or Test Flight.

The link looks something like this

https://myapp.app.link?$identity_id=486299017484100364&feature=sharing&type=0&duration=0&source=ios&data=eyJldmVudElEIjoiNDE5ODAzMTkyNjVpdGNoY2ZW50YnJpdGUiLCJ0aW1lc3RhbXAiOiIxNTE3NzI0MDAwLjAiLCJzZXJ2aWNlSUQiOiI0MTk4MDMxOTI2NSIsImNyZWF0b3JUelSW5kZXgiOiIxIiwidHlwZSI6InNoYXJlQ2FyZCIsImRlZXBMlYXRpb25UaW1lc3RhbXAiOiIxNTE3MTgwOTgxLjk1MjA5IiwiJG9nX2ltYWdlX3VybCI6Imh0dHBzOi8vaW1nLmV2YnVjLmNvbS9odHRwcyUzQSUyRiUyRmNkbi5ldmJ1Yy5jb20lMkZpbWFnZXMlMkYzOTM2ODEzNCUyRjIyODcwOTg5ODQwNiUyRjElMkZvcmlnaW5hbC5qcGc/cz00N2M5ZTRiYTNjZTg5ZjgxN2ZhYjE1ZjM3NjYzNGI0YSIsInNlcnZpY2VJbmRleCI6IjIiLCIkY2Fub25pY2FsX2lkZW50aWZpZXIiOiJjYXJkSWQvNDE5ODAzMTkyNjVpdGNoYWJsZWV2ZW50YnJpdGUiLCIkZGVza3RvcF91cmwiOiJodHRwOi8vd3d3Lml0Y2hhYmxlLmNvbSIsImlzRmxleFRpbWUiOiJmYWxzZSIsImN1cnJlbnRCcmFuY2hNb2RlbFZlcnNpbOiIyIiwiJG9nX3RpdGxlIjoiQmxhY2sgVG8gVGhlIEZ1dHVyZSAoQmxhY2sgSGlzdG9yeSBNb250aCBQYXJ0eSkgLSBGUkVFIFdJVEggUlNWUCJ9

All other links except the first have a "standard" view. For example

https://myapp.app.link/VlddI01p5q

**Comment by E-B-Smith** [comment]
The long form of Branch links are generated by the SDK if a short link can't be generated. It takes a trip to the server to generate a short link, so if the network call times out the short link can't be generated and a long link is used instead. 

Is the Branch SDK initialized (best to do this as soon as possible at app in your `application: didFinishLaunchingWithOptions:` method) and the network available when the links are generated?

Also, if an alias is used to generate the short link, and that alias is already used, a long link is generated.

I tested this a couple times by installing a fresh application to make sure that the SDK wasn't doing something weird when generating a short link.  Short links were generated as expected the first time, everytime.

Maybe something else is going on?

**Comment by E-B-Smith** [comment]
Reopen this if you're still having trouble.
