### ISSUE TITLE
Allow static library usage from Cocoapods

### ISSUE THREAD

**Issue by bridger** [BranchMetrics/ios-branch-deep-linking#782]
Version [1.4.0 of Cocoapods](http://blog.cocoapods.org/CocoaPods-1.4.0/) allows a pod to be used as a static library, even in a Swift app. It requires the library's podspec to contain `s.static_framework = true`.

I believe this will help apps launch faster. Here's a blog post that explains why too many dynamic frameworks slows down launch: https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea

**Comment by E-B-Smith** [comment]
Great -- I'll look into this.  Our framework already can be built as a static library or a dynamic library.  If it's just a matter of adding the switch it'll be super easy. 

I want to make sure it doesn't screw up the dynamic framework people though.

**Comment by E-B-Smith** [comment]
This should be possible now!  Let me know if it doesn't work for you.

**Comment by bridger** [comment]
Thank you!
