### ISSUE TITLE
Crash on setIdentity() "NSNumber isEqualToString"Identity_ID from server parsed to NSNumber not to NSString 

### ISSUE THREAD

**Issue by altairdeark** [BranchMetrics/ios-branch-deep-linking#783]
We experienced next crash in BNCPreferenceHelper.m, 255 line.
```
...
- (void)setIdentityID:(NSString *)identityID {
if (![_identityID isEqualToString:identityID]) {
        _identityID = identityID;
        [self writeObjectToDefaults:BRANCH_PREFS_KEY_IDENTITY_ID value:identityID];
    }
}
...
```

Response from server on setIdentity(), parse **identity_ID** to **(long) NSNumber** not to **NSString**
it will cause crash after reset Identity

We are not sure if it is a problem in pod, because Server response JSON not string either.

```
2018-02-12 14:21:54.337003+0700 [2950:899990] XXXXX [branch.io] BNCServerInterface.m(771) Debug: Server returned: Status: 200; Data: {
    "identity_id" = 4000001000300;
    link = "https://xxxxxxxx.test-app.link/?%24identity_id=4000001000300";
    "session_id" = 491496367546784300;
}
```

**Comment by altairdeark** [comment]
Currently we fixed it by adding additional condition into **setIdentity** function, but it is not a great solution.

```
- (void)setUserIdentity:(NSString *)userIdentity {
    NSString *stringIdentity;
    
    if ([userIdentity isKindOfClass:[NSNumber alloc]]) {
        NSNumber *numberIdentity = userIdentity;
        stringIdentity = [numberIdentity stringValue];
    } else {
        stringIdentity = userIdentity;
    }
    
    if ([_identityID isKindOfClass:[NSNumber alloc]]) {
        NSNumber *_numberIdentity = _identityID;
        _identityID = [_numberIdentity stringValue];
    }
    
    if (![_userIdentity isEqualToString:stringIdentity]) {
        _userIdentity = stringIdentity;
        [self writeObjectToDefaults:BRANCH_PREFS_KEY_IDENTITY value:stringIdentity];
    }
}


```

Our proposal is to map JSONResponse from server into explicit NSString were it needed. In BranchSetIdentityRequest.m, 46 line. 

```
- (void)processResponse:(BNCServerResponse *)response error:(NSError *)error {
    if (error) {
        if (self.callback && self.shouldCallCallback) {
            self.callback([[NSDictionary alloc] init], error);
        }
        
        self.shouldCallCallback = NO; // don't call the callback next time around
        return;
    }
    
    BNCPreferenceHelper *preferenceHelper = [BNCPreferenceHelper preferenceHelper];
    **preferenceHelper.identityID = response.data[BRANCH_RESPONSE_KEY_BRANCH_IDENTITY];**
    preferenceHelper.userUrl = response.data[BRANCH_RESPONSE_KEY_USER_URL];
    preferenceHelper.userIdentity = self.userId;
    if (response.data[BRANCH_RESPONSE_KEY_SESSION_ID]) {
        preferenceHelper.sessionID = response.data[BRANCH_RESPONSE_KEY_SESSION_ID];
    }
  
    if (response.data[BRANCH_RESPONSE_KEY_INSTALL_PARAMS]) {
        preferenceHelper.installParams = response.data[BRANCH_RESPONSE_KEY_INSTALL_PARAMS];
    }
    
    if (self.callback && self.shouldCallCallback) {
        NSString *storedParams = preferenceHelper.installParams;
        NSDictionary *installParams = [BNCEncodingUtils decodeJsonStringToDictionary:storedParams];
        self.callback(installParams, nil);
    }
}
```

**Comment by E-B-Smith** [comment]
Sorry to hear about your crash!  I'll make a fix that will do better type checking and let you know when the update is available.

Also, I'll make sure that we haven't changed something on the back end that would cause this.

In the mean time, you should change the lines:

```
if ([userIdentity isKindOfClass:[NSNumber alloc]]) {
```

to 

```
if ([userIdentity isKindOfClass:[NSNumber class]]) {
```

**Comment by altairdeark** [comment]
Hi @E-B-Smith, thanks for quick response. 
My apologise, were copied `alloc` by a mistake from buffer.

Waiting for fix

**Comment by E-B-Smith** [comment]
I put in a check for this in this PR:  #785 

But I am still wondering how our backend is sending you a non-string.

Do you have any custom Branch integrations? Maybe a server-to-server integration or web-hook?

What other SDKs are you using?

**Comment by altairdeark** [comment]
Yes, we use web-hooks to generate links and it looks like we were setting identity as a **Number** not a **String**, however branch server did not decline such requests as incorrect. 

May be you are using database without strong type checks? like mongo or else.

Thanks for quick update and merge request. 
But you fixed client side, we think the main problem is on server side. 
Also it will only affect identity field, same problem can be caused by any other fields, which type are not explicitly set on server side.

In any case we are waiting merge of #785, it will fix problem for now and we will check one more time our web-hooks

**Comment by altairdeark** [comment]
## Updates

We fix our web-hooks, however it does not fix the problem even for new users.

**Comment by E-B-Smith** [comment]
Thanks for your great feedback.  I have a client patch, and we are working on a server side fix too so that existing users won't crash as well.

@snakingfire

**Comment by E-B-Smith** [comment]
Both the SDK and the Branch back end are fixed for this now.  Let me know if you have any other issues.
