### ISSUE TITLE
initSession not called on app launch - Swift 

### ISSUE THREAD

**Issue by ranhsd** [BranchMetrics/ios-branch-deep-linking#790]
Hi, 
the **initSession** function is not triggered on app launch. If I move the app to background and then return to foreground everything works as excepted but If I am killing the app and then launch it from a deep link the initSession is not getting called. 

This is my code: 

```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
        
        let branch = Branch.getInstance()

        branch?.initSession(launchOptions: launchOptions) { (branchUniversalObject, branchLinkProperties, error) in

            DispatchQueue.main.async {
                store.dispatch(PresentGenericMessage(title: nil, message: "some message"))
            }

            if error != nil {

                return
            }
        }

        return true

        
    } 


    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        
        let branchHandled = Branch.getInstance().application(app, open: url, options: options)
        return branchHandled
        
    }
    
    
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
        return Branch.getInstance().continue(userActivity)
    }
```

**Comment by ranhsd** [comment]
Somebody can assist here? Maybe @E-B-Smith ?

Thanks.

**Comment by E-B-Smith** [comment]
Sorry to hear about your troubles. It looks like your code is right so it's probably something in your configuration.

Make sure your deep link domain is set up right in your projects capabilities section:
https://docs.branch.io/pages/apps/ios/#configure-associated-domains

And that your `URL type` is set up in your Info.plist file.
https://docs.branch.io/pages/apps/ios/#configure-infoplist

Also, make sure your app is configured in the Branch dashboard too.
https://dashboard.branch.io

Check out the WebViewExample in `Examples/WebViewExample` for a working Swift example. Maybe something in the example will help.

Can you share the link that doesn't work for you?

**Comment by E-B-Smith** [comment]
Also, with what version of iOS are you having problems?

**Comment by ranhsd** [comment]
Hi @E-B-Smith thanks for your answer. It is not working on iOS 11 (I didn't tested it on iOS 10 yet). I did all the configurations because the link itself is working the only thing that doesn't work is that **initWithSession** callback is not triggered **only when the app is launched** from the deep link and the app is not running in background

**Comment by ranhsd** [comment]
Hi @E-B-Smith I found the problem. I was returned **false** from **willFinishLaunchingWithOptions** so it's mandatory to return **true**  from both **willFinishLaunchingWithOptions** and **didFinishLaunchingWithOptions**

**Comment by E-B-Smith** [comment]
Dang -- That trips me up too sometimes.  Good catch.

**Comment by ranhsd** [comment]
Thank you for your quick response (as always) I really think your service is awesome.
