### ISSUE TITLE
Sharing deep link through Skype acts as if you clicked it

### ISSUE THREAD

**Issue by alaraKalama** [BranchMetrics/ios-branch-deep-linking#793]
When you create BranchUniversalObject and share it with Skype, minimise the app and then reopen it again the +clicked_branch_link parameter is true and the app acts as you clicked a deep link.

I am setting imageUrl, title, contentDescription and custom metadata key to the universal object, its contentIndexMode is set to private, I am also adding BranchLinkProperties with emailSubject, desktopUrl and custom timestamp of the time of sharing as control params.
Interestingly when I add control params for $ios_deepview the problem disappears. Which is okay if you want deepviews but not really cool if you don't.
I am able to reproduce it on iOS 11 and 10.

**Comment by E-B-Smith** [comment]
I'll get Skype on my phone and check this out!

**Comment by E-B-Smith** [comment]
I played around with sharing a Branch app link in Skype but didn't see this issue.

Can you list the exact steps you used to reproduce this?

**Comment by alaraKalama** [comment]
1. I am creating BranchUniversalObject with canonicalIdentifier "content/\(id)"
2. I am setting values for imageUrl, title, contentDescription and contentIndexMode is set to private. Also adding metadata key with custom key and value
3. I am creating BranchLinkProperties with 3 control parameters - "$desktop_url", "$email_subject" and custom share timestamp. 
4. I am calling the showShareSheet method on the object with the created link properties and share text
5. I am sharing the link through Skype app and it is shared successfully 
6. I minimise the app that I just shared the link with and open it again without opening Skype or any other app
7.  The parameters in the completion of initSession method have the payload of this last link I created, the +clicked_branch_link value is 1

**Comment by E-B-Smith** [comment]
I was able to reproduce this with the right combination of Branch dashboard settings.

I made a fix for this that should be out soon. See PR #811 , Skype sharing.

**Comment by E-B-Smith** [comment]
This is fixed in version 0.23.5.

**Comment by lalu5585** [comment]
Hello E-B-Smith,

seems this issue reproduced again in version 0.25.3.

let buo = BranchUniversalObject.init(canonicalIdentifier: "content/12345")
        buo.title = "abc"
        buo.contentDescription = "xyz"
        buo.imageUrl = "abc.com"
        buo.contentMetadata.customMetadata["Groupid"] = "\((dialog.id)!)"
        buo.contentMetadata.customMetadata["AdminMobile"] = "\(self.adminPhone)"
        buo.contentMetadata.customMetadata["type"] = "Invite"
        let lp: BranchLinkProperties = BranchLinkProperties()
        buo.getShortUrl(with: lp) { (url, error) in}

the same thing happens, 

but I have noticed that first time it generates share link with Alternate Link Domain, and the second time it generates share link with a Default Link Domain which has added. the third time its work fine.

"~referring_link": https://share-xyz-alternate.app.link/0cVwsL9TDU?
"~referring_link": https://share-xyz.app.link/0cVwsL9TDU,


I am not sure what is wrong. can you please help me with this.

Thanks
