### ISSUE TITLE
Conflicting return type in declaration of 'new'

### ISSUE THREAD

**Issue by jimmyktf** [BranchMetrics/ios-branch-deep-linking#795]
We are getting the static analyzer warning

Branch/Branch-SDK/Branch-SDK/Networking/BNCNetworkService.h:36:1: Conflicting return type in declaration of 'new': 'instancetype' (aka 'id') vs 'id<BNCNetworkServiceProtocol>'

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/02394ce83dc419bac02c9877d9f0ce9a3c7515f3/Branch-SDK/Branch-SDK/Networking/BNCNetworkService.h#L36

**Comment by E-B-Smith** [comment]
Fixed in #792 .

**Comment by E-B-Smith** [comment]
Updated in version 0.23.4.
