### ISSUE TITLE
Conflicting parameter types

### ISSUE THREAD

**Issue by jimmyktf** [BranchMetrics/ios-branch-deep-linking#796]
We are getting the static analyzer warning

Branch/Branch-SDK/Branch-SDK/Networking/BNCNetworkService.h:41:98: Conflicting parameter types in declaration of 'networkOperationWithURLRequest:completion:': 'void (^__strong)(__strong id<BNCNetworkOperationProtocol>)' vs 'void (^__strong)(BNCNetworkOperation *__strong)'

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/02394ce83dc419bac02c9877d9f0ce9a3c7515f3/Branch-SDK/Branch-SDK/Networking/BNCNetworkService.h#L40

**Comment by E-B-Smith** [comment]
Thanks for reporting this -- I'll make the change.

Which version of Xcode / code analyzer warnings do you have set?  I set all of them and I don't see this warning.  I want to keep the code free of warnings.

**Comment by E-B-Smith** [comment]
Fixed in PR #792 .

**Comment by E-B-Smith** [comment]
Updated in version 0.23.4.
