### ISSUE TITLE
Possible Memory leak while profiling BareBones project

### ISSUE THREAD

**Issue by deepshah7** [BranchMetrics/ios-branch-deep-linking#797]
Hello There,

I was evaluating branch before integrating it into our app. I was profiling the BareBones (iOS) example from Branch. I observed that when the application loads it leaks memory (around 2.3kb). 

Do we know anything about this? Am I missing something?

Instruments shows that there might be a cycle in the code and because of that the leak is happening (PFA the screenshot of the cycle).

<img width="411" alt="screen shot 2018-03-13 at 08 38 19" src="https://user-images.githubusercontent.com/254086/37325057-2f60d3d4-26b2-11e8-9ad9-ded69221af3c.png">

**Comment by deepshah7** [comment]
#798 This is the pull request I have created it seems to be solving the problem, however I am not sure if its the right fix.

**Comment by E-B-Smith** [comment]
Great catch --  Thanks!  I'll merge this in the next release, sometime in the next week.

**Comment by E-B-Smith** [comment]
Look at this PR, #802 , HandleNetwork Deallocation.

I added the code to break the retain cycles, but only when we're really done with the network session.

**Comment by E-B-Smith** [comment]
Updated in 0.23.4

**Comment by deepshah7** [comment]
I did try to profile the BareBones project with the fix and it does seem to fix the leak. Thanks!
