### ISSUE TITLE
Share Sheet doesn't allow to use own BranchActivityItemProviderDelegate

### ISSUE THREAD

**Issue by michalcichon** [BranchMetrics/ios-branch-deep-linking#804]
I would like to map `channel` attribute when I use `showShareSheet` on `BranchUniversalObject` but I am not allow to do it because `showShareSheetWithLinkProperties:andShareText:fromViewController:completion:` method cannot pass `delegate`. The method on the bottom creates item providers using this:

```
UIActivityItemProvider *itemProvider = [self getBranchActivityItemWithLinkProperties:linkProperties];
```

And it uses the following method with a `nil`ed `delegate`:

```
+ (BranchActivityItemProvider *)getBranchActivityItemWithParams:(NSDictionary *)params feature:(NSString *)feature stage:(NSString *)stage campaign:(NSString *)campaign tags:(NSArray *)tags alias:(NSString *)alias {
    return [[BranchActivityItemProvider alloc] initWithParams:params tags:tags feature:feature stage:stage campaign:campaign alias:alias delegate:nil];
}
```

BTW. There is no `getBranchActivityItemWithParams` method that set not-nil value to every parameter of `BranchActivityItemProvider` init.

**Comment by E-B-Smith** [comment]
You should use a `BranchShareLink` object, which is a newer and better way to share Branch objects.

You can set a delegate on the `BranchShareLink` and the delegate object will be called back so your app can override link settings like channel or the sharing text based on the activity that the user selects.

Here's some example code:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed/Branch-TestBed/ViewController.m#L342-L365

Be sure to set the delegate:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed/Branch-TestBed/ViewController.m#L303

Here's an example of the delegate methods. Both are optional:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-TestBed/Branch-TestBed/ViewController.m#L342-L365

You can post any questions about this here.

**Comment by E-B-Smith** [comment]
If you have questions about this you can reopen the issue and I'll be glad to help.
