### ISSUE TITLE
Branch Deep Link issue - on launch from deeplink url

### ISSUE THREAD

**Issue by fevicks** [BranchMetrics/ios-branch-deep-linking#806]
Always not getting the deeplink parameters - if app is killed & open from deep link - some times works randomly. If the app is in background i can get the parameters, please check the below code

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        _ = ShoppingViewController(nibName: nil, bundle: nil)
        
        let googleMapsApiKey = BuildSettingKeys.googleAPIKey.value
        GMSServices.provideAPIKey(googleMapsApiKey)
        
        setSemantic()
        
        IQKeyboardManager.sharedManager().enable = true
        
        
        UITabBar.appearance().tintColor = UIColor.magadeerGreen()
        UITabBarItem.appearance().setTitleTextAttributes([NSFontAttributeName: UIFont.magadeerRegular(fontSize: 10)], for: .normal)
        
        
        self.showRootViewControllerBasedOnCondition()
        
        Fabric.with([Crashlytics.self])
        
        Thread.sleep(forTimeInterval: 2)
        
        
        //FirebaseApp.configure()
        let filePath = Bundle.main.path(forResource: BuildSettingKeys.firebaseGoogleServiceInfoPlist.value, ofType: "plist")
        if let options = FirebaseOptions.init(contentsOfFile: filePath!){
            FirebaseApp.configure(options: options)
        }else{
            assert(false, "Couldn't load config file")
        }
        
        //MARK: - For Pushnotification
        if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
            // For iOS 10 data message (sent via FCM
            Messaging.messaging().delegate = self
        } else {
            let settings: UIUserNotificationSettings =
                UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            application.registerUserNotificationSettings(settings)
        }
        
        application.registerForRemoteNotifications()
        
        //https://github.com/BranchMetrics/Branch-Integration-Guides/blob/master/ios-quickstart.md
        //https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/
        //let branch: Branch = Branch.getInstance()
        
        var branch: Branch!
        
        let aqarType = BuildSettingKeys.deploymentType.value
        if aqarType == "STAGING"{
            branch = Branch.getTestInstance()
            //Branch.setUseTestBranchKey(true)
            branch.setDebug() ///////// added for Link test - open the app
        }else{ // RELEASE
            branch = Branch.getInstance()
        }
        
        /*Branch.getInstance()*/branch.initSession(launchOptions: nil, automaticallyDisplayDeepLinkController: false) { (params, error) in
            if error == nil && (params!["recipe_id"] != nil){
                print("Recipe Id = \(params!["recipe_id"]!)")
                self.showRecipeDetails(recipeId: params!["recipe_id"]! as! Int)
                // Navigate to Recipe Details
                self.showErrorAlert(message: "1111 =\(params!)")
            } else {
                //                let branch11 = Branch.getInstance()
                //                let params11 = branch11?.getLatestReferringParams() as? [String : Any]
                self.showErrorAlert(message: "2222 == \(params!)")
                
                //                self.showErrorAlert(message: "222 = \(params!)")
            }
        }

        Branch.getInstance().continue(userActivity);
        
        return true
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        
        var branch: Branch!
        
        let aqarType = BuildSettingKeys.deploymentType.value
        if aqarType == "STAGING"{
            branch = Branch.getTestInstance()
            //Branch.setUseTestBranchKey(true)
            branch.setDebug() ///////// added for Link test - open the app
        }else{ // RELEASE
            branch = Branch.getInstance()
        }
        /*Branch.getInstance()*/branch.initSession(launchOptions: nil, automaticallyDisplayDeepLinkController: false) { (params, error) in
            if error == nil && (params!["recipe_id"] != nil){
                print("Recipe Id = \(params!["recipe_id"]!)")
                self.showRecipeDetails(recipeId: params!["recipe_id"]! as! Int)
                // Navigate to Recipe Details
                self.showErrorAlert(message: "3333 =\(params!)")
            } else {
                self.showErrorAlert(message: "4444 == error = \(error) \(params!)")
                
                //                self.showErrorAlert(message: "222 = \(params!)")
            }
        }
        
        
        return true
    }
    
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
        // handler for Universal Links
        Branch.getInstance().continue(userActivity)
        return true
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        // handler for Push Notifications
        Branch.getInstance().handlePushNotification(userInfo)
    }

    
    internal func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        
        // pass the url to the handle deep link call
        Branch.getInstance().handleDeepLink(url);
        
        return true
    }
    
    // Respond to Universal Links
    func application(application: UIApplication, continueUserActivity userActivity: NSUserActivity, restorationHandler: ([AnyObject]?) -> Void) -> Bool {
        // pass the url to the handle deep link call
        Branch.getInstance().continue(userActivity);

        return true
    }

**Comment by E-B-Smith** [comment]
Try moving your `branch.initSession` to right after `Fabric.with([Crashlytics.self])` and before `Thread.sleep`.

Just curious: Why do you call `Thread.sleep` in your `didFinishLaunchingWithOptions` method? If you take too long in that method iOS will kill your app sometimes.

**Comment by fevicks** [comment]
@E-B-Smith Thanks for your response. The issue was - i was declered initSession in both **"didFinishLaunchingWithOptions & application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool"**

i removed it from  **didFinishLaunchingWithOptions**, now its working fine

Regarding Thread.sleep - we need to show the splash screen for 2 second as the requirement.
