### ISSUE TITLE
I found that sharing to facebook and twritter always fails on ios11

### ISSUE THREAD

**Issue by yanganggithub** [BranchMetrics/ios-branch-deep-linking#812]
SLComposeViewController dealloc <SLComposeViewController: 0x121d5dc40>
Link sharing cancelled

**Comment by E-B-Smith** [comment]
I've tried this and it works without crashing for me.
Can you add more details or maybe a code snippet of what you're doing?

**Comment by yanganggithub** [comment]
let branchUniversalObject: BranchUniversalObject = BranchUniversalObject(canonicalIdentifier: "monster/12345")
branchUniversalObject.title = "Meet Mr. Squiggles"
branchUniversalObject.contentDescription = "Your friend Josh has invited you to meet his awesome monster, Mr. Squiggles!"
branchUniversalObject.imageUrl = "https://example.com/monster-pic-12345.png"
branchUniversalObject.contentMetadata.customMetadata = ["custom":"123"]
branchUniversalObject.contentMetadata.customMetadata = ["anything":"everything"]

let linkProperties: BranchLinkProperties = BranchLinkProperties()
linkProperties.feature = "share"
linkProperties.channel = "facebook"

branchUniversalObject.showShareSheet(with: linkProperties,
                                     andShareText: "Super amazing thing I want to share!",
                                     from: self) { (activityType, completed) in
    if (completed) {
        print(String(format: "Completed sharing to %@", activityType!))
    } else {
        print("Link sharing cancelled")
    }
}



I wrote in the UIViewController, the interface can evoke, click to share directly to the facebook console error, and then nothing happens, but in ios9 can be success, I'm in China, but it's over the wall

**Comment by yanganggithub** [comment]
kumu[8680:3007748] [core] SLComposeViewController initWithExtension: <NSExtension: 0x13546f960> {id = com.apple.share.Facebook.post} requestedServiceType: com.apple.social.facebook
2018-03-30 16:49:26.235819+0800 kumu[8680:3007748] [core] SLComposeViewController dealloc <SLComposeViewController: 0x1356421e0>
Link sharing cancelled

**Comment by E-B-Smith** [comment]
Try this example of sharing a Branch link:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Examples/WebViewExample/WebViewExample/ArticleViewController.swift#L93-L103

**Comment by E-B-Smith** [comment]
I hope this helped.  If you have any questions please re-open this issue and ask.
