### ISSUE TITLE
build warnings with XCode9.3

### ISSUE THREAD

**Issue by jaz-ah** [BranchMetrics/ios-branch-deep-linking#814]
When building with Branch 0.24.0 (or 0.23.5) with XCode9.3, you get the following warnings:
<img width="338" alt="screen shot 2018-04-04 at 7 21 32 am" src="https://user-images.githubusercontent.com/13263369/38313463-f3663a8a-37d8-11e8-9eb8-210adc84b6a5.png">

**Comment by jaz-ah** [comment]
+1 thanks @E-B-Smith

**Comment by E-B-Smith** [comment]
Fixed in version 0.24.1.
