### ISSUE TITLE
Urgent Issue

### ISSUE THREAD

**Issue by SudarvizhiSelvam** [BranchMetrics/ios-branch-deep-linking#815]
I integrated the branch.io using the document "https://docs.branch.io/pages/apps/ios/#handle-push-notifications "

when i click the link params is showing like this Optional(["+clicked_branch_link": 0, "+non_branch_link": com.thevoizeapp://open?link_click_id=511052502067353474, "+is_first_session": 0])
when i close the app and iam getting the param delayed why this happens Optional(["$ios_url": https://thevoiz.test-app.link, "+is_first_session": 0, "~campaign": content 123 launch, "+match_guaranteed": 0, "$og_title": iOS , "$publicly_indexable": 1, "$og_description": Voiz App Profile Share, "~channel": facebook, "$one_time_use": 0, "~feature": sharing, "random": 3B518AC3-1CCC-44E9-964B-F03FB196A0FF, "~creation_source": 3, "user_id": 2, "$desktop_url": http://example.com/home, "$locally_indexable": 1, "custom_data": yes, "~referring_link": https://thevoiz.app.link/Eszoq4DIUL, "deep_link_type": profile, "~id": 511037280715393454, "$og_image_url": https://s3-us-west-2.amazonaws.com/voizapp/UserThumbnail/20180219174129782.png (65 kB)
, "$canonical_identifier": content/123, "~stage": new user, "$identity_id": 510773376495799007, "+clicked_branch_link": 1, "+click_timestamp": 1523082637])
thevoiz.test-app.link
VOIZ App
A voice social media platform created to promote a better world while adding a personal and emotional element to interaction. VoizBuzz LLC CA - The Voiz App
 
 thevoiz.app.link
iOS
Voiz App Profile Share (65 kB)

do knw why it is gets delayed any solution

**Comment by SudarvizhiSelvam** [comment]
Hi E-B-Smith can you suggest me any answer for this

**Comment by SudarvizhiSelvam** [comment]
Hi E-B Smith Thank your help it is working fine now 
 but it in cross platform it is not working andriod link is redirecting in to my app i wont get the params
same issue in android also why this happen branch io does not support this..???

**Comment by E-B-Smith** [comment]
I think you have a configuration issue with your Android app as well.  

You can get specific question answered at the forum:

https://github.com/BranchMetrics/android-branch-deep-linking
