### ISSUE TITLE
DeepLink opens app but callback in not firing until the app goes to background

### ISSUE THREAD

**Issue by hushhash** [BranchMetrics/ios-branch-deep-linking#825]
Two targets on the same code base with different configurations, the one that's in production is having a critical and strange issue: 
- App is running
- User clicks on a deeplink from outside the app
- App is triggered and is opened and one of two things happen:
1.  On the test target, initSessionWithLaunchOptions:andRegisterDeepLinkHandler: callback is being called immediately as expected as a response to clicking the link. 
2.  On the production target the callback back isn't called until the app goes to background (for example: opening the iOS notification screen).

because the app is refocused from the link, and because the deeplink is called, only not in the right time, the configuration seems to be ok. 

One thing I've noticed is that in regards to the app delegate, on the production target the deep link triggers:
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options { 
While the other target's deeplink triggers 
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray * __nullable restorableObjects))restorationHandler

**Comment by E-B-Smith** [comment]
Are you using the same URL scheme and applink domains defined correctly in both configurations?

Check that the URL scheme defined in your Info.plist is correct in both, and that your associated domains are set up in your app's capabilities section.

**Comment by E-B-Smith** [comment]
I'm glad you solved it.  I'll look into why it has to be the first though.

**Comment by E-B-Smith** [comment]
I updated the documentation to make sure it's clear that the app's URI scheme should be the first one listed in the Info.plist file.

Release 0.24.2.
