### ISSUE TITLE
[iOS 11.3] Cannot get controlParams in initSession function

### ISSUE THREAD

**Issue by nguyenngocnhan90** [BranchMetrics/ios-branch-deep-linking#830]
I am using Branch to catch `controlParams` in `initSession` function in AppDelegate.swift. It works in iOS 11.2 but iOS 11.3.
So I cannot handle the detail of action in iOS 11.3 .

Would you please help me to detect this issue and give me the feedbacks? Thanks!

**Comment by E-B-Smith** [comment]
Have you added the Branch call back to both 

```

**Comment by nguyenngocnhan90** [comment]
I did add to these functions as well. But it does not run to these functions to call Branch callback.
For iOS 11.3

**Comment by E-B-Smith** [comment]
Have you defined a URL scheme for your app and configured it in the Branch dashboard?

Also, can you post the relevant portions of your app delegate here?

**Comment by nguyenngocnhan90** [comment]
```
branch.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: {(params, error) in
                guard let params = params else {
                    return
                }
                
                // Check passing param to redirect
                // Has `+clicked_branch_link` and `+is_first_session` only
            })

**Comment by E-B-Smith** [comment]
Is this just deferred deep linking or all deep linking?

**Comment by E-B-Smith** [comment]
@richardliveraise There's no SDK update needed.  

The problem with 11.3.1 is that Apple changed the Safari user agent string to not include the patch version of the browser, which was causing our deferred deep linking mechanism on the backend to fail.

We patched and deployed the backend and it should be working better now.

**Comment by nguyenngocnhan90** [comment]
Oh, great!
Thank you very much, @E-B-Smith !
I did test again on many iOS version, and it works well!
