### ISSUE TITLE
Links not being created correctly on iOS 10

### ISSUE THREAD

**Issue by joaopedro1520** [BranchMetrics/ios-branch-deep-linking#834]
Hello, I'm using the latest branch version 0.25 and when doing some tests noticed that on ios10 the links are being created with bcn.lt/a/ -- shows private branch key--? channel ...., but on iOS 11 it correctly shows my custom link and most importantly it doesn't show the branch key in the link.
Thanks

**Comment by E-B-Smith** [comment]
This is normal.

When generating a link, Branch tries to create a short link which requires a network call to create the link on the Branch server. If the network isn't available, the Branch SDK creates a long link instead, which uses the bnc.lt domain and contains the Branch key.

**Comment by joaopedro1520** [comment]
This is only happening on iOS 10, on both iOS 9 and 11 the link is created correctly even with no internet. So it's okay for the branch key to be exposed in the link?

**Comment by E-B-Smith** [comment]
The created links are cached, so if you create a link, turn off internet, and create the same link again, it will use the cached link again (provided all the link info is the same).  That might be what you're seeing.

Yes, it's okay for the key to be exposed like this.
