### ISSUE TITLE
Branch callback method does not get called

### ISSUE THREAD

**Issue by mohammadrhn** [BranchMetrics/ios-branch-deep-linking#838]
Hi. I've noticed that when I click on a branch link, the data does not get passed to the iOS app. I've tested the links again in branch debug mode and found out that the branch server responds with link data but the callback method does not get called so the app doesn't receive any parameters.

**Comment by mohammadrhn** [comment]
- The links that I created using branch dashboard (Quick links)

- I tested the app in both states. when it was running in the background and when the app was not open and in both states, the problem occurs.

- The iOS version that my test device is running on is 11.3.1

**Comment by mohammadrhn** [comment]
I don't think so. I'm not using universal links

**Comment by E-B-Smith** [comment]
You'll need to configure universal links for you app for Branch links to work right. Here's the guide to setting that up:

https://docs.branch.io/pages/apps/ios/

**Comment by E-B-Smith** [comment]
I hope this helped fix your issue!

You can re-open this issue or contact Branch support if you're still having trouble.
https://support.branch.io/support/home

**Comment by mohammadrhn** [comment]
Hi again. I've enabled the universal links from the dashboard and created some new links and tested them but in the Xcode console I get this response when I click on a branch link:

`{"session_id":"535857377115803737","identity_id":"511597697552485853","link":"https://appstore.app.link?%24identity_id=511597697552485853","identity":"58806718","data":"{\"+match_guaranteed\":true,\"$marketing_title\":\"test link 2\",\"~creation_source\":1,\"~marketing\":true,\"+clicked_branch_link\":true,\"appId\":\"905007097600\",\"+click_timestamp\":1528996581,\"$one_time_use\":false,\"~id\":531517996016031230,\"+is_first_session\":false,\"~referring_link\":\"https://appstore.app.link/testLink2\",\"~feature\":\"marketing\"}","device_fingerprint_id":"535845528542551189"}.
2018-06-14 21:46:21.241995+0430 <<app_name>>[19507:2496131] [branch.io] BNCServerInterface.m(818) Debug: Server returned: Status: 200; Data: {
    data = "{\"+match_guaranteed\":true,\"$marketing_title\":\"test link 2\",\"~creation_source\":1,\"~marketing\":true,\"+clicked_branch_link\":true,\"appId\":\"905007097600\",\"+click_timestamp\":1528996581,\"$one_time_use\":false,\"~id\":531517996016031230,\"+is_first_session\":false,\"~referring_link\":\"https://appstore.app.link/testLink2\",\"~feature\":\"marketing\"}";
    "device_fingerprint_id" = 535845528542551189;
    identity = 58806718;
    "identity_id" = 511597697552485853;
    link = "https://appstore.app.link?%24identity_id=511597697552485853";
    "session_id" = 535857377115803737;
}.`

As you can see the `clicked_branch_link` is true but callback does not get called. This is the code that I use to setup Branch and I'm using the segment integration.

`
// Initializing Branch SDK
    Branch *branch = [Branch getInstance];
    [branch setDebug];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        NSLog(@"Branch Callback");
        if (!error && params) {
            // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
            // params will be empty if no data found
            // ... insert custom logic here ...
            NSLog(@"params: %@", params.description);    
        }
    }];
`

And this is how I enabled Branch using segment
`SEGAnalyticsConfiguration *configuration = [SEGAnalyticsConfiguration configurationWithWriteKey:@"<<MY_API_KEY>>"];
    configuration.trackApplicationLifecycleEvents = YES; // Enable this to record certain application events automatically!
    configuration.recordScreenViews = YES; // Enable this to record screen views automatically!
    configuration.trackPushNotifications = YES; //Enable this to record notifications
    configuration.trackDeepLinks = YES; //Enable this to record deepLinks
    [configuration use:[BNCBranchIntegrationFactory instance]];
    [SEGAnalytics setupWithConfiguration:configuration];
`

**Comment by E-B-Smith** [comment]
If your using the Segment integration you need to integrate Branch differently.

I find it easier to use Branch notifications when using Segment rather than the callback function.

Here's an example of using Branch with Segment:
https://github.com/BranchMetrics/Segment-Branch-iOS/tree/master/Examples/Fortune

Initialize Segment with Branch:
https://github.com/BranchMetrics/Segment-Branch-iOS/blob/master/Examples/Fortune/Fortune/AppDelegate.swift#L14-L25

Register to get notifications:
https://github.com/BranchMetrics/Segment-Branch-iOS/blob/master/Examples/Fortune/Fortune/FortuneViewController.swift#L27-L38

Handle the deep link notification:
https://github.com/BranchMetrics/Segment-Branch-iOS/blob/master/Examples/Fortune/Fortune/FortuneViewController.swift#L103-L129

**Comment by mohammadrhn** [comment]
Thanks.
I Added Branch notifications and when the app is in the background it works fine but when I close the app from multitasking and tap on a branch link it does not work. links just open the app but notifications do not get called. 
Should I register notifications in a specific file? (Delegate file for example)

**Comment by E-B-Smith** [comment]
It sounds like you need to make sure that Segment and the Branch integration are initialized in your `application:didFinishLaunchingWithOptions:` method, and you have added an observer for the notifications in that method too.

**Comment by mohammadrhn** [comment]
Thank you very much. The solution resolved my issues.

**Comment by E-B-Smith** [comment]
Awesome!
