### ISSUE TITLE
Links not being created correctly

### ISSUE THREAD

**Issue by dbonates** [BranchMetrics/ios-branch-deep-linking#841]
It seems to be the same problem as the https://github.com/BranchMetrics/ios-branch-deep-linking/issues/834 (closed issue ¯\\\_(ツ)_/¯) here on Peixe Urbano app, and like @joaopedro1520 said there, it doesn't seems to be related to internet since our app relies entirely on it and is running fine on related scenario.

### Print of link being generated link:

![fail-link](https://user-images.githubusercontent.com/188093/40372167-89b7673c-5dba-11e8-8541-b6c3f137fd63.png)

### Tests
* on a sequence of about `5 tests`, only `1 generated the short link`. And this is happening for about some weeks, and here's how it is influencing our sharing performance with about 45% of failed experiences:

### 45% fail between 23 apr ~ 21 may:
<img width="385" alt="captura de tela 2018-05-22 as 12 24 18" src="https://user-images.githubusercontent.com/188093/40372497-324faa12-5dbb-11e8-8fda-edeb41ecddd4.png">

### Failing with Facebook SDK:

The link work on WhatsApp sharing, but it fails if our user try it on Facebook, as you can see int this print:

![img_6f34db632883-1](https://user-images.githubusercontent.com/188093/40372154-80ad050c-5dba-11e8-8c77-f883606eeeb1.jpeg)

best,

**Comment by E-B-Smith** [comment]
Thanks for the heads up! That's a pretty dramatic fall in sharing. I'll investigate this and let you know what I find. 

Quick question: Are you trying to create an alias link?

**Comment by E-B-Smith** [comment]
Can you send the parameters that you are setting?  I'm not seeing short link creation fail, so maybe it's a particular parameter that's causing the problem.

**Comment by ernesto** [comment]
Same behavior here :/

**Comment by E-B-Smith** [comment]
Please send me an example of the kind of link your trying to create that is failing!  

I tested a number of times, and for the link parameters and settings I tried, I always got a short link.  So I think it's some link parameter that is being set that is misbehaving.

Rather than just having to guess it would be super helpful to have an example of a failing link.

**Comment by E-B-Smith** [comment]
This may have become a problem now because we are improving our backend code and tightening up our data type requirements.  The unfortunate side effect is that sometimes things that used to work start to fail.

Specifically, setting `$custom_meta_tags` to a stringified dictionary is probably rejected be the back end one the short link is generated.

I recommend using the `BranchShareLink` class to create and share Branch links.  Here's an example that uses your data.  I added your content data, content like title, price, category, to the Branch content container object `BranchUniversalObject`, and added link control parameters to the Branch `BranchLinkProperties` object.

Here's an example in Swift:

```swift
    @IBAction func shareBranchLinkAction(_ sender: AnyObject) {
        let canonicalIdentifier = "id-" + self.dateFormatter().string(from: Date.init())
        let shareBranchObject = BranchUniversalObject.init(canonicalIdentifier: canonicalIdentifier)
        shareBranchObject.title = "Share Branch Link Example"
        shareBranchObject.canonicalUrl = "https://developer.branch.io/"
        shareBranchObject.imageUrl = "https://branch.io/img/press/kit/badge-black.png"
        shareBranchObject.keywords = [ "example", "short", "share", "link" ]
        shareBranchObject.contentDescription = "This is an example shared short link."
        shareBranchObject.contentMetadata.customMetadata["publicSlug"] = canonicalIdentifier;
        shareBranchObject.contentMetadata.customMetadata = [
            "product:sale_price:amount": "39.9000015258789",
            "product:sale_price:currency": "BRL",
            "product:original_price:amount": "44.9000015258789",
            "product:price:amount": "39.9000015258789",
            "product:price:currency": "BRL",
            "product:original_price:currency": "BRL",
            "og:type": "product",
            "$sale_price": "R$ 39,90",
            "object_id": "219697",
            "object_type": 3,
        ];

        let shareLinkProperties = BranchLinkProperties()
        shareLinkProperties.feature = "Share"
        shareLinkProperties.channel = "Share"
        shareLinkProperties.campaign = "DealScreen"
        shareLinkProperties.controlParams = [
            "$deeplink_path": "peixeurbano://offer?location=florianopolis&tipo=3&offer=219697&utm_campaign=Share&utm_medium=DealScreen&utm_source=iOS",
            "$desktop_url": "https://www.peixeurbano.com.br/florianopolis/sushimasa-beira-mar/buffet-livre-de-japonesezkd?utm_campaign=Share&utm_medium=DealScreen&utm_source=iOS",
        ]

        let branchShareLink = BranchShareLink.init(
            universalObject: shareBranchObject,
            linkProperties:  shareLinkProperties
            )
        branchShareLink.title = "Share your test link!"
        branchShareLink.shareText = "Shared from Branch's TestBed-Swift at \(self.dateFormatter().string(from: Date()))"
        branchShareLink.presentActivityViewController(
            from: self,
            anchor: actionButton
        )
    }
```

**Comment by insidegui** [comment]
What about users running previous versions of the app?

**Comment by ernesto** [comment]
About my logs: 
```
[branchUniversalObject showShareSheetWithLinkProperties:linkProperties
                                               andShareText:shareDescription
                                         fromViewController:sender
                                                 completion:^(NSString *activityType, BOOL completed) { ...
```

```
<BranchUniversalObject 0x0000000159ecd0d0
 canonicalIdentifier: share_app/5638954
 title: (null)
 contentDescription: (null)
 imageUrl: https://cdn-production.beautydate.com.br/assets/fallbacks/cover_image_listing_768-f43a0b942397dabc607fca14b46a691b4f5a02e5d32a5c4402bc4be362024bd1.png
 metadata: {
    "referring_userAvatar" = "https://cdn-production.beautydate.com.br/uploads/user/avatar/5638954/thumb_c5d78ac3816540ac665a9e4aa3bfcee0.jpg";
    "referring_userId" = 5638954;
    "referring_userName" = "Ernesto Araujo";
}
 type: (null)
 locallyIndex: 0
 publiclyIndex: 0
 keywords: (null)
 expirationDate: (null)
>
```

```
BranchLinkProperties | tags: (null) 
 feature: share_app 
 alias: (null) 
 channel: app_beautydate_ios 
 stage: (null) 
 campaign: indique_o_app_protouser 
 matchDuration: 0 
 controlParams: {
    "$deeplink_path" = "beautydate://b2beauty/business?business_id=538&utm_source=BDALink";
    "$desktop_url" = "https://www.beautydate.com/fio-fio-beauty-club";
    "$og_image_url" = "https://cdn-production.beautydate.com.br/uploads/business/cover_image/538/listing_1492627703_768.jpg";
    "referring_EstablishmentCover" = "https://cdn-production.beautydate.com.br/assets/fallbacks/cover_image_listing_768-f43a0b942397dabc607fca14b46a691b4f5a02e5d32a5c4402bc4be362024bd1.png";
    "referring_EstablishmentName" = "Fio-Fio Beauty Club";
    "referring_key" = 5638954;
    "referring_professionalId" = 1373107;
}
```

**Comment by E-B-Smith** [comment]
@GeneShay Had a good point:  Is this because disableTracking in Branch is set for these users?

If you set disableTracking for a user (for instance, for GDPR), only long links can be generated.

Short links require that a round trip call to the Branch servers be made, which can be considered tracking.

**Comment by insidegui** [comment]
Ok, we have not disabled it, so it's enabled. Therefore our issue is not because of that flag.

**Comment by GeneShay** [comment]
@ernesto, in your case, the issue is definitely that [you have disabled tracking with Branch SDK](https://docs.branch.io/pages/apps/ios/#enable-disable-user-tracking).

@insidegui and @dbonates , 
1. Have you tried Edwards example code, where he used your exact parameters to create a link? Did it work as expected, or were you able to reproduce the issue?
I have not been able to reproduce this issue on our side, when operating on our office network and my personal home WiFi network. 

2. If you would like to provide your Branch App ID - I can test specifically for your Branch account.

3. I would also suggest testing this functionality with our TestBed App ([Swift](https://github.com/BranchMetrics/ios-branch-deep-linking/tree/master/Branch-TestBed-Swift) or [Obj C](https://github.com/BranchMetrics/ios-branch-deep-linking/tree/master/Branch-TestBed)). 

4. You may then setup Branch TestBed app with your Branch keys, to see if you can reproduce the issue. If you can't - that means that there is an integration issue. If you can - that means that something outside the app is causing this. 

Let me know what you find out! Please remember that the detail of your response and finding will help us find the issue at a faster rate.

**Comment by E-B-Smith** [comment]
If you're still having problems with this then re-open this issue or open a new one.

I hope this helped.

**Comment by insidegui** [comment]
It looks like the issue was server-side because the links are not being generated correctly again, without us changing anything 😊

**Comment by joaopedro1520** [comment]
In my case, it's still not working on ios10 . the links are still huge. This is my code to generate the links.

```
    BranchUniversalObject *branchUniversalObject = [[BranchUniversalObject alloc] initWithCanonicalIdentifier:@"share"];
    branchUniversalObject.canonicalUrl = @"url";
    branchUniversalObject.title = NSLocalizedString(@"title", nil);
    branchUniversalObject.contentDescription = [NSString stringWithFormat:NSLocalizedString(@"description", nil),
                                                user.referralCode];
    branchUniversalObject.imageUrl = @"www.png";
    [branchUniversalObject.contentMetadata.customMetadata setValue:@"promo_code" forKey:user.referralCode];
    
    BranchLinkProperties *linkProperties = [[BranchLinkProperties alloc] init];
    linkProperties.feature = @"sharing";
    [linkProperties addControlParam:@"$desktop_url" withValue:@"https://www."];
    [linkProperties addControlParam:@"$ios_deepview" withValue:@"default_template"];
        
    NSString * shareMessage = [NSString stringWithFormat:NSLocalizedString(@"share_message", nil),
                               user.referralCode, freeMinutes];
    
    [branchUniversalObject showShareSheetWithLinkProperties:linkProperties
                                               andShareText:shareMessage
                                         fromViewController:self
                                                 completion:^(NSString *activityType, BOOL completed) {}];
```

I compared with the testbed app and it seems the configs I have are correct. I didn't change anything since the time I implemented this a year ago.

Thanks

**Comment by E-B-Smith** [comment]
I'll test this on iOS 10 and see what I find.

**Comment by E-B-Smith** [comment]
I can't reproduce this on 10.3 with the code snippet you sent.  

Is `Branch.trackingDisabled` set to `YES`?  If tracking is disabled then the Branch SDK will always create long links (generating short links requires a server call which can be considered tracking.

**Comment by joaopedro1520** [comment]
Yes tracking is disabled. But again on ios11 short links are created.

Enviado do meu iPhone

No dia 22/06/2018, às 22:05, Edward Smith <notifications@github.com<mailto:notifications@github.com>> escreveu:


I can't reproduce this on 10.3 with the code snippet you sent.

Is Branch.trackingDisabled set to YES? If tracking is disabled then the Branch SDK will always create long links (generating short links requires a server call which can be considered tracking.

**Comment by E-B-Smith** [comment]
If you create the short link, then set tracking disabled, then the original short link will be used if it is cached.

**Comment by joaopedro1520** [comment]
Tracking is disabled on app start. Just wondering why this behavior only occurs for me on iOS 10 phones. New link creations on ios 9/11 are always short

Enviado do meu iPhone

No dia 22/06/2018, às 22:12, Edward Smith <notifications@github.com<mailto:notifications@github.com>> escreveu:


If you create the short link, then set tracking disabled, then the original short link will be used if it is cached.

**Comment by E-B-Smith** [comment]
I have the same behavior on iOS 10 and 11.

**Comment by dorucojocaru059** [comment]
Hello,

The issue still occurs on iOS13. Sometimes branch generates a long link, sometimes - a short one without any code changes. 
- The device has a good network connection
- A short link that was generated before is not cached, or at least is not retrieved from the cache, as mentioned above. Randomly a short or long link is generated for the same parameters (app-share-link). 
- the above mentioned 'disableTracking' is not mentionable for this case, as it was not used for our project.

Setting a timeout for branch requests did not help: 
e.g. Branch.getInstance().setNetworkTimeout(10)

**Comment by ioanafurtuna1** [comment]
@echo-branch - this is how we got instructed from your support team to proceed, which is what we did.

In any case, your suggestion has been already been tried without success. Following our own investigation, seems like the issue has a 100% repro while taking the mobile app to background, and then bringing it back to foreground and attempting to generate the URL again. We're in touch with support via email as well.

**Comment by echo-branch** [comment]
@dorucojocaru059 
I missed the part where you already tried setting a longer timeout.  I haven't seen the issue as described.  Could you provide some details such as SDK version, iOS version, which link method in a new ticket?  Thanks.
