### ISSUE TITLE
Issue occur when integrate google map

### ISSUE THREAD

**Issue by khan33** [BranchMetrics/ios-branch-deep-linking#847]
I am facing issue when google map integrate to project. Following issue occurring 
Property 'URLBlackList' not found on object of type 'BNCPreferenceHelper *' 
<img width="973" alt="screen shot 2018-07-31 at 10 16 08 pm" src="https://user-images.githubusercontent.com/41967446/43475507-704ed14a-950f-11e8-8a3d-47dcb4648d1a.png">

**Comment by Shahbaz-Akram** [comment]
I am also facing this issue after installing pod 'GoogleMaps' otherwise working fine.

**Comment by E-B-Smith** [comment]
Thanks for the heads up.  I'll look into this, but in the mean time did you refresh the Branch pod too? That is do a, `pod install --repo-update` to re-install and update all the pods you're using?

**Comment by khan33** [comment]
@E-B-Smith  i can't update my existing pods. Because of customization in pods.

**Comment by E-B-Smith** [comment]
Can you update just Branch?

It looks like there's some sort of file version mismatch with your Branch integration.

**Comment by E-B-Smith** [comment]
@khan33 ^^^

**Comment by khan33** [comment]
let me update Branch

**Comment by khan33** [comment]
Thanks @E-B-Smith. I update Branch (0.25.1) through cocapod now error resolved.

**Comment by E-B-Smith** [comment]
@Shahbaz-Akram Does this resolve your issue too?

**Comment by Shahbaz-Akram** [comment]
@E-B-Smith  yes thanks man
