### ISSUE TITLE
https://api.branch.io/v1/open fails in production

### ISSUE THREAD

**Issue by mbesnili** [BranchMetrics/ios-branch-deep-linking#850]
Hello, 

We've integrated branch ios sdk into our app which seemed to work fine in debug builds. Here are some logs from our our debug builds. 

default	21:29:28.975634 +0300	Sociable	[branch.io] Branch.m(192) Log: Branch version 0.25.0 started at 2018-08-07 18:29:28 +0000.
default	21:29:29.863698 +0300	Sociable	[branch.io] BNCServerInterface.m(758) Debug: URL: https://api.branch.io/v1/install.
default	21:29:29.864103 +0300	Sociable	[branch.io] BNCServerInterface.m(762) Debug: Body: {
    "ad_tracking_enabled" = 1;
    "app_version" = "12.2";
    "apple_ad_attribution_checked" = 0;
    "branch_key" = "key_live_fjDQ45E8XmTc6owmdCTaEmgbytjNYWFc";
    brand = Apple;
    country = PT;
    debug = 1;
    "facebook_app_link_checked" = 0;
    "first_install_time" = 1531307562360;
    "hardware_id" = "8C827EEB-B3BA-42C2-82FB-588429030D2C";
    "hardware_id_type" = random;
    "ios_bundle_id" = "com.forplay.forplay";
    "ios_team_id" = H3SATSSFHJ;
    "ios_vendor_id" = "44E9E198-3633-4211-B4AF-6D524DBF0D4A";
    "is_hardware_id_real" = 0;
    language = pt;
    "lastest_update_time" = 1533666546000;
    "latest_install_time" = 1533666560315;
    "local_ip" = "10.191.165.238";
    model = "iPhone8,1";
    os = iOS;
    "os_version" = "11.4.1";
    retryNumber = 0;
    "screen_height" = 1334;
    "screen_width" = 750;
    sdk = "ios0.25.0";
    update = 2;
    "uri_scheme" = sociable;
    "user_agent" = "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77";
}
JSON: {"sdk":"ios0.25.0","facebook_app_link_checked":false,"language":"pt","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77","screen_height":1334,"country":"PT","app_version":"12.2","update":2,"ad_tracking_enabled":true,"brand":"Apple","ios_team_id":"H3SATSSFHJ","retryNumber":0,"uri_scheme":"sociable","local_ip":"10.191.165.238","os":"iOS","hardware_id":"8C827EEB-B3BA-42C2-82FB-588429030D2C","screen_width":750,"ios_vendor_id":"44E9E198-3633-4211-B4AF-6D524DBF0D4A","ios_bundle_id":"com.forplay.forplay","first_install_time":1531307562360,"hardware_id_type":"random","latest_install_time":1533666560315,"debug":true,"os_version":"11.4.1","is_hardware_id_real":false,"model":"iPhone8,1","branch_key":"key_live_fjDQ45E8XmTc6owmdCTaEmgbytjNYWFc","lastest_update_time":1533666546000,"apple_ad_attribution_checked":false}.
default	21:29:29.864490 +0300	Sociable	[branch.io] BNCNetworkService.m(232) Debug: Network start operation https://api.branch.io/v1/install.
default	21:29:30.002647 +0300	Sociable	[4 api.branch.io:443 stream, pid: 2763, url: https://api.branch.io/v1/install, tls] start
default	21:29:30.802446 +0300	Sociable	[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api.branch.io/v1/install 1.018s. Status 200 error (null).
{"session_id":"555444733367957269","identity_id":"555444733339016383","link":"https://sociable.app.link?%24identity_id=555444733339016383","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":true}","device_fingerprint_id":"555444733326112445"}.
default	21:29:30.802475 +0300	Sociable	[branch.io] BNCServerInterface.m(818) Debug: Server returned: Status: 200; Data: {
    data = "{\"+clicked_branch_link\":false,\"+is_first_session\":true}";
    "device_fingerprint_id" = 555444733326112445;
    "identity_id" = 555444733339016383;
    link = "https://sociable.app.link?%24identity_id=555444733339016383";
    "session_id" = 555444733367957269;
}.
default	21:29:30.803039 +0300	Sociable	[branch.io] BNCNetworkService.m(232) Debug: Network start operation https://cdn.branch.io/sdk/uriskiplist_v0.json.
default	21:29:30.803531 +0300	Sociable	[10 cdn.branch.io:443 stream, pid: 2763, url: https://cdn.branch.io/sdk/uriskiplist_v0.json, tls] start
default	21:29:31.122471 +0300	Sociable	[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://cdn.branch.io/sdk/uriskiplist_v0.json 0.325s. Status 200 error (null).
{"version":1, "uri_skip_list":["^fb\\d+:","^li\\d+:","^pdk\\d+:","^twitterkit-.*:","^com\\.googleusercontent\\.apps\\.\\d+-.*:\\\/oauth", "^(?i).+:.*[?].*\\b(password|o?auth|o?auth.?token|access|access.?token)\\b"]}.
default	21:29:31.122834 +0300	Sociable	[10 cdn.branch.io:443 stream, pid: 2763, url: https://cdn.branch.io/sdk/uriskiplist_v0.json, tls] cancelled
	[10.1 79F5C8B9-FFEC-428B-9331-47B728E2CAC6 192.168.1.100.65226<->13.32.222.72:443]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 0.324s, DNS @0.002s took 0.013s, TCP @0.017s took 0.077s, TLS took 0.167s
	bytes in/out: 5140/592, packets in/out: 6/3, rtt: 0.071s, retransmitted packets: 0, out-of-order packets: 0

**In production, branch initialization seemed to failed somehow.** 

default	21:04:26.842719 +0300	Sociable	[branch.io] Branch.m(192) Log: Branch version 0.25.0 started at 2018-08-07 18:04:26 +0000.
default	21:04:30.092376 +0300	Sociable	[9 <private> stream, pid: 2722, url: https://cdn.branch.io/sdk/uriskiplist_v0.json, tls] cancelled
	[9.1 897B6C2F-E38B-4490-AE45-17C1A68E631D <private>.65030<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 0.273s, DNS @0.000s took 0.017s, TCP @0.019s took 0.051s, TLS took 0.149s
	bytes in/out: 5140/592, packets in/out: 6/3, rtt: 0.052s, retransmitted packets: 0, out-of-order packets: 0
default	21:04:51.276003 +0300	Sociable	[4 <private> stream, pid: 2722, url: https://api.branch.io/v1/install, tls] cancelled
	[4.1 B367C73E-2195-47F9-9068-397DCE444287 <private>.65028<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 22.956s, DNS @0.004s took 0.733s, TCP @0.740s took 0.287s
	bytes in/out: 0/0, packets in/out: 0/0, rtt: 0.000s, retransmitted packets: 0, out-of-order packets: 0
default	21:05:30.836882 +0300	Sociable	[14 <private> stream, pid: 2722, url: https://api.branch.io/v1/open, tls] cancelled
	[14.1 34FE817F-5EA3-490B-A746-F0A64171D86F <private>.65044<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 38.873s, DNS @0.000s took 0.012s, TCP @0.033s took 0.319s
	bytes in/out: 0/0, packets in/out: 0/0, rtt: 0.000s, retransmitted packets: 0, out-of-order packets: 0
default	21:05:32.578423 +0300	Sociable	[branch.io] BNCServerInterface.m(598) Error: An error prevented request to https://api.branch.io/v1/open from completing: Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}
default	21:05:32.579074 +0300	Sociable	[branch.io] BranchOpenRequest.m(183) Warning: Received session data of type '__NSSingleEntryDictionaryI' data is '{
    "+clicked_branch_link" = 0;
}'.
default	21:05:33.863785 +0300	Sociable	[branch.io] Branch.m(2054) Error: Missing session items!
default	21:07:32.664013 +0300	Sociable	[22 <private> stream, pid: 2722, url: https://api.branch.io/v1/open, tls] cancelled
	[22.1 6F32D768-E126-4A40-A2AF-8EA09BB79110 <private>.65058<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 121.472s, DNS @0.001s took 0.006s, TCP @0.012s took 0.812s, TLS took 0.150s
	bytes in/out: 4881/1749, packets in/out: 9/9, rtt: 0.141s, retransmitted packets: 0, out-of-order packets: 0

What's the problem here ? 

Thanks in advance. 

If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by E-B-Smith** [comment]
Are you running through a proxy, like Charles proxy? The SSL can't make a handshake, so the network events are cancelled.

**Comment by mbesnili** [comment]
No, i'm not running through a proxy ? Same code works for debug, but doesn't work in production.

**Comment by E-B-Smith** [comment]
Are you using the correct key for the production version?

Also, you can turn on more logging information by setting `BNCLogSetDisplayLevel(BNCLogLevelAll);` in your app delegate before initializing Branch.

**Comment by mbesnili** [comment]
We're using same key for debug and production version. So, i'm pretty sure it's core as it works for debug version. 

I'm going to submit a new version of app with BNCLogSetDisplayLevel(BNCLogLevelAll) set. I'm going to let you know if something pops up.

Thank you.

**Comment by E-B-Smith** [comment]
@mbesnili  I hope you resolved your problem.  If you need more advice you can reopen this issue.
