### ISSUE TITLE
Error calling Branch Events in Objective-C

### ISSUE THREAD

**Issue by rodrigobdz** [BranchMetrics/ios-branch-deep-linking#855]
I am currently implementing Branch Events in an app and while reading the docs I used a function call I found in the [README](https://github.com/BranchMetrics/ios-branch-deep-linking/blame/5dd137d3e224b7f0ddc7c3b4906c3a2f6a380e51/README.md#L607):

```objc
[BranchEvent.standardEvent(BranchStandardEventAddToCart) logEvent];
```

Xcode throws an error. Shouldn't it be called as shown below?

```diff
- [BranchEvent.standardEvent(BranchStandardEventAddToCart) logEvent];
+ [[BranchEvent standardEvent:BranchStandardEventAddToCart] logEvent];
```

**Comment by E-B-Smith** [comment]
Yes it should!  Thanks, I'll update the docs. It looks like the Swift and obj-c examples got intertwined.
