### ISSUE TITLE
Dynamic Link Not Processed for Installations

### ISSUE THREAD

**Issue by TinananaWang** [BranchMetrics/ios-branch-deep-linking#858]
## Background
We are not getting consistent UTMs in Branch & Segment, and we were instructed by @Sarkar to use the dynamic link, which does give us UTMs in Branch with 100% success rate. However, since the Branch SDK cannot handle sending UTM parameters from Facebook campaign links because of some Facebook regulation, we need to set up the code by ourselves. Here is our internal ticket:

The marketing team is using "dynamic links" like this one: https://cm2v.test-app.link?%243p=a_facebook&utm_campaign=some_campaign&utm_source=some_source&%24ios_url=https%3A//rink.hockeyapp.net/apps/67cf1e34766347cea6a1f0c0df01d3ed&%24android_url=https%3A//play.google.com/store/apps/details%3Fid%3Dcom.hopskipdrive.hsd_android_v2.beta&%24desktop_url=https%3A//organizer.hopskipdev.com/sign-up

You can identify the link as coming from a Facebook campaign by the presence of $3p=a_facebook in the path.

Given a link in this format, send a track event to Segment using the Segment SDK.

- event_name: “Install Attributed"
- Properties: All of the params in the link, including anonymousId, all the utms, etc. Partial screenshot of an example event, which should give you enough information to know how to structure the data:
<img width="1411" alt="succeed utm" src="https://user-images.githubusercontent.com/20799093/45069985-03292580-b084-11e8-828b-bc2dba9ffcd7.PNG">

## Issue from Our Engineer while Setting it Up
Unfortunately, in staging what I am seeing is that the link is not processed when it's an install (i.e. uninstall, clear advertising id, then click link). I am redirected to HockeyApp to install, then the app is opened but that link click is not attributed. If I click on the link after the app has been installed then the params / branch link are received & parsed correctly.

Here are the parms that branch returns in initSession() after a fresh install after resetting the advertising ID:

![1](https://user-images.githubusercontent.com/20799093/45070032-4edbcf00-b084-11e8-95df-5f57a288357c.PNG)

And here's what I get if the app is already installed and running in the background and I click the link:

![2](https://user-images.githubusercontent.com/20799093/45070055-61ee9f00-b084-11e8-8998-cbb04d216ff9.PNG)

Most notable is that in the fresh install scenario, the "clicked_branch_link" parameter is "0" (false) - it should be "1" (true). Unfortunately, their SDK does not work the way Branch claims.

@Sarkar Please help with this problem as soon as possible. Thank you!

**Comment by E-B-Smith** [comment]
Thanks for bringing this to our attention.  Sorry this has been a chore to get going: There are a ton of pieces to this. 

This will take some investigation to see what's going on.

**Comment by TinananaWang** [comment]
@E-B-Smith This is pretty urgent. Can we please get an estimate? Thanks.

**Comment by E-B-Smith** [comment]
Which version of Segment and Branch are you on?  Make sure you use `pod update` to use the latest version on the SDKs.  This may be the problem with double opens.

**Comment by johnemiller** [comment]
We are currently on Branch 0.25.3 & LeanPlumSegment 1.1.3
