### ISSUE TITLE
Cannot get custom  parameters from deep link in iOS app

### ISSUE THREAD

**Issue by bkudale33** [BranchMetrics/ios-branch-deep-linking#863]
I am using Branch version - 0.25.3.
Recently i updated the branch version, before updating the version it was working.
sometime parameters get received but most of the time only get default parameters .
only getting the following parameters
{
    "+clicked_branch_link" = 0;
    "+is_first_session" = 0;
    "+non_branch_link" = "wowparenting://open?link_click_id=568052920356847505";
}
Branch link  -  https://wowparenting.app.link/EBBXdFiE7P

**Comment by E-B-Smith** [comment]
It looks like you may have a configuration mismatch somewhere.

Make sure you're using the right Branch key in your app.  It's best to use your live Branch key for both testing and production unless you're worried about stats. 

Also check that your 'Link Settings' are all match in the Branch dashboard and in your app.

**Comment by E-B-Smith** [comment]
Where you able to resolve this?
