### ISSUE TITLE
getShortURL does not work

### ISSUE THREAD

**Issue by trungdv1987** [BranchMetrics/ios-branch-deep-linking#865]
Hi Support team,

You have done a good work on BranchSDK. 
Just we've found a small issue pls kindly help me on this, we're going submit app to the store but this issue makes us less confidence:

Attached file is a sample project that able to demonstrate the bug.
Probably you should use your branch key and facebook app id as well.

on iOS 9: after login FB, getShortURL got frozen, never ever return the link
on ios 11.2.6: it does not work after login FB thru native app only (thru browser works fine)

[TrungDV_Test.zip](https://github.com/BranchMetrics/ios-branch-deep-linking/files/2417685/TrungDV_Test.zip)

**Comment by E-B-Smith** [comment]
Sorry about your troubles.  I'll take a look at your example and see what's up.

**Comment by trungdv1987** [comment]
Thanks Smith,

Pls note that before login, if we call getShortURL then it works normally, but after login thru FB, there're some cases as i mentioned above

**Comment by trungdv1987** [comment]
@E-B-Smith 

Dear Smith, we still have not any updates yet?

**Comment by E-B-Smith** [comment]
Thanks for you great example.  It made finding the issue really easy.

I'll have a fix for this soon!  I'll update this thread when it's available.

**Comment by E-B-Smith** [comment]
Pull #867

**Comment by trungdv1987** [comment]
@E-B-Smith Thanks, i tested it and it works.
But i pull the sdk from your branch, integrate to our project, Xcode raised an error about code sign. 
Then i built the sdk by my self from your project, but i got an error: "Bitcode bundle could not be generated because Branch was built without full bitcode"
Can you double check?

**Comment by E-B-Smith** [comment]
I didn't build the PR for release, just for testing pre-release, so the framework isn't built.

If you build it yourself you'll need to turn on bitcode in the project settings.

Or you can wait until tomorrow when I release the whole thing for real.

**Comment by trungdv1987** [comment]
The bitcode already enabled from your project and ours as well.
I think i can wait until tomorrow. Pls ping me once you release it for real.

Thanks.

**Comment by trungdv1987** [comment]
@E-B-Smith do you have any updates yet?

**Comment by E-B-Smith** [comment]
Thank you for your patience!
https://github.com/BranchMetrics/ios-branch-deep-linking/releases/tag/0.25.6

**Comment by trungdv1987** [comment]
Thanks Smith!

**Comment by trungdv1987** [comment]
@E-B-Smith can i ask you a question?

Is there any case that when hit Branch link, app just call app delegate:

**Comment by trungdv1987** [comment]
@E-B-Smith 

It happens with version: 0.25.6
And works well with version: 0.25.5
