### ISSUE TITLE
Getting custom parameters from deep link in iOS app 

### ISSUE THREAD

**Issue by imanzarrabian** [BranchMetrics/ios-branch-deep-linking#869]
Hey I have this exact same issue  https://github.com/BranchMetrics/ios-branch-deep-linking/issues/863 which was closed but no clue on how to get around it :(
I have some custom params on one side when creating the link with the ios SDK 
```swift
        let buo = BranchUniversalObject(canonicalIdentifier: shareToken)
        // buo.canonicalUrl = "https://example.com/content/123"
        buo.title = NSLocalizedString("ContactsApp, le carnet d’adresse toujours à jour de vos contacts professionnels", comment: "")
        
        buo.contentDescription = NSLocalizedString("Retrouve mes informations de contact sur Contacts App", comment: "")
        buo.locallyIndex = true
        buo.contentMetadata.customMetadata = ["token": shareToken, "user_id": User.me!.id]
        buo.userCompletedAction("Viewed")
```
but I only get two default parameters when opening the link on the other side
```swift
   Branch.getInstance().initSession(launchOptions: launchOptions) { (params, error) in
            guard let params = params as? [String: AnyObject] else {
                return
            }
            if let token = params["token"] as? String, let userId = params["user_id"] as? String {
                DeepLinkManager.saveTokenAndUserID(token: token, userId: userId)
                DeepLinkManager.routeToDeepLink()
            }
        }
```
The "token" and "user_id" are never present when clicking on the link. 
I am using the live key 
Any help would be welcome :)

**Comment by imanzarrabian** [comment]
I noticed that it stopped working after updating my pods recently. Worked perfectly before that

**Comment by imanzarrabian** [comment]
Oh! Was this fixed in 0.25.6? 
_Fixed a case when a session call back could happen with empty data._

**Comment by benspratling4** [comment]
I have similar trouble in 0.25.0 and 0.25.3.  I added analytics to verify the deep link is getting into the app, but the deep link handler isn't getting called.
My deep link handler is called as long as the user is starting up a new install without a deep link.

**Comment by imanzarrabian** [comment]
Yes. It seems to me that when coming from a branch.io link this function is not called
```swift
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool { 
   Branch.getInstance().application(app, open: url, options: options)
   return true
}
```
When clicking on a classic my-app:// link though the open url function triggers. Might be related to the issue.

**Comment by E-B-Smith** [comment]
Yikes! I'm looking into this now.  Are you using the Segment-Branch SDK by any chance?

**Comment by imanzarrabian** [comment]
Hey! Nope not using segment at all.

**Comment by benspratling4** [comment]
E-B, I am using the Segment-Branch SDK.  Maybe my issue is different?

**Comment by E-B-Smith** [comment]
@benspratling4 

There was a change in the way that Segment creates an instance to Branch that made the old way not work anymore.  

In short, the instance returned from `Branch.getInstance()` early on in the initialization may not be the one that Segment uses, creating a lot of confusion. 

We now suggest observing the `NSNotifications` that Branch sends to handle deep links as that is pretty bullet proof.

Here's the updated example at the Segment-Branch-iOS repo:

https://github.com/BranchMetrics/Segment-Branch-iOS#step-2-add-some-code-to-your-appdelegate

**Comment by imanzarrabian** [comment]
@E-B-Smith 
Thx for your help the ```continueUserActivity```method was already implemented in my AppDelegate but you pointed me in the right direction. 
It turns out that this is the method that is called now. The signature chagned a bit (the restorationHandler Input param type is now explicit). Implementing this method makes the deeplink work again. 
```swift 
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        Branch.getInstance().continue(userActivity)
        return true
    }
```
Thx for your help.

**Comment by imanzarrabian** [comment]
@E-B-Smith I opened a PR for README update BTW

**Comment by E-B-Smith** [comment]
Thanks for the update!
