### ISSUE TITLE
Handler of Branch.getInstance().initSession isn't being called

### ISSUE THREAD

**Issue by trungdv1987** [BranchMetrics/ios-branch-deep-linking#870]
Is there any case that when hit a short link ex: app.md.com/GHHDI76878H, app calls (2) only instead of (1)

Our app: start app -> hit initSession handler (1), send to background -> hit short link -> it called (2) only
Our sample app: start app -> hit initSession handler (1), send to background -> hit short link -> it called (1) only as expectation

The difference is 1 app integrated a lot of third parties: Facebook, Google, Firebase, Twitter, etc...
The other didn't

**(1)**`Branch.getInstance().initSession(launchOptions: launchOptions) { (params, error) in
            // do stuff with deep link data (nav to page, display content, etc)
            print(params as? [String: AnyObject] ?? {})
        }`

**(2)** `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
    Branch.getInstance().continue(userActivity)
}`

**Comment by trungdv1987** [comment]
It happens with version: 0.25.6
And works well with version: 0.25.5

**Comment by E-B-Smith** [comment]
Thanks for the heads up.  I'm looking into this now.

**Comment by E-B-Smith** [comment]
Are you using the Segment-Branch integration.

**Comment by E-B-Smith** [comment]
Are your apps, your app and your sample app using the identical Branch keys and Branch set up?

**Comment by trungdv1987** [comment]
At the beginning, our app is integrated Branch via Fabric.
Our sample is integrated follow this guide (manual install): https://docs.branch.io/pages/apps/ios/ 

Then i removed Fabric and it's related things, then tried re-integrate with manual install follow that guide, but no luck. But older version works well.

Our app and sample app are using the same bundle id and Branch key.

**Comment by trungdv1987** [comment]
Our sample app is attached in issue https://github.com/BranchMetrics/ios-branch-deep-linking/issues/865

**Comment by E-B-Smith** [comment]
The short link https://app.md.com/GHHDI76878H isn't a Branch link, so the call back handler won't indicate that it is a Branch link.

A link like https://megadeeds.app.link/LZPi5iO3KQ  **is** a Branch link, and the callback handler will indicate that it's a Branch link and the associated data will be returned.

**Comment by E-B-Smith** [comment]
I hope this clarified things for you! Happy deep linking.

**Comment by trungdv1987** [comment]
@E-B-Smith  Sorry for making confuse, I just gave an example. But the link is definitely a Branch link, like : https://megadeeds.app.link/LZPi5iO3KQ. Do you have any ideas ?

**Comment by E-B-Smith** [comment]
When you click on the link, does it open the app?
If you're running it on a device, is it code signed correctly?
Are you using your live key?
Have you added both these functions to your app delegate?
```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {

    // Pass the url to the handle deep link call
    let branchHandled = Branch.getInstance().application(application,
        open: url,
        sourceApplication: sourceApplication,
        annotation: annotation
    )
    if (!branchHandled) {
        // If not handled by Branch, do other deep link routing for the
        // Facebook SDK, Pinterest SDK, etc
    }

    return true
}

func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    let handledByBranch = Branch.getInstance().continue(userActivity)

    return handledByBranch
}
```

**Comment by trungdv1987** [comment]
@E-B-Smith,

When you click on the link, does it open the app? -> Yes
If you're running it on a device, is it code signed correctly? -> Yes
Are you using your live key? -> Yes
Have you added both these functions to your app delegate? -> Yes

**Comment by E-B-Smith** [comment]
Are you testing with a link that is not desktop only or one time use?

**Comment by trungdv1987** [comment]
Yes it's weirds that the demo app is working fine.
And the fact that if i replace with older Branch SDK, our app works normally.

I think i will simplify our app (remove all businesses) and send you for checking.

**Comment by E-B-Smith** [comment]
Are you calling Branch.setIdentity before initializing Branch?
Sometimes that causes problems.
Move it to right after initializing Branch if so.

**Comment by trungdv1987** [comment]
Are you calling Branch.setIdentity before initializing Branch? -> **NO**

Below is the link of project which able to demonstrate the bug. Please take a look @E-B-Smith .
Thanks.

https://drive.google.com/open?id=14Vb5BgjnyGgciqhRndsl9xcsP6bBUrrS

**Comment by E-B-Smith** [comment]
Are you using Swift 3 or Swift 4?

**Comment by E-B-Smith** [comment]
Thanks for your example - I was able to find a solution for you.

Put the call to `Branch.getInstance().continue(userActivity)` first in your `continueUserActivity:` method, like this:

```swift
    //** universal links
   // Make sure this method isn't marked `private`!
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        Branch.getInstance().continue(userActivity) // <= Put this line first!
        BranchManager.userCompletedAction("ActionLog.startappUL") // Then this line.
        // pass the url to the handle deep link call
        return true
    }
```

This should solve your problem now, and I'll patch the SDK to prevent problems like this in the future.

**Comment by trungdv1987** [comment]
@E-B-Smith Swift 4

**Comment by trungdv1987** [comment]
Thanks @E-B-Smith E
it works like a charm, simple but takes time to configure it out

**Comment by trungdv1987** [comment]
Cheers :)
