### ISSUE TITLE
BranchCSSearchableItemAttributeSet is not imported in framework module

### ISSUE THREAD

**Issue by roccx** [BranchMetrics/ios-branch-deep-linking#873]
Is there a reason why `BranchCSSearchableItemAttributeSet` isn't imported into the framework? 
Is it deprecated or obsolete?

I was trying to use the Branch API for custom spotlight indexing of html documents, 
which isn't possible with `BranchUniversalObject`.

**Comment by E-B-Smith** [comment]
Thanks for the heads up.  I this is an oversight and I'll make the header public.

If you don't want to wait for the next release you can mark the header public yourself and start using it.

**Comment by roccx** [comment]
This doesn't seam to solve the issue are you missing it inside the Branch.h header maybe?
