### ISSUE TITLE
Branch.m -handleUniversalDeepLink_private:fromSelf: duplicates code from Branch.m -isBranchLink:

### ISSUE THREAD

**Issue by benspratling4** [BranchMetrics/ios-branch-deep-linking#878]
With the distinction being -handleUniversalDeepLink_private: calls -bnc_containsString: instead of -containsString:.  The difference between -bnc_containsString and -containsString: is -bnc_containsString: checks if the argument is nil.  However, in -handleUniversalDeepLink_private: this check is unnecessary, because in each case other calls would have failed first if it were nil.

**Comment by E-B-Smith** [comment]
The difference is that `-isBranchLink:` is a public interface and is expected to work in a certain way.

Since `handleUniversalDeepLink_private:fromSelf:` is a private method we can change (and have)  how that method behaves.  There's no contract with the SDK user.
