### ISSUE TITLE
Branch.m -isBranchLink: and BNCPreferenceHelper.m -getBranchUniversalLinkDomains are instance methods unnecessarily.

### ISSUE THREAD

**Issue by benspratling4** [BranchMetrics/ios-branch-deep-linking#879]
Branch.m -isBranchLink: is an instance method, but it could be a class method, allowing me to check if an incoming URL is a branch link before Branch has finished initialization, thus allowing me to handle non-branch links without the complication of waiting on Branch to initialize.

While -isBranchLink: depends on self.preferenceHelper, which would appear to require an instance, the only preference helper method it calls is -getBranchUniversalLinkDomains:, which does not depend on any instance properties either, and thus could be a class method.

**Comment by E-B-Smith** [comment]
What's your use case for doing this? Maybe I can suggest an easier way.

**Comment by E-B-Smith** [comment]
Feel free to reopen the issue if you still have questions.
