### ISSUE TITLE
BranchUniversalObject content type restrictions

### ISSUE THREAD

**Issue by roccx** [BranchMetrics/ios-branch-deep-linking#880]
The `BranchUniversalObject` is restricting the possible content types to a predefined set of possibilities compared to local indexed `CSSearchableItemAttributeSet`. 

Should the `BranchUniversalObject` only reflect an API which is supported by deep-linking or would it be possible to add APIs for content types which would just be supported locally by the indexing engine?

**Example use-case:**

If the `BranchUniversalObject` would have a property for `htmlContentData` which may is only supported by `CoreSpotlight`, then it would be possible to index html content for the local search but still use the deep-link for App routing.

**Comment by E-B-Smith** [comment]
On you Branch universal object, you can set 
```
myBranchUniversalObject.contentMetadata.contentSchema = kUTTypeHTML;
```
to set the CSSearchableItemAttributeSet content type to html. 

---

So you're trying to create a local index with app content with a BranchUniversalObject?

Will this content also be available on the web? Or just in your app?

**Comment by E-B-Smith** [comment]
Did this help? I'll close out the issue now but you can re-open if you're still having issues.
