### ISSUE TITLE
Receiving push notifications on foreground

### ISSUE THREAD

**Issue by pangers** [BranchMetrics/ios-branch-deep-linking#885]
Hi,

I have integrated Branch into my app and I have an issue regarding receiving push notifications while the app is in the forground. I have implemented the method allowing the app to receive push notifications while the on the foreground. Just FYI, we are using another SDK for handling push notifications.

```
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {        
        completionHandler(.alert)
    }
```

When a push notification is received (while in the foreground) and the user taps on it, we pass the link from the payload to the Branch method `(BOOL)handleDeepLink:(NSURL *)url`. However, the Branch `deepLinkHandler` (from the `initSession` method) does not seem to run. Only after the app is taken to the background then brought back to the foreground, does the Branch `deepLinkHandler` run.

When a push notification is received while the app is in the background and the user taps on it, everything works great.

Is this the expected behaviour? Is there a way to have the `deepLinkHandler` to run while the app is in the foreground?

Thanks

**Comment by E-B-Smith** [comment]
I just updated the SDK to handle this situation - try updating your version of Branch to release 0.25.7.

If this doesn't fix your problem please re-open this issue and I'll take a deeper look.
