### ISSUE TITLE
URL $desktop_url: Parameter Encode

### ISSUE THREAD

**Issue by Formerly** [BranchMetrics/ios-branch-deep-linking#886]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

When the short link is opened on the PC page, the redirect URL is encoded, causing the data we want to record cannot be recorded normally. The reference code is not found in the corresponding URL @ symbol related codec. The following is the corresponding data screenshot.

https://drive.google.com/open?id=1UY8R8Y_eMneV3Z9_8t8RBw5u5UGr4rVB

https://drive.google.com/open?id=1oYKJKGQvSCtYGz7F1cDbs4nrJkAuPqc6

**Comment by E-B-Smith** [comment]
How did you create this link?

**Comment by Formerly** [comment]
{"branch_key":"xxxxxxxxx","channel":"os_api","feature":"os_api","campaign":"os_api","stage":"os_api","data":{"$android_url":"https:\/\/play.google.com\/store\/apps\/details?id=com.banggood.client","$ios_url":"https:\/\/itunes.apple.com\/app\/id906268880","$desktop_url":"https:\/\/www.banggood.com\/Xiaomi-Mi8-Mi-8-Global-Version-6_21-inch-6GB-RAM-64GB-ROM-Snapdragon-845-Octa-core-4G-Smartphone-p-1325618.html?utm_campaign=3958464_1325618&utm_content=4083&p=1@06193958464201603O?utm_campaign=3958464_1325618&utm_content=4083&p=1@06193958464201603O","$deeplink_path":"banggood:\/\/prod-1325618?utm_campaign=3958464_1325618&utm_content=4083&p=1@06193958464201603O"}}
 
 curl Send https://api.branch.io/v1/url The parameters to create are these.

The final result is: https://banggood.app.link/okh7aO1sdR

**Comment by E-B-Smith** [comment]
Thanks - I'll look into this.

**Comment by E-B-Smith** [comment]
You need make sure your URLs are correctly encoded when you create the link.

Here is the above JSON correctly encoded:

```json
{
	"branch_key": "xxxxxxxxx",
	"channel": "os_api",
	"feature": "os_api",
	"campaign": "os_api",
	"stage": "os_api",
	"data": {
		"$android_url": "https://play.google.com/store/apps/details?id=com.banggood.client",
		"$ios_url": "https://itunes.apple.com/app/id906268880",
		"$desktop_url": "https://www.banggood.com/Xiaomi-Mi8-Mi-8-Global-Version-6_21-inch-6GB-RAM-64GB-ROM-Snapdragon-845-Octa-core-4G-Smartphone-p-1325618.html?utm_campaign=3958464_1325618&utm_content=4083&p=1%4006193958464201603O&utm_campaign=3958464_1325618&utm_content=4083&p=1%4006193958464201603O",
		"$deeplink_path": "banggood://prod-1325618?utm_campaign=3958464_1325618&utm_content=4083&p=1%4006193958464201603O"
	}
}
```

I made a few changes to your example.

I converted the parameter values for `$desktop_url`:

I changed the second `p` value (did you mean to have two?)  from  `p=1@06193958464201603O` to `p=1%4006193958464201603O` and changed the `?utm_campaign=3958464_1325618` to `&utm_campaign=3958464_1325618` (query parameters should be appended with `&` after the first `?`).

Also I value for `$deeplink_path` from `p=1@06193958464201603O` to `p=1%4006193958464201603O`.

This should solve your issues!
