### ISSUE TITLE
branch.initSession not triggered

### ISSUE THREAD

**Issue by dhsu210** [BranchMetrics/ios-branch-deep-linking#894]
If there is a bug or error in this repo, please file the issue here. 

Our branch links were working perfectly fine until last week (we were on 0.25.0). There was nothing changed on our end, but I've spent the last few days testing and still cannot get `Branch.getInstance().initSession` to trigger and show the data params. This has broken our data attribution flow so would hopefully like to get this fixed asap. I've double checked our branch_live_key, the integration steps in the SDK documentation, and even added a new AASA file (we didn't have one previously) to our website.

Current code implementation besides `Branch.getInstance().initSession` in `didFinishLaunching`:

`func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool { 
var returnValue: Bool = Branch.getInstance().continue(userActivity)
return returnValue
}`

`func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
Branch.getInstance().handleDeepLink(url)
}`

`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        Branch.getInstance().application(app, open: url, options: options)
}`

I've also tried updating the the pod to 0.25.8 -- but to no avail. Can I get some help with this?

**Comment by E-B-Smith** [comment]
The latest release works for me without trouble so I wonder what's different for you...

Do the universal links at least open the app?

Also, try removing the function:

```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool { 
     Branch.getInstance().handleDeepLink(url) 
}
```

and leaving the function:

```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool
```

You only need the last one. The other was a convenience method for pre-iOS 9 compatibility.

**Comment by dhsu210** [comment]
Thanks for responding so quickly! I tried commenting out that function but it's still not entering the initSession. Do you think the AASA file might have a significant impact on this?

**Comment by dhsu210** [comment]
The app does open - I have breakpoints in my AppDelegate file, it's just that it skips over the branch.initSession without going into the breakpoints in there

**Comment by E-B-Smith** [comment]
Is your Branch key in the info.plist, and are you using the live Branch key?

**Comment by dhsu210** [comment]
Yes, it is. We had it fully integrated and functioning for a very long time so I'm not sure why it stopped working last week.

**Comment by dhsu210** [comment]
I also tried adding a `branch_app_domain`, but we are still using the standard branch domains (have not created a custom Branch domain)

**Comment by E-B-Smith** [comment]
Sorry things stopped working! Thanks for taking the time to work with me.

In your `didFinishLaunching:` method, before you initialize Branch, turn full Branch logging on by adding:

```
BNCLogSetDisplayLevel(BNCLogLevelAll);
```

In Swift I think you can just say:
```
BNCLogSetDisplayLevel(.all)
```

**Comment by E-B-Smith** [comment]
This will spit out a bunch of stuff in the debugger.

**Comment by dhsu210** [comment]
Where should I be looking to see the Branch logging?

**Comment by E-B-Smith** [comment]
Look in Xcode's debugger console or the device's console logs.

**Comment by dhsu210** [comment]
Hmm nothing is showing up in the Xcode debugger console. It's totally blank. I have it inserted right above the initSession code line.

**Comment by E-B-Smith** [comment]
Hmm.  This is what mine looks like:

<img width="887" alt="screen shot 2018-11-21 at 12 46 00 pm" src="https://user-images.githubusercontent.com/1229047/48867605-873da000-ed8b-11e8-9203-87d4a5503da7.png">

**Comment by dhsu210** [comment]
Does it affect it if I'm testing with a live branch link?

**Comment by E-B-Smith** [comment]
No.

**Comment by dhsu210** [comment]
[](url)
<img width="994" alt="screen shot 2018-11-21 at 12 56 46 pm" src="https://user-images.githubusercontent.com/10564231/48867993-f23ba680-ed8c-11e8-8466-bbdbe8b1fc0c.png">

**Comment by E-B-Smith** [comment]
Okay, continue on.  The log display may not have caught up yet.

**Comment by dhsu210** [comment]
<img width="1020" alt="screen shot 2018-11-21 at 1 00 27 pm" src="https://user-images.githubusercontent.com/10564231/48868129-73933900-ed8d-11e8-85fc-d1222bf0d38d.png">

It then jumps to the end of the initSession clause (with no logs as seen below)

<img width="1008" alt="screen shot 2018-11-21 at 1 00 30 pm" src="https://user-images.githubusercontent.com/10564231/48868131-755cfc80-ed8d-11e8-9bbc-b23642306112.png">

**Comment by E-B-Smith** [comment]
Just run it like normal - No breakpoints.

**Comment by dhsu210** [comment]
Still nothing.

For context, I'm currently running the app on my device on a Test configuration (which is linked to our Prod server), setting it to `Wait for executable to be launched`, and when Xcode is done compiling, I go to my device, click the branch link from our website, which then prompts an Open in Everlance pop up. I click OK to continue.

**Comment by E-B-Smith** [comment]
How about trying a simple build and run on the device to see if we're logging anything.

**Comment by dhsu210** [comment]
So I did a super basic Debug configuration, no break points and ran it on my device:

<img width="999" alt="screen shot 2018-11-21 at 1 29 22 pm" src="https://user-images.githubusercontent.com/10564231/48869287-890a6200-ed91-11e8-80fd-8d99de05833e.png">

**Comment by E-B-Smith** [comment]
Click on a link while your app is running in the debugger.

**Comment by dhsu210** [comment]
Sorry false alarm that not logged in is our own print statement. Will try your above suggestion

**Comment by dhsu210** [comment]
So I can't click on a live link because it redirects to the App Store instead of the app. Do you have a suggestion for using the debug app version + a link?

**Comment by dhsu210** [comment]
Since the debug app version will only run locally off my computer, I can try to run it in my Xcode simulator + click a link in the simulator safari

**Comment by E-B-Smith** [comment]
That will work.

**Comment by dhsu210** [comment]
Alright some stuff popped up. Any hints on what I should be looking for? There's quite a few more logs than this one

<img width="1004" alt="screen shot 2018-11-21 at 1 42 14 pm" src="https://user-images.githubusercontent.com/10564231/48869802-5a8d8680-ed93-11e8-90e7-9c24fe301b61.png">

**Comment by E-B-Smith** [comment]
What kind of link are you clicking on?

**Comment by E-B-Smith** [comment]
Also, have you seen this resource?

https://docs.branch.io/pages/apps/ios/#troubleshoot-issues

**Comment by dhsu210** [comment]
I'm clicking on this link [
https://bnc.lt/E9ac/bQ9znZhuCC](url). It's a link from our website.

Yes I've seen that resource and tried to troubleshoot based on those instructions.

**Comment by dhsu210** [comment]
If you click on that link on your laptop, you'll see it redirect to our web dashboard with the company logo on top (this is working correctly). If you click on the link on your mobile device, download our app from the App Store, you won't see the logo upon sign up (this is visual proof that it's not working correctly right now).

**Comment by E-B-Smith** [comment]
Thanksgiving happened!

Did you resolve this or is this still an issue?

**Comment by dhsu210** [comment]
No worries! Nope it is still an issue that I'm working on

**Comment by E-B-Smith** [comment]
Do you have any updates on this?  Deep linking and deferred deep linking are working for me, so I must be missing some crucial part of your testing.

**Comment by dhsu210** [comment]
Thanks for following up! It's still not fixed but I'm working directly with a Branch solutions engineer now and she's testing with a .ipa file I sent her. Hopefully there's something to be found there!

**Comment by E-B-Smith** [comment]
Great!  I'll close this out here then.
