### ISSUE TITLE
Deadlock when launching app in iOS 12

### ISSUE THREAD

**Issue by leandromperez** [BranchMetrics/ios-branch-deep-linking#900]
Hi,
Sometimes, very randomly, the app freezes when launching. 
Pausing the debugger I was able to see that 2 threads are in deadlock, the main thread, and a secondary thread. Both performing branch actions:
 
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000021fc5bf0c in semaphore_wait_trap ()
#1	0x0000000108ee55a0 in _dispatch_sema4_wait ()
#2	0x0000000108ee6024 in _dispatch_semaphore_wait_slow ()
#3	0x0000000106f66f6c in -[Branch processNextQueueItem] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:2036
#4	0x0000000106f660dc in -[Branch callClose] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:1937
#5	0x0000000106f65df4 in -[Branch applicationWillResignActive] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:1918
#6	0x000000022003e928 in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()

```

```

Thread 2 Queue : io.segment.analytics (serial)
#0	0x000000021fc5bf0c in semaphore_wait_trap ()
#1	0x0000000108ee55a0 in _dispatch_sema4_wait ()
#2	0x0000000108ee6024 in _dispatch_semaphore_wait_slow ()
#3	0x0000000106f66f6c in -[Branch processNextQueueItem] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:2036
#4	0x0000000106f68c0c in -[Branch initializeSession] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:2185
#5	0x0000000106f68400 in -[Branch initUserSessionAndCallCallback:] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:2123
#6	0x0000000106f57544 in -[Branch initSessionWithLaunchOptions:isReferrable:explicitlyRequestedReferrable:automaticallyDisplayController:] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:655
#7	0x0000000106f570bc in -[Branch initSessionWithLaunchOptions:isReferrable:explicitlyRequestedReferrable:automaticallyDisplayController:registerDeepLinkHandler:] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:606
#8	0x0000000106f5693c in -[Branch initSessionWithLaunchOptions:] at /XXX-app/XXX/Pods/Branch/Branch-SDK/Branch-SDK/Branch.m:557
#9	0x0000000108000674 in -[BNCBranchIntegration applicationDidFinishLaunching:] at /XXX-app/XXX/Pods/Segment-Branch/Pod/Classes/BNCBranchIntegration.m:331
#10	0x00000002200d7600 in __invoking___ ()
#11	0x000000021ffb5530 in -[NSInvocation invoke] ()

```
Please take a look at this [log file](https://github.com/BranchMetrics/ios-branch-deep-linking/files/2676378/Branch.stack.trace2.log).

Using 
- Branch (0.25.9):
    - Branch/Core (= 0.25.9)

I cannot reproduce this frequently, since the problem very random. 

Please let me know if I can help with more information. 

Any thoughts?

Thanks,
Leandro

**Comment by csalmi-branch** [comment]
Leandro,

Thank you for bringing this to our attention! We have backlogged a ticket to dig further into this issue and hopefully can find a resolution soon. In the meantime, is this blocking you or preventing use of any features?

Thank you,
Colleen

**Comment by VGudenko** [comment]
The same is for me

**Comment by leandromperez** [comment]
> Leandro,
> 
> Thank you for bringing this to our attention! We have backlogged a ticket to dig further into this issue and hopefully can find a resolution soon. In the meantime, is this blocking you or preventing use of any features?
> 
> Thank you,
> Colleen

Colleen,
Yes, this issue is causing our current release to freeze sometimes, and we just discovered new crashes in Crashlytics that might be related to this issue too.

**Comment by leandromperez** [comment]
Hi, 
@Psrinath-branch I discovered that we were creating an additional instance on top of the shared instance. That was causing race conditions and deadlocks. Just making sure a single instance was running fixed the issue.
Thanks for your assistance,
Leandro

**Comment by csalmi-branch** [comment]
Thanks for the update @leandromperez! Since you have found a resolution, I am going to close this issue. If anything else comes up, please open a new issue or reach out to our support team.
https://support.branch.io/support/home
