### ISSUE TITLE
Initialization stops working after 2-3 app quits

### ISSUE THREAD

**Issue by nikeshakya** [BranchMetrics/ios-branch-deep-linking#901]
-> Branch sdk initialization and features work when I fresh install the app
-> Once I quit app and re-open it, .init function returns error 1004 saying couldn't connect to branch server. 
-> If I delete app, reinstall it and open again, it works.
How do I resolve this issue ? Should I clear anything from instance before using it?

**Comment by csalmi-branch** [comment]
Hi @nikeshakya. What version of the SDK are you using?

**Comment by Psrinath-branch** [comment]
Hey @nikeshakya,

As @csalmi-branch mentioned, along with the SDK version, can you also share us the logs of this error? 
As per the code below, can you share us the details of branchError and its status code? 
` BNCLogError(@"An error prevented request to %@ from completing: %@",
                    request.URL.absoluteString, branchError);`

Thanks!

**Comment by Psrinath-branch** [comment]
Hey @nikeshakya - Glad to see that the error has disappeared with the latest SDK. 
With the previous error, we would recommend sharing the exact error message that appears when you query the endpoint. 
For example: requesting the URL - "https://api2.branch.io/v1/open", the resulting message seen is -
`message": "Invalid or missing app id, Branch key, or secret",
		"code":	400`
With this error message, we can suggest you with the next steps.
